-- 控制面静态表（基线重定 2026-09-06：000001/000002/000004/000006/000018/
-- 000019/000024 终态合并；POC 期无存量库，历史迁移整体退役，文档中的旧
-- 迁移号按本目录当前文件对照）。运行时组合见 docs/developer/06-databases.md。

CREATE TABLE IF NOT EXISTS projects (
    id              TEXT PRIMARY KEY,
    internal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name            TEXT NOT NULL,
    description     TEXT,
    status          TEXT NOT NULL DEFAULT 'active',
    settings        JSONB DEFAULT '{}',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_name ON projects(name);

CREATE TABLE IF NOT EXISTS api_keys (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    secret_hash TEXT NOT NULL,
    scopes      TEXT[] NOT NULL DEFAULT '{}',
    expire_at   TIMESTAMPTZ,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_keys_project ON api_keys(project_id);

-- 认证热路径按 secret_hash 点查；唯一约束即 hash 全局唯一不变式。
CREATE UNIQUE INDEX IF NOT EXISTS api_keys_secret_hash_key ON api_keys (secret_hash);

CREATE TABLE IF NOT EXISTS admins (
    id            TEXT PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'owner',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_projects (
    admin_id   TEXT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (admin_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_admin_projects_project ON admin_projects(project_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    id          TEXT PRIMARY KEY,
    project_id  TEXT,
    actor_id    TEXT,
    actor_kind  TEXT NOT NULL,
    action      TEXT NOT NULL,
    status      TEXT NOT NULL,
    ip          TEXT,
    user_agent  TEXT,
    metadata    JSONB NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resource_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_project_created ON audit_logs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created ON audit_logs(actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_id, created_at DESC) WHERE resource_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS project_oauth_providers (
    project_id    TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    provider      TEXT NOT NULL,
    enabled       BOOLEAN NOT NULL DEFAULT TRUE,
    client_id     TEXT NOT NULL,
    client_secret TEXT NOT NULL,
    scopes        TEXT[] NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (project_id, provider)
);

CREATE INDEX IF NOT EXISTS idx_project_oauth_providers_project ON project_oauth_providers(project_id);

-- 无项目头的支付/订阅/iOS 定位。写入路径在 PR6 才用；表可先建。
CREATE TABLE IF NOT EXISTS provider_resource_index (
    provider     TEXT NOT NULL,
    kind         TEXT NOT NULL,
    provider_ref TEXT NOT NULL,
    project_id   TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    PRIMARY KEY (provider, kind, provider_ref)
);

-- 写幂等缓存（redesign §4.1/§10.1）：request_id 24h 去重，只缓存成功响应。
-- 键作用域 (project_id, actor_id, request_id)：actor = 稳定归因身份
--（user id / key:<id> / system），不同 actor 同 key 不冲突。
CREATE TABLE IF NOT EXISTS idempotency_keys (
    project_id       TEXT NOT NULL,
    actor_id         TEXT NOT NULL,
    request_id       TEXT NOT NULL,
    fingerprint      TEXT NOT NULL,
    claim_token      TEXT NOT NULL,
    state            TEXT NOT NULL,
    response_payload JSONB,
    expires_at       TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (project_id, actor_id, request_id)
);

-- 惰性清理（写入时顺带删除过期行）走本索引。
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_expires_at ON idempotency_keys(expires_at);
