// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: server/v1/auth.proto

package serverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_VerifyToken_FullMethodName = "/torchwood.server.v1.AuthService/VerifyToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService 是对外凭证校验面（token introspection，OAuth2 RFC 9660
// 模式）：把进程内凭证校验能力以 Server API 暴露，供桥接服务/Agent 在
// 建立连接前判定 Torchwood 签发凭证的有效性。判定语义与请求侧认证完全
// 一致（复用同一校验器），不引入第二套校验逻辑。
type AuthServiceClient interface {
	// VerifyToken 校验 Torchwood 凭证原文并返回主体信息。
	//
	// 语义：
	//   - 任何校验失败（过期/撤销/封禁/不存在/签名无效）→ valid=false + 200，
	//     不报错（introspection 契约）；仅基础设施故障返回 5xx。
	//   - 凭证范围：端用户 access JWT 与项目 API key（sk- secret）。admin JWT、
	//     refresh token、一次性 JWT、函数执行 token 与端用户连接语义不符，
	//     一律 valid=false；一次性 token 只读判定、不消费。
	//   - 项目边界：调用者（API key 恒绑定项目；admin 会话经 X-Torchwood-Project）
	//     与凭证分属不同项目时 valid=false；平台 admin 未选项目可跨项目校验。
	//   - roles 为实时解析的角色词汇（不信任 JWT rls claim）：users /
	//     user:<id>[/verified] / group:<gid> / member:<mid> / group:<gid>/<role> /
	//     label:<l> 等。
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService 是对外凭证校验面（token introspection，OAuth2 RFC 9660
// 模式）：把进程内凭证校验能力以 Server API 暴露，供桥接服务/Agent 在
// 建立连接前判定 Torchwood 签发凭证的有效性。判定语义与请求侧认证完全
// 一致（复用同一校验器），不引入第二套校验逻辑。
type AuthServiceServer interface {
	// VerifyToken 校验 Torchwood 凭证原文并返回主体信息。
	//
	// 语义：
	//   - 任何校验失败（过期/撤销/封禁/不存在/签名无效）→ valid=false + 200，
	//     不报错（introspection 契约）；仅基础设施故障返回 5xx。
	//   - 凭证范围：端用户 access JWT 与项目 API key（sk- secret）。admin JWT、
	//     refresh token、一次性 JWT、函数执行 token 与端用户连接语义不符，
	//     一律 valid=false；一次性 token 只读判定、不消费。
	//   - 项目边界：调用者（API key 恒绑定项目；admin 会话经 X-Torchwood-Project）
	//     与凭证分属不同项目时 valid=false；平台 admin 未选项目可跨项目校验。
	//   - roles 为实时解析的角色词汇（不信任 JWT rls claim）：users /
	//     user:<id>[/verified] / group:<gid> / member:<mid> / group:<gid>/<role> /
	//     label:<l> 等。
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.server.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthService_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/v1/auth.proto",
}
