// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: server/v1/runbook.proto

package serverv1

import (
	context "context"
	v1 "github.com/torchwoodcloud/torchwood/genproto/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunbookService_GetRunbookState_FullMethodName   = "/torchwood.server.v1.RunbookService/GetRunbookState"
	RunbookService_RecordRunbookStep_FullMethodName = "/torchwood.server.v1.RunbookService/RecordRunbookStep"
	RunbookService_DeleteRunbookStep_FullMethodName = "/torchwood.server.v1.RunbookService/DeleteRunbookStep"
)

// RunbookServiceClient is the client API for RunbookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunbookService 是版本化资源迁移的状态面（docs/design/runbook.md §2.2，
// D2/D8/D9/D21）：只记录"哪些 step 已应用"的事实，不执行任何资源动作——
// 引擎在 CLI 侧，动作幂等 + 失败重跑（D7 无跨 RPC 事务，无 dirty 标记）。
// 状态是控制面表（迁移 000009），按项目隔离（项目上下文来自凭证）。
type RunbookServiceClient interface {
	// GetRunbookState 返回指定 runbook 的已应用 step 升序全集（空 = 未应用）。
	GetRunbookState(ctx context.Context, in *GetRunbookStateRequest, opts ...grpc.CallOption) (*GetRunbookStateResponse, error)
	// RecordRunbookStep 记录一个已应用的 step（CAS 语义，D8 并发防护）：
	// expect_prev_version 缺省/0 = 首步；不等于当前顶版 → FAILED_PRECONDITION
	// （并发双跑输家重拉状态收敛）。checksum = sha256(归一化后文件字节)（D9）。
	RecordRunbookStep(ctx context.Context, in *RecordRunbookStepRequest, opts ...grpc.CallOption) (*RecordRunbookStepResponse, error)
	// DeleteRunbookStep 摘除一个 step（down 回退 / forgive 逃生门 D21）：
	// 仅允许删除当前顶版（版本链单调），否则 FAILED_PRECONDITION。不执行
	// 任何资源动作——资源回退由调用方先完成再摘记录。
	DeleteRunbookStep(ctx context.Context, in *DeleteRunbookStepRequest, opts ...grpc.CallOption) (*v1.Empty, error)
}

type runbookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunbookServiceClient(cc grpc.ClientConnInterface) RunbookServiceClient {
	return &runbookServiceClient{cc}
}

func (c *runbookServiceClient) GetRunbookState(ctx context.Context, in *GetRunbookStateRequest, opts ...grpc.CallOption) (*GetRunbookStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunbookStateResponse)
	err := c.cc.Invoke(ctx, RunbookService_GetRunbookState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbookServiceClient) RecordRunbookStep(ctx context.Context, in *RecordRunbookStepRequest, opts ...grpc.CallOption) (*RecordRunbookStepResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordRunbookStepResponse)
	err := c.cc.Invoke(ctx, RunbookService_RecordRunbookStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runbookServiceClient) DeleteRunbookStep(ctx context.Context, in *DeleteRunbookStepRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, RunbookService_DeleteRunbookStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunbookServiceServer is the server API for RunbookService service.
// All implementations must embed UnimplementedRunbookServiceServer
// for forward compatibility.
//
// RunbookService 是版本化资源迁移的状态面（docs/design/runbook.md §2.2，
// D2/D8/D9/D21）：只记录"哪些 step 已应用"的事实，不执行任何资源动作——
// 引擎在 CLI 侧，动作幂等 + 失败重跑（D7 无跨 RPC 事务，无 dirty 标记）。
// 状态是控制面表（迁移 000009），按项目隔离（项目上下文来自凭证）。
type RunbookServiceServer interface {
	// GetRunbookState 返回指定 runbook 的已应用 step 升序全集（空 = 未应用）。
	GetRunbookState(context.Context, *GetRunbookStateRequest) (*GetRunbookStateResponse, error)
	// RecordRunbookStep 记录一个已应用的 step（CAS 语义，D8 并发防护）：
	// expect_prev_version 缺省/0 = 首步；不等于当前顶版 → FAILED_PRECONDITION
	// （并发双跑输家重拉状态收敛）。checksum = sha256(归一化后文件字节)（D9）。
	RecordRunbookStep(context.Context, *RecordRunbookStepRequest) (*RecordRunbookStepResponse, error)
	// DeleteRunbookStep 摘除一个 step（down 回退 / forgive 逃生门 D21）：
	// 仅允许删除当前顶版（版本链单调），否则 FAILED_PRECONDITION。不执行
	// 任何资源动作——资源回退由调用方先完成再摘记录。
	DeleteRunbookStep(context.Context, *DeleteRunbookStepRequest) (*v1.Empty, error)
	mustEmbedUnimplementedRunbookServiceServer()
}

// UnimplementedRunbookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunbookServiceServer struct{}

func (UnimplementedRunbookServiceServer) GetRunbookState(context.Context, *GetRunbookStateRequest) (*GetRunbookStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunbookState not implemented")
}
func (UnimplementedRunbookServiceServer) RecordRunbookStep(context.Context, *RecordRunbookStepRequest) (*RecordRunbookStepResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordRunbookStep not implemented")
}
func (UnimplementedRunbookServiceServer) DeleteRunbookStep(context.Context, *DeleteRunbookStepRequest) (*v1.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRunbookStep not implemented")
}
func (UnimplementedRunbookServiceServer) mustEmbedUnimplementedRunbookServiceServer() {}
func (UnimplementedRunbookServiceServer) testEmbeddedByValue()                        {}

// UnsafeRunbookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunbookServiceServer will
// result in compilation errors.
type UnsafeRunbookServiceServer interface {
	mustEmbedUnimplementedRunbookServiceServer()
}

func RegisterRunbookServiceServer(s grpc.ServiceRegistrar, srv RunbookServiceServer) {
	// If the following call panics, it indicates UnimplementedRunbookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunbookService_ServiceDesc, srv)
}

func _RunbookService_GetRunbookState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunbookStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbookServiceServer).GetRunbookState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunbookService_GetRunbookState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbookServiceServer).GetRunbookState(ctx, req.(*GetRunbookStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunbookService_RecordRunbookStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRunbookStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbookServiceServer).RecordRunbookStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunbookService_RecordRunbookStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbookServiceServer).RecordRunbookStep(ctx, req.(*RecordRunbookStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunbookService_DeleteRunbookStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunbookStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunbookServiceServer).DeleteRunbookStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunbookService_DeleteRunbookStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunbookServiceServer).DeleteRunbookStep(ctx, req.(*DeleteRunbookStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunbookService_ServiceDesc is the grpc.ServiceDesc for RunbookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunbookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.server.v1.RunbookService",
	HandlerType: (*RunbookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRunbookState",
			Handler:    _RunbookService_GetRunbookState_Handler,
		},
		{
			MethodName: "RecordRunbookStep",
			Handler:    _RunbookService_RecordRunbookStep_Handler,
		},
		{
			MethodName: "DeleteRunbookStep",
			Handler:    _RunbookService_DeleteRunbookStep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/v1/runbook.proto",
}
