// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: server/v1/runtime_vars.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	v1 "github.com/torchwoodcloud/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VarSetVisibility 是集合可见性（§2.4）：public = 任何持 project_id 的客户端
// 可匿名读；private = 项目用户（有效 Principal）可见、路人不可见。
type VarSetVisibility int32

const (
	VarSetVisibility_VAR_SET_VISIBILITY_UNSPECIFIED VarSetVisibility = 0
	VarSetVisibility_VAR_SET_VISIBILITY_PUBLIC      VarSetVisibility = 1
	VarSetVisibility_VAR_SET_VISIBILITY_PRIVATE     VarSetVisibility = 2
)

// Enum value maps for VarSetVisibility.
var (
	VarSetVisibility_name = map[int32]string{
		0: "VAR_SET_VISIBILITY_UNSPECIFIED",
		1: "VAR_SET_VISIBILITY_PUBLIC",
		2: "VAR_SET_VISIBILITY_PRIVATE",
	}
	VarSetVisibility_value = map[string]int32{
		"VAR_SET_VISIBILITY_UNSPECIFIED": 0,
		"VAR_SET_VISIBILITY_PUBLIC":      1,
		"VAR_SET_VISIBILITY_PRIVATE":     2,
	}
)

func (x VarSetVisibility) Enum() *VarSetVisibility {
	p := new(VarSetVisibility)
	*p = x
	return p
}

func (x VarSetVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VarSetVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_server_v1_runtime_vars_proto_enumTypes[0].Descriptor()
}

func (VarSetVisibility) Type() protoreflect.EnumType {
	return &file_server_v1_runtime_vars_proto_enumTypes[0]
}

func (x VarSetVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VarSetVisibility.Descriptor instead.
func (VarSetVisibility) EnumDescriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{0}
}

// RuntimeVarVersionAction 是版本链动作（runtime_var_versions.action）。
type RuntimeVarVersionAction int32

const (
	RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_UNSPECIFIED RuntimeVarVersionAction = 0
	RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_CREATE      RuntimeVarVersionAction = 1
	RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_UPDATE      RuntimeVarVersionAction = 2
	RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_DELETE      RuntimeVarVersionAction = 3
	RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_ROLLBACK    RuntimeVarVersionAction = 4
)

// Enum value maps for RuntimeVarVersionAction.
var (
	RuntimeVarVersionAction_name = map[int32]string{
		0: "RUNTIME_VAR_VERSION_ACTION_UNSPECIFIED",
		1: "RUNTIME_VAR_VERSION_ACTION_CREATE",
		2: "RUNTIME_VAR_VERSION_ACTION_UPDATE",
		3: "RUNTIME_VAR_VERSION_ACTION_DELETE",
		4: "RUNTIME_VAR_VERSION_ACTION_ROLLBACK",
	}
	RuntimeVarVersionAction_value = map[string]int32{
		"RUNTIME_VAR_VERSION_ACTION_UNSPECIFIED": 0,
		"RUNTIME_VAR_VERSION_ACTION_CREATE":      1,
		"RUNTIME_VAR_VERSION_ACTION_UPDATE":      2,
		"RUNTIME_VAR_VERSION_ACTION_DELETE":      3,
		"RUNTIME_VAR_VERSION_ACTION_ROLLBACK":    4,
	}
)

func (x RuntimeVarVersionAction) Enum() *RuntimeVarVersionAction {
	p := new(RuntimeVarVersionAction)
	*p = x
	return p
}

func (x RuntimeVarVersionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeVarVersionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_server_v1_runtime_vars_proto_enumTypes[1].Descriptor()
}

func (RuntimeVarVersionAction) Type() protoreflect.EnumType {
	return &file_server_v1_runtime_vars_proto_enumTypes[1]
}

func (x RuntimeVarVersionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeVarVersionAction.Descriptor instead.
func (RuntimeVarVersionAction) EnumDescriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{1}
}

type CreateVarSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 创建后不可改（D9 显式实体；重命名 = 重建 + 回滚替代）。
	VarSetId string `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	// 缺省 public（UNSPECIFIED 由 app 层归一）。
	Visibility    VarSetVisibility `protobuf:"varint,2,opt,name=visibility,proto3,enum=torchwood.server.v1.VarSetVisibility" json:"visibility,omitempty"`
	Description   string           `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVarSetRequest) Reset() {
	*x = CreateVarSetRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVarSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVarSetRequest) ProtoMessage() {}

func (x *CreateVarSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVarSetRequest.ProtoReflect.Descriptor instead.
func (*CreateVarSetRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVarSetRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *CreateVarSetRequest) GetVisibility() VarSetVisibility {
	if x != nil {
		return x.Visibility
	}
	return VarSetVisibility_VAR_SET_VISIBILITY_UNSPECIFIED
}

func (x *CreateVarSetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetVarSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVarSetRequest) Reset() {
	*x = GetVarSetRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVarSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVarSetRequest) ProtoMessage() {}

func (x *GetVarSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVarSetRequest.ProtoReflect.Descriptor instead.
func (*GetVarSetRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{1}
}

func (x *GetVarSetRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

type UpdateVarSetRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VarSetId string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	// proto3 optional：未设置 = 不修改（PATCH 语义）。
	Visibility    *VarSetVisibility `protobuf:"varint,2,opt,name=visibility,proto3,enum=torchwood.server.v1.VarSetVisibility,oneof" json:"visibility,omitempty"`
	Description   *string           `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVarSetRequest) Reset() {
	*x = UpdateVarSetRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVarSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVarSetRequest) ProtoMessage() {}

func (x *UpdateVarSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVarSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateVarSetRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateVarSetRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *UpdateVarSetRequest) GetVisibility() VarSetVisibility {
	if x != nil && x.Visibility != nil {
		return *x.Visibility
	}
	return VarSetVisibility_VAR_SET_VISIBILITY_UNSPECIFIED
}

func (x *UpdateVarSetRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteVarSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVarSetRequest) Reset() {
	*x = DeleteVarSetRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVarSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVarSetRequest) ProtoMessage() {}

func (x *DeleteVarSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVarSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteVarSetRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteVarSetRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

// VarSet 是集合的资源投影。etag 为不透明 token "{epoch}:{revision}"（D2：
// 客户端直接透传做轮询；epoch 掺入防同名删除重建碰撞）；revision 单独作
// 版本链寻址。var_count/total_bytes 是 footprint（D13 限额的 Console 展示）。
type VarSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Visibility    VarSetVisibility       `protobuf:"varint,2,opt,name=visibility,proto3,enum=torchwood.server.v1.VarSetVisibility" json:"visibility,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Revision      int64                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	VarCount      int32                  `protobuf:"varint,6,opt,name=var_count,json=varCount,proto3" json:"var_count,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,7,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VarSet) Reset() {
	*x = VarSet{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarSet) ProtoMessage() {}

func (x *VarSet) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarSet.ProtoReflect.Descriptor instead.
func (*VarSet) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{4}
}

func (x *VarSet) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *VarSet) GetVisibility() VarSetVisibility {
	if x != nil {
		return x.Visibility
	}
	return VarSetVisibility_VAR_SET_VISIBILITY_UNSPECIFIED
}

func (x *VarSet) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VarSet) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *VarSet) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *VarSet) GetVarCount() int32 {
	if x != nil {
		return x.VarCount
	}
	return 0
}

func (x *VarSet) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *VarSet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VarSet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListVarSetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSets       []*VarSet              `protobuf:"bytes,1,rep,name=var_sets,json=varSets,proto3" json:"var_sets,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVarSetsResponse) Reset() {
	*x = ListVarSetsResponse{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVarSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVarSetsResponse) ProtoMessage() {}

func (x *ListVarSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVarSetsResponse.ProtoReflect.Descriptor instead.
func (*ListVarSetsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{5}
}

func (x *ListVarSetsResponse) GetVarSets() []*VarSet {
	if x != nil {
		return x.VarSets
	}
	return nil
}

func (x *ListVarSetsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateRuntimeVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *RuntimeVarValue       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuntimeVarRequest) Reset() {
	*x = CreateRuntimeVarRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuntimeVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuntimeVarRequest) ProtoMessage() {}

func (x *CreateRuntimeVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuntimeVarRequest.ProtoReflect.Descriptor instead.
func (*CreateRuntimeVarRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRuntimeVarRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *CreateRuntimeVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateRuntimeVarRequest) GetValue() *RuntimeVarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateRuntimeVarRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListRuntimeVarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeVarsRequest) Reset() {
	*x = ListRuntimeVarsRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeVarsRequest) ProtoMessage() {}

func (x *ListRuntimeVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeVarsRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimeVarsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{7}
}

func (x *ListRuntimeVarsRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *ListRuntimeVarsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRuntimeVarsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetRuntimeVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeVarRequest) Reset() {
	*x = GetRuntimeVarRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeVarRequest) ProtoMessage() {}

func (x *GetRuntimeVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeVarRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeVarRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{8}
}

func (x *GetRuntimeVarRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *GetRuntimeVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type UpdateRuntimeVarRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VarSetId string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Key      string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// 必填：完整新值，类型可随本次变更（D5 无 Upsert，Update 分立）。
	Value *RuntimeVarValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// proto3 optional：未设置 = 不修改。
	Description   *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuntimeVarRequest) Reset() {
	*x = UpdateRuntimeVarRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuntimeVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuntimeVarRequest) ProtoMessage() {}

func (x *UpdateRuntimeVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuntimeVarRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuntimeVarRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRuntimeVarRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *UpdateRuntimeVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateRuntimeVarRequest) GetValue() *RuntimeVarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateRuntimeVarRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeleteRuntimeVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuntimeVarRequest) Reset() {
	*x = DeleteRuntimeVarRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuntimeVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuntimeVarRequest) ProtoMessage() {}

func (x *DeleteRuntimeVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuntimeVarRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuntimeVarRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRuntimeVarRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *DeleteRuntimeVarRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// RuntimeVar 是单个类型化变量。value 的 oneof 即类型锚点（存储 JSONB 单列 +
// value_type 列，D3）；类型创建时锁定、变更走显式 Update。
type RuntimeVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *RuntimeVarValue       `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeVar) Reset() {
	*x = RuntimeVar{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVar) ProtoMessage() {}

func (x *RuntimeVar) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVar.ProtoReflect.Descriptor instead.
func (*RuntimeVar) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{11}
}

func (x *RuntimeVar) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *RuntimeVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RuntimeVar) GetValue() *RuntimeVarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RuntimeVar) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuntimeVar) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RuntimeVar) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RuntimeVarValue 是五类型 oneof（D3）。integer 限 ±2^53−1：gateway 输出
// JSON number，TS number 超精度静默损坏。json_value 为合法 JSON 文本，
// 嵌套深度 ≤100（app 层校验，错误友好——encoding/json 万层栈保护错误不可读）。
type RuntimeVarValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RuntimeVarValue_StringValue
	//	*RuntimeVarValue_IntegerValue
	//	*RuntimeVarValue_FloatValue
	//	*RuntimeVarValue_BoolValue
	//	*RuntimeVarValue_JsonValue
	Kind          isRuntimeVarValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeVarValue) Reset() {
	*x = RuntimeVarValue{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVarValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVarValue) ProtoMessage() {}

func (x *RuntimeVarValue) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVarValue.ProtoReflect.Descriptor instead.
func (*RuntimeVarValue) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{12}
}

func (x *RuntimeVarValue) GetKind() isRuntimeVarValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RuntimeVarValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*RuntimeVarValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *RuntimeVarValue) GetIntegerValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*RuntimeVarValue_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return 0
}

func (x *RuntimeVarValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*RuntimeVarValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *RuntimeVarValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*RuntimeVarValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *RuntimeVarValue) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Kind.(*RuntimeVarValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

type isRuntimeVarValue_Kind interface {
	isRuntimeVarValue_Kind()
}

type RuntimeVarValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type RuntimeVarValue_IntegerValue struct {
	IntegerValue int64 `protobuf:"varint,2,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type RuntimeVarValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type RuntimeVarValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type RuntimeVarValue_JsonValue struct {
	JsonValue string `protobuf:"bytes,5,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

func (*RuntimeVarValue_StringValue) isRuntimeVarValue_Kind() {}

func (*RuntimeVarValue_IntegerValue) isRuntimeVarValue_Kind() {}

func (*RuntimeVarValue_FloatValue) isRuntimeVarValue_Kind() {}

func (*RuntimeVarValue_BoolValue) isRuntimeVarValue_Kind() {}

func (*RuntimeVarValue_JsonValue) isRuntimeVarValue_Kind() {}

type ListRuntimeVarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          []*RuntimeVar          `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeVarsResponse) Reset() {
	*x = ListRuntimeVarsResponse{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeVarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeVarsResponse) ProtoMessage() {}

func (x *ListRuntimeVarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeVarsResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimeVarsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{13}
}

func (x *ListRuntimeVarsResponse) GetVars() []*RuntimeVar {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *ListRuntimeVarsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListRuntimeVarVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarSetId      string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeVarVersionsRequest) Reset() {
	*x = ListRuntimeVarVersionsRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeVarVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeVarVersionsRequest) ProtoMessage() {}

func (x *ListRuntimeVarVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeVarVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimeVarVersionsRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{14}
}

func (x *ListRuntimeVarVersionsRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *ListRuntimeVarVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRuntimeVarVersionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetRuntimeVarVersionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VarSetId string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	// 版本链寻址号（revision 1 起；0 = 尚无任何版本）。
	Revision      int64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeVarVersionRequest) Reset() {
	*x = GetRuntimeVarVersionRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeVarVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeVarVersionRequest) ProtoMessage() {}

func (x *GetRuntimeVarVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeVarVersionRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeVarVersionRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{15}
}

func (x *GetRuntimeVarVersionRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *GetRuntimeVarVersionRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type RollbackRuntimeVarRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VarSetId string                 `protobuf:"bytes,1,opt,name=var_set_id,json=varSetId,proto3" json:"var_set_id,omitempty"`
	// 等于当前版本 → InvalidArgument（D12：语义错误而非幂等操作）；窗口外
	// （已被淘汰）→ NotFound "target revision pruned"。
	TargetRevision int64 `protobuf:"varint,2,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RollbackRuntimeVarRequest) Reset() {
	*x = RollbackRuntimeVarRequest{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRuntimeVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRuntimeVarRequest) ProtoMessage() {}

func (x *RollbackRuntimeVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRuntimeVarRequest.ProtoReflect.Descriptor instead.
func (*RollbackRuntimeVarRequest) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{16}
}

func (x *RollbackRuntimeVarRequest) GetVarSetId() string {
	if x != nil {
		return x.VarSetId
	}
	return ""
}

func (x *RollbackRuntimeVarRequest) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

// RuntimeVarVersion 是版本链元数据（D10：revision 复用 heads.revision，
// 版本链语义收窄为"值快照序列"；集合元数据变更不入链）。全文快照走
// GetRuntimeVarVersion。
type RuntimeVarVersion struct {
	state    protoimpl.MessageState  `protogen:"open.v1"`
	Revision int64                   `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Action   RuntimeVarVersionAction `protobuf:"varint,2,opt,name=action,proto3,enum=torchwood.server.v1.RuntimeVarVersionAction" json:"action,omitempty"`
	Summary  string                  `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	// admin:<id> / apikey:<id> / function:<id>（handler 从 Principal 填入）。
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeVarVersion) Reset() {
	*x = RuntimeVarVersion{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVarVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVarVersion) ProtoMessage() {}

func (x *RuntimeVarVersion) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVarVersion.ProtoReflect.Descriptor instead.
func (*RuntimeVarVersion) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeVarVersion) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RuntimeVarVersion) GetAction() RuntimeVarVersionAction {
	if x != nil {
		return x.Action
	}
	return RuntimeVarVersionAction_RUNTIME_VAR_VERSION_ACTION_UNSPECIFIED
}

func (x *RuntimeVarVersion) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RuntimeVarVersion) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RuntimeVarVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListRuntimeVarVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*RuntimeVarVersion   `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	Meta          *v1.ListResponseMeta   `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeVarVersionsResponse) Reset() {
	*x = ListRuntimeVarVersionsResponse{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeVarVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeVarVersionsResponse) ProtoMessage() {}

func (x *ListRuntimeVarVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeVarVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimeVarVersionsResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{18}
}

func (x *ListRuntimeVarVersionsResponse) GetVersions() []*RuntimeVarVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListRuntimeVarVersionsResponse) GetMeta() *v1.ListResponseMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// RuntimeVarVersionEntry 是版本快照全文的单键条目（{key:{t,v,d,c}} 的展开，
// D11 全列四元组：description/created_at 保留，Console 两版 diff 用）。
type RuntimeVarVersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *RuntimeVarValue       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeVarVersionEntry) Reset() {
	*x = RuntimeVarVersionEntry{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeVarVersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeVarVersionEntry) ProtoMessage() {}

func (x *RuntimeVarVersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeVarVersionEntry.ProtoReflect.Descriptor instead.
func (*RuntimeVarVersionEntry) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{19}
}

func (x *RuntimeVarVersionEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RuntimeVarVersionEntry) GetValue() *RuntimeVarValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RuntimeVarVersionEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RuntimeVarVersionEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetRuntimeVarVersionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *RuntimeVarVersion     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// 该版本的全量快照（key ASC）。
	Entries       []*RuntimeVarVersionEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeVarVersionResponse) Reset() {
	*x = GetRuntimeVarVersionResponse{}
	mi := &file_server_v1_runtime_vars_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeVarVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeVarVersionResponse) ProtoMessage() {}

func (x *GetRuntimeVarVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_runtime_vars_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeVarVersionResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeVarVersionResponse) Descriptor() ([]byte, []int) {
	return file_server_v1_runtime_vars_proto_rawDescGZIP(), []int{20}
}

func (x *GetRuntimeVarVersionResponse) GetVersion() *RuntimeVarVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetRuntimeVarVersionResponse) GetEntries() []*RuntimeVarVersionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_server_v1_runtime_vars_proto protoreflect.FileDescriptor

const file_server_v1_runtime_vars_proto_rawDesc = "" +
	"\n" +
	"\x1cserver/v1/runtime_vars.proto\x12\x13torchwood.server.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x16grpcapi/v1/authz.proto\x1a\x16shared/v1/common.proto\"\xc8\x01\n" +
	"\x13CreateVarSetRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x12E\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2%.torchwood.server.v1.VarSetVisibilityR\n" +
	"visibility\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdescription\"R\n" +
	"\x10GetVarSetRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\"\xfd\x01\n" +
	"\x13UpdateVarSetRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x12V\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2%.torchwood.server.v1.VarSetVisibilityB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00H\x00R\n" +
	"visibility\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02H\x01R\vdescription\x88\x01\x01B\r\n" +
	"\v_visibilityB\x0e\n" +
	"\f_description\"U\n" +
	"\x13DeleteVarSetRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\"\xf3\x02\n" +
	"\x06VarSet\x12\x1c\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tR\bvarSetId\x12E\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2%.torchwood.server.v1.VarSetVisibilityR\n" +
	"visibility\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\x12\x1b\n" +
	"\tvar_count\x18\x06 \x01(\x05R\bvarCount\x12\x1f\n" +
	"\vtotal_bytes\x18\a \x01(\x03R\n" +
	"totalBytes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x88\x01\n" +
	"\x13ListVarSetsResponse\x126\n" +
	"\bvar_sets\x18\x01 \x03(\v2\x1b.torchwood.server.v1.VarSetR\avarSets\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\xfd\x01\n" +
	"\x17CreateRuntimeVarRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x122\n" +
	"\x03key\x18\x02 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18@2\x12^[a-z_][a-z0-9_]*$R\x03key\x12B\n" +
	"\x05value\x18\x03 \x01(\v2$.torchwood.server.v1.RuntimeVarValueB\x06\xbaH\x03\xc8\x01\x01R\x05value\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdescription\"\xaa\x01\n" +
	"\x16ListRuntimeVarsRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xe8\a(\x00R\bpageSize\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\tpageToken\"\x8a\x01\n" +
	"\x14GetRuntimeVarRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x122\n" +
	"\x03key\x18\x02 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18@2\x12^[a-z_][a-z0-9_]*$R\x03key\"\x92\x02\n" +
	"\x17UpdateRuntimeVarRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x122\n" +
	"\x03key\x18\x02 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18@2\x12^[a-z_][a-z0-9_]*$R\x03key\x12B\n" +
	"\x05value\x18\x03 \x01(\v2$.torchwood.server.v1.RuntimeVarValueB\x06\xbaH\x03\xc8\x01\x01R\x05value\x12/\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02H\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x8d\x01\n" +
	"\x17DeleteRuntimeVarRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x122\n" +
	"\x03key\x18\x02 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18@2\x12^[a-z_][a-z0-9_]*$R\x03key\"\x90\x02\n" +
	"\n" +
	"RuntimeVar\x12\x1c\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tR\bvarSetId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x03 \x01(\v2$.torchwood.server.v1.RuntimeVarValueR\x05value\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xec\x01\n" +
	"\x0fRuntimeVarValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12@\n" +
	"\rinteger_value\x18\x02 \x01(\x03B\x19\xbaH\x16\"\x14\x18\xff\xff\xff\xff\xff\xff\xff\x0f(\x81\x80\x80\x80\x80\x80\x80\xf0\xff\x01H\x00R\fintegerValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x05 \x01(\tH\x00R\tjsonValueB\r\n" +
	"\x04kind\x12\x05\xbaH\x02\b\x01\"\x89\x01\n" +
	"\x17ListRuntimeVarsResponse\x123\n" +
	"\x04vars\x18\x01 \x03(\v2\x1f.torchwood.server.v1.RuntimeVarR\x04vars\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\xb1\x01\n" +
	"\x1dListRuntimeVarVersionsRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x12'\n" +
	"\tpage_size\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc8\x01(\x00R\bpageSize\x12'\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\tpageToken\"\x82\x01\n" +
	"\x1bGetRuntimeVarVersionRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x12#\n" +
	"\brevision\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\brevision\"\x8d\x01\n" +
	"\x19RollbackRuntimeVarRequest\x12>\n" +
	"\n" +
	"var_set_id\x18\x01 \x01(\tB \xbaH\x1d\xc8\x01\x01r\x18\x10\x01\x18(2\x12^[a-z_][a-z0-9_]*$R\bvarSetId\x120\n" +
	"\x0ftarget_revision\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\x0etargetRevision\"\xe0\x01\n" +
	"\x11RuntimeVarVersion\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12D\n" +
	"\x06action\x18\x02 \x01(\x0e2,.torchwood.server.v1.RuntimeVarVersionActionR\x06action\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9f\x01\n" +
	"\x1eListRuntimeVarVersionsResponse\x12B\n" +
	"\bversions\x18\x01 \x03(\v2&.torchwood.server.v1.RuntimeVarVersionR\bversions\x129\n" +
	"\x04meta\x18\x02 \x01(\v2%.torchwood.shared.v1.ListResponseMetaR\x04meta\"\xc3\x01\n" +
	"\x16RuntimeVarVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.torchwood.server.v1.RuntimeVarValueR\x05value\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa7\x01\n" +
	"\x1cGetRuntimeVarVersionResponse\x12@\n" +
	"\aversion\x18\x01 \x01(\v2&.torchwood.server.v1.RuntimeVarVersionR\aversion\x12E\n" +
	"\aentries\x18\x02 \x03(\v2+.torchwood.server.v1.RuntimeVarVersionEntryR\aentries*u\n" +
	"\x10VarSetVisibility\x12\"\n" +
	"\x1eVAR_SET_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19VAR_SET_VISIBILITY_PUBLIC\x10\x01\x12\x1e\n" +
	"\x1aVAR_SET_VISIBILITY_PRIVATE\x10\x02*\xe3\x01\n" +
	"\x17RuntimeVarVersionAction\x12*\n" +
	"&RUNTIME_VAR_VERSION_ACTION_UNSPECIFIED\x10\x00\x12%\n" +
	"!RUNTIME_VAR_VERSION_ACTION_CREATE\x10\x01\x12%\n" +
	"!RUNTIME_VAR_VERSION_ACTION_UPDATE\x10\x02\x12%\n" +
	"!RUNTIME_VAR_VERSION_ACTION_DELETE\x10\x03\x12'\n" +
	"#RUNTIME_VAR_VERSION_ACTION_ROLLBACK\x10\x042\x8f\x13\n" +
	"\x12RuntimeVarsService\x12\xa1\x01\n" +
	"\fCreateVarSet\x12(.torchwood.server.v1.CreateVarSetRequest\x1a\x1b.torchwood.server.v1.VarSet\"J\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/server/runtime-var-sets\x12\x94\x01\n" +
	"\vListVarSets\x12 .torchwood.shared.v1.ListRequest\x1a(.torchwood.server.v1.ListVarSetsResponse\"9\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/server/runtime-var-sets\x12\x97\x01\n" +
	"\tGetVarSet\x12%.torchwood.server.v1.GetVarSetRequest\x1a\x1b.torchwood.server.v1.VarSet\"F\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x02*\x12(/v1/server/runtime-var-sets/{var_set_id}\x12\xae\x01\n" +
	"\fUpdateVarSet\x12(.torchwood.server.v1.UpdateVarSetRequest\x1a\x1b.torchwood.server.v1.VarSet\"W\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x02-:\x01*2(/v1/server/runtime-var-sets/{var_set_id}\x12\xaa\x01\n" +
	"\fDeleteVarSet\x12(.torchwood.server.v1.DeleteVarSetRequest\x1a\x1a.torchwood.shared.v1.Empty\"T\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x02**(/v1/server/runtime-var-sets/{var_set_id}\x12\xbf\x01\n" +
	"\x10CreateRuntimeVar\x12,.torchwood.server.v1.CreateRuntimeVarRequest\x1a\x1f.torchwood.server.v1.RuntimeVar\"\\\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x022:\x01*\"-/v1/server/runtime-var-sets/{var_set_id}/vars\x12\xb9\x01\n" +
	"\x0fListRuntimeVars\x12+.torchwood.server.v1.ListRuntimeVarsRequest\x1a,.torchwood.server.v1.ListRuntimeVarsResponse\"K\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x02/\x12-/v1/server/runtime-var-sets/{var_set_id}/vars\x12\xae\x01\n" +
	"\rGetRuntimeVar\x12).torchwood.server.v1.GetRuntimeVarRequest\x1a\x1f.torchwood.server.v1.RuntimeVar\"Q\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x025\x123/v1/server/runtime-var-sets/{var_set_id}/vars/{key}\x12\xc5\x01\n" +
	"\x10UpdateRuntimeVar\x12,.torchwood.server.v1.UpdateRuntimeVarRequest\x1a\x1f.torchwood.server.v1.RuntimeVar\"b\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x028:\x01*23/v1/server/runtime-var-sets/{var_set_id}/vars/{key}\x12\xbd\x01\n" +
	"\x10DeleteRuntimeVar\x12,.torchwood.server.v1.DeleteRuntimeVarRequest\x1a\x1a.torchwood.shared.v1.Empty\"_\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x025*3/v1/server/runtime-var-sets/{var_set_id}/vars/{key}\x12\xd2\x01\n" +
	"\x16ListRuntimeVarVersions\x122.torchwood.server.v1.ListRuntimeVarVersionsRequest\x1a3.torchwood.server.v1.ListRuntimeVarVersionsResponse\"O\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x023\x121/v1/server/runtime-var-sets/{var_set_id}/versions\x12\xd7\x01\n" +
	"\x14GetRuntimeVarVersion\x120.torchwood.server.v1.GetRuntimeVarVersionRequest\x1a1.torchwood.server.v1.GetRuntimeVarVersionResponse\"Z\xea\xc4\x19\x12\"\x10\n" +
	"\fruntime_vars\x10\x01\x82\xd3\xe4\x93\x02>\x12</v1/server/runtime-var-sets/{var_set_id}/versions/{revision}\x12\xd7\x01\n" +
	"\x12RollbackRuntimeVar\x12..torchwood.server.v1.RollbackRuntimeVarRequest\x1a&.torchwood.server.v1.RuntimeVarVersion\"i\xea\xc4\x19 \x1a\x05admin\x1a\x05owner\"\x10\n" +
	"\fruntime_vars\x10\x02\x82\xd3\xe4\x93\x02?:\x01*\":/v1/server/runtime-var-sets/{var_set_id}/versions:rollback\x1a\x06\xf2\xc4\x19\x02\b\x03B\xfe\x03\x92A\xb9\x03RR\n" +
	"\adefault\x12G\n" +
	"\x1dAn unexpected error response.\x12&\n" +
	"$\x1a\".torchwood.shared.v1.ErrorResponseZ\xb4\x02\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14Format: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\xab\x01\n" +
	"\x06apiKey\x12\xa0\x01\b\x02\x12\x8e\x01The project is bound to the API key row; X-Torchwood-Project is not needed. This header is only for Console admin sessions switching projects.\x1a\tX-API-Key \x02\n" +
	"O\n" +
	"\x06cookie\x12E\b\x02\x127TORCHWOOD_session_console=<sid> (Console admin session)\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06apiKey\x12\x00z\x1e\n" +
	"\x12x-torchwood-access\x12\b\x1a\x06serverZ?github.com/torchwoodcloud/torchwood/genproto/server/v1;serverv1b\x06proto3"

var (
	file_server_v1_runtime_vars_proto_rawDescOnce sync.Once
	file_server_v1_runtime_vars_proto_rawDescData []byte
)

func file_server_v1_runtime_vars_proto_rawDescGZIP() []byte {
	file_server_v1_runtime_vars_proto_rawDescOnce.Do(func() {
		file_server_v1_runtime_vars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_runtime_vars_proto_rawDesc), len(file_server_v1_runtime_vars_proto_rawDesc)))
	})
	return file_server_v1_runtime_vars_proto_rawDescData
}

var file_server_v1_runtime_vars_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_v1_runtime_vars_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_server_v1_runtime_vars_proto_goTypes = []any{
	(VarSetVisibility)(0),                  // 0: torchwood.server.v1.VarSetVisibility
	(RuntimeVarVersionAction)(0),           // 1: torchwood.server.v1.RuntimeVarVersionAction
	(*CreateVarSetRequest)(nil),            // 2: torchwood.server.v1.CreateVarSetRequest
	(*GetVarSetRequest)(nil),               // 3: torchwood.server.v1.GetVarSetRequest
	(*UpdateVarSetRequest)(nil),            // 4: torchwood.server.v1.UpdateVarSetRequest
	(*DeleteVarSetRequest)(nil),            // 5: torchwood.server.v1.DeleteVarSetRequest
	(*VarSet)(nil),                         // 6: torchwood.server.v1.VarSet
	(*ListVarSetsResponse)(nil),            // 7: torchwood.server.v1.ListVarSetsResponse
	(*CreateRuntimeVarRequest)(nil),        // 8: torchwood.server.v1.CreateRuntimeVarRequest
	(*ListRuntimeVarsRequest)(nil),         // 9: torchwood.server.v1.ListRuntimeVarsRequest
	(*GetRuntimeVarRequest)(nil),           // 10: torchwood.server.v1.GetRuntimeVarRequest
	(*UpdateRuntimeVarRequest)(nil),        // 11: torchwood.server.v1.UpdateRuntimeVarRequest
	(*DeleteRuntimeVarRequest)(nil),        // 12: torchwood.server.v1.DeleteRuntimeVarRequest
	(*RuntimeVar)(nil),                     // 13: torchwood.server.v1.RuntimeVar
	(*RuntimeVarValue)(nil),                // 14: torchwood.server.v1.RuntimeVarValue
	(*ListRuntimeVarsResponse)(nil),        // 15: torchwood.server.v1.ListRuntimeVarsResponse
	(*ListRuntimeVarVersionsRequest)(nil),  // 16: torchwood.server.v1.ListRuntimeVarVersionsRequest
	(*GetRuntimeVarVersionRequest)(nil),    // 17: torchwood.server.v1.GetRuntimeVarVersionRequest
	(*RollbackRuntimeVarRequest)(nil),      // 18: torchwood.server.v1.RollbackRuntimeVarRequest
	(*RuntimeVarVersion)(nil),              // 19: torchwood.server.v1.RuntimeVarVersion
	(*ListRuntimeVarVersionsResponse)(nil), // 20: torchwood.server.v1.ListRuntimeVarVersionsResponse
	(*RuntimeVarVersionEntry)(nil),         // 21: torchwood.server.v1.RuntimeVarVersionEntry
	(*GetRuntimeVarVersionResponse)(nil),   // 22: torchwood.server.v1.GetRuntimeVarVersionResponse
	(*timestamppb.Timestamp)(nil),          // 23: google.protobuf.Timestamp
	(*v1.ListResponseMeta)(nil),            // 24: torchwood.shared.v1.ListResponseMeta
	(*v1.ListRequest)(nil),                 // 25: torchwood.shared.v1.ListRequest
	(*v1.Empty)(nil),                       // 26: torchwood.shared.v1.Empty
}
var file_server_v1_runtime_vars_proto_depIdxs = []int32{
	0,  // 0: torchwood.server.v1.CreateVarSetRequest.visibility:type_name -> torchwood.server.v1.VarSetVisibility
	0,  // 1: torchwood.server.v1.UpdateVarSetRequest.visibility:type_name -> torchwood.server.v1.VarSetVisibility
	0,  // 2: torchwood.server.v1.VarSet.visibility:type_name -> torchwood.server.v1.VarSetVisibility
	23, // 3: torchwood.server.v1.VarSet.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: torchwood.server.v1.VarSet.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 5: torchwood.server.v1.ListVarSetsResponse.var_sets:type_name -> torchwood.server.v1.VarSet
	24, // 6: torchwood.server.v1.ListVarSetsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	14, // 7: torchwood.server.v1.CreateRuntimeVarRequest.value:type_name -> torchwood.server.v1.RuntimeVarValue
	14, // 8: torchwood.server.v1.UpdateRuntimeVarRequest.value:type_name -> torchwood.server.v1.RuntimeVarValue
	14, // 9: torchwood.server.v1.RuntimeVar.value:type_name -> torchwood.server.v1.RuntimeVarValue
	23, // 10: torchwood.server.v1.RuntimeVar.created_at:type_name -> google.protobuf.Timestamp
	23, // 11: torchwood.server.v1.RuntimeVar.updated_at:type_name -> google.protobuf.Timestamp
	13, // 12: torchwood.server.v1.ListRuntimeVarsResponse.vars:type_name -> torchwood.server.v1.RuntimeVar
	24, // 13: torchwood.server.v1.ListRuntimeVarsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	1,  // 14: torchwood.server.v1.RuntimeVarVersion.action:type_name -> torchwood.server.v1.RuntimeVarVersionAction
	23, // 15: torchwood.server.v1.RuntimeVarVersion.created_at:type_name -> google.protobuf.Timestamp
	19, // 16: torchwood.server.v1.ListRuntimeVarVersionsResponse.versions:type_name -> torchwood.server.v1.RuntimeVarVersion
	24, // 17: torchwood.server.v1.ListRuntimeVarVersionsResponse.meta:type_name -> torchwood.shared.v1.ListResponseMeta
	14, // 18: torchwood.server.v1.RuntimeVarVersionEntry.value:type_name -> torchwood.server.v1.RuntimeVarValue
	23, // 19: torchwood.server.v1.RuntimeVarVersionEntry.created_at:type_name -> google.protobuf.Timestamp
	19, // 20: torchwood.server.v1.GetRuntimeVarVersionResponse.version:type_name -> torchwood.server.v1.RuntimeVarVersion
	21, // 21: torchwood.server.v1.GetRuntimeVarVersionResponse.entries:type_name -> torchwood.server.v1.RuntimeVarVersionEntry
	2,  // 22: torchwood.server.v1.RuntimeVarsService.CreateVarSet:input_type -> torchwood.server.v1.CreateVarSetRequest
	25, // 23: torchwood.server.v1.RuntimeVarsService.ListVarSets:input_type -> torchwood.shared.v1.ListRequest
	3,  // 24: torchwood.server.v1.RuntimeVarsService.GetVarSet:input_type -> torchwood.server.v1.GetVarSetRequest
	4,  // 25: torchwood.server.v1.RuntimeVarsService.UpdateVarSet:input_type -> torchwood.server.v1.UpdateVarSetRequest
	5,  // 26: torchwood.server.v1.RuntimeVarsService.DeleteVarSet:input_type -> torchwood.server.v1.DeleteVarSetRequest
	8,  // 27: torchwood.server.v1.RuntimeVarsService.CreateRuntimeVar:input_type -> torchwood.server.v1.CreateRuntimeVarRequest
	9,  // 28: torchwood.server.v1.RuntimeVarsService.ListRuntimeVars:input_type -> torchwood.server.v1.ListRuntimeVarsRequest
	10, // 29: torchwood.server.v1.RuntimeVarsService.GetRuntimeVar:input_type -> torchwood.server.v1.GetRuntimeVarRequest
	11, // 30: torchwood.server.v1.RuntimeVarsService.UpdateRuntimeVar:input_type -> torchwood.server.v1.UpdateRuntimeVarRequest
	12, // 31: torchwood.server.v1.RuntimeVarsService.DeleteRuntimeVar:input_type -> torchwood.server.v1.DeleteRuntimeVarRequest
	16, // 32: torchwood.server.v1.RuntimeVarsService.ListRuntimeVarVersions:input_type -> torchwood.server.v1.ListRuntimeVarVersionsRequest
	17, // 33: torchwood.server.v1.RuntimeVarsService.GetRuntimeVarVersion:input_type -> torchwood.server.v1.GetRuntimeVarVersionRequest
	18, // 34: torchwood.server.v1.RuntimeVarsService.RollbackRuntimeVar:input_type -> torchwood.server.v1.RollbackRuntimeVarRequest
	6,  // 35: torchwood.server.v1.RuntimeVarsService.CreateVarSet:output_type -> torchwood.server.v1.VarSet
	7,  // 36: torchwood.server.v1.RuntimeVarsService.ListVarSets:output_type -> torchwood.server.v1.ListVarSetsResponse
	6,  // 37: torchwood.server.v1.RuntimeVarsService.GetVarSet:output_type -> torchwood.server.v1.VarSet
	6,  // 38: torchwood.server.v1.RuntimeVarsService.UpdateVarSet:output_type -> torchwood.server.v1.VarSet
	26, // 39: torchwood.server.v1.RuntimeVarsService.DeleteVarSet:output_type -> torchwood.shared.v1.Empty
	13, // 40: torchwood.server.v1.RuntimeVarsService.CreateRuntimeVar:output_type -> torchwood.server.v1.RuntimeVar
	15, // 41: torchwood.server.v1.RuntimeVarsService.ListRuntimeVars:output_type -> torchwood.server.v1.ListRuntimeVarsResponse
	13, // 42: torchwood.server.v1.RuntimeVarsService.GetRuntimeVar:output_type -> torchwood.server.v1.RuntimeVar
	13, // 43: torchwood.server.v1.RuntimeVarsService.UpdateRuntimeVar:output_type -> torchwood.server.v1.RuntimeVar
	26, // 44: torchwood.server.v1.RuntimeVarsService.DeleteRuntimeVar:output_type -> torchwood.shared.v1.Empty
	20, // 45: torchwood.server.v1.RuntimeVarsService.ListRuntimeVarVersions:output_type -> torchwood.server.v1.ListRuntimeVarVersionsResponse
	22, // 46: torchwood.server.v1.RuntimeVarsService.GetRuntimeVarVersion:output_type -> torchwood.server.v1.GetRuntimeVarVersionResponse
	19, // 47: torchwood.server.v1.RuntimeVarsService.RollbackRuntimeVar:output_type -> torchwood.server.v1.RuntimeVarVersion
	35, // [35:48] is the sub-list for method output_type
	22, // [22:35] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_server_v1_runtime_vars_proto_init() }
func file_server_v1_runtime_vars_proto_init() {
	if File_server_v1_runtime_vars_proto != nil {
		return
	}
	file_server_v1_runtime_vars_proto_msgTypes[2].OneofWrappers = []any{}
	file_server_v1_runtime_vars_proto_msgTypes[9].OneofWrappers = []any{}
	file_server_v1_runtime_vars_proto_msgTypes[12].OneofWrappers = []any{
		(*RuntimeVarValue_StringValue)(nil),
		(*RuntimeVarValue_IntegerValue)(nil),
		(*RuntimeVarValue_FloatValue)(nil),
		(*RuntimeVarValue_BoolValue)(nil),
		(*RuntimeVarValue_JsonValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_runtime_vars_proto_rawDesc), len(file_server_v1_runtime_vars_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_runtime_vars_proto_goTypes,
		DependencyIndexes: file_server_v1_runtime_vars_proto_depIdxs,
		EnumInfos:         file_server_v1_runtime_vars_proto_enumTypes,
		MessageInfos:      file_server_v1_runtime_vars_proto_msgTypes,
	}.Build()
	File_server_v1_runtime_vars_proto = out.File
	file_server_v1_runtime_vars_proto_goTypes = nil
	file_server_v1_runtime_vars_proto_depIdxs = nil
}
