// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Security      *Security              `protobuf:"bytes,2,opt,name=security,proto3" json:"security,omitempty"`
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Storage       *Storage               `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Functions     *Functions             `protobuf:"bytes,5,opt,name=functions,proto3" json:"functions,omitempty"`
	Telemetry     *Telemetry             `protobuf:"bytes,6,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Messaging     *Messaging             `protobuf:"bytes,7,opt,name=messaging,proto3" json:"messaging,omitempty"`
	Idgen         *IdGen                 `protobuf:"bytes,8,opt,name=idgen,proto3" json:"idgen,omitempty"`
	Payments      *Payments              `protobuf:"bytes,9,opt,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *AppConfig) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *AppConfig) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *AppConfig) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppConfig) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *AppConfig) GetFunctions() *Functions {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *AppConfig) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *AppConfig) GetMessaging() *Messaging {
	if x != nil {
		return x.Messaging
	}
	return nil
}

func (x *AppConfig) GetIdgen() *IdGen {
	if x != nil {
		return x.Idgen
	}
	return nil
}

func (x *AppConfig) GetPayments() *Payments {
	if x != nil {
		return x.Payments
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPC                  `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Http          *Http                  `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	Metrics       *Http                  `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHttp() *Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetMetrics() *Http {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GRPC) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Http struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Addr    string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Cors    *Http_Cors             `protobuf:"bytes,3,opt,name=cors,proto3" json:"cors,omitempty"`
	// Public base URL used to construct OAuth redirect URIs, e.g. https://api.example.com
	PublicUrl     string `protobuf:"bytes,4,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Http) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Http) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Http) GetCors() *Http_Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

func (x *Http) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type Security struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Jwt    *Security_Jwt          `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	ApiKey *Security_ApiKey       `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Trusted proxy CIDRs (e.g. 10.0.0.0/8). Only peers matching these ranges
	// may supply X-Forwarded-For / X-Real-Ip; otherwise the peer address is used.
	TrustedProxies []string `protobuf:"bytes,3,rep,name=trusted_proxies,json=trustedProxies,proto3" json:"trusted_proxies,omitempty"`
	// Console bootstrap token required to sign up the first admin. When empty,
	// Console SignUp is rejected (prevents setup takeover).
	SetupToken string              `protobuf:"bytes,4,opt,name=setup_token,json=setupToken,proto3" json:"setup_token,omitempty"`
	Sessions   *Security_Sessions  `protobuf:"bytes,5,opt,name=sessions,proto3" json:"sessions,omitempty"`
	RateLimit  *Security_RateLimit `protobuf:"bytes,6,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	// Static data-encryption key (OAuth client secrets / TOTP secrets, secretbox
	// AES-256-GCM). Independent from jwt.secret; when empty the JWT secret is
	// used as fallback (startup warns). env: TORCHWOOD_SECURITY_ENCRYPTION_KEY
	EncryptionKey string `protobuf:"bytes,7,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	// 认证面局部频控（T-01）：登录失败双维计数 + 注册 IP 频控。均按"失败
	// 计数 + 滑动窗口"语义，成功登录/注册重置相关键；未配置的维度使用
	// 内置默认值（email/ip 各 5 次/60s，signup_ip 10 次/小时）。
	LoginThrottle *Security_LoginThrottle `protobuf:"bytes,8,opt,name=login_throttle,json=loginThrottle,proto3" json:"login_throttle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Security) GetJwt() *Security_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Security) GetApiKey() *Security_ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *Security) GetTrustedProxies() []string {
	if x != nil {
		return x.TrustedProxies
	}
	return nil
}

func (x *Security) GetSetupToken() string {
	if x != nil {
		return x.SetupToken
	}
	return ""
}

func (x *Security) GetSessions() *Security_Sessions {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *Security) GetRateLimit() *Security_RateLimit {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *Security) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *Security) GetLoginThrottle() *Security_LoginThrottle {
	if x != nil {
		return x.LoginThrottle
	}
	return nil
}

type Database struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Debug  bool                   `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`
	Pool   *Database_Pool         `protobuf:"bytes,3,opt,name=pool,proto3" json:"pool,omitempty"`
	// 慢查询日志阈值（如 "500ms"）；空字符串 = 默认 500ms；"0" = 禁用。
	SlowQueryThreshold string `protobuf:"bytes,4,opt,name=slow_query_threshold,json=slowQueryThreshold,proto3" json:"slow_query_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Database) GetPool() *Database_Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *Database) GetSlowQueryThreshold() string {
	if x != nil {
		return x.SlowQueryThreshold
	}
	return ""
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	S3            *Storage_S3            `protobuf:"bytes,2,opt,name=s3,proto3" json:"s3,omitempty"`
	Local         *Storage_Local         `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Storage) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Storage) GetS3() *Storage_S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

func (x *Storage) GetLocal() *Storage_Local {
	if x != nil {
		return x.Local
	}
	return nil
}

type Functions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// executor 是执行器选择：默认 "docker"（v1 每请求一容器，进程内执行，
	// 回退模式）；"dispatcher"（v2 常驻 runner 为默认执行模型，经
	// functions-dispatcher 分发）。二选一，不同时启用。
	Executor      string                  `protobuf:"bytes,1,opt,name=executor,proto3" json:"executor,omitempty"`
	Docker        *Functions_Docker       `protobuf:"bytes,2,opt,name=docker,proto3" json:"docker,omitempty"`
	Execution     *Functions_Execution    `protobuf:"bytes,3,opt,name=execution,proto3" json:"execution,omitempty"`
	Dispatcher    *Functions_Dispatcher   `protobuf:"bytes,4,opt,name=dispatcher,proto3" json:"dispatcher,omitempty"`
	Trigger       *Functions_Trigger      `protobuf:"bytes,5,opt,name=trigger,proto3" json:"trigger,omitempty"`
	ClientInvoke  *Functions_ClientInvoke `protobuf:"bytes,6,opt,name=client_invoke,json=clientInvoke,proto3" json:"client_invoke,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions) Reset() {
	*x = Functions{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions) ProtoMessage() {}

func (x *Functions) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions.ProtoReflect.Descriptor instead.
func (*Functions) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Functions) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *Functions) GetDocker() *Functions_Docker {
	if x != nil {
		return x.Docker
	}
	return nil
}

func (x *Functions) GetExecution() *Functions_Execution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *Functions) GetDispatcher() *Functions_Dispatcher {
	if x != nil {
		return x.Dispatcher
	}
	return nil
}

func (x *Functions) GetTrigger() *Functions_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *Functions) GetClientInvoke() *Functions_ClientInvoke {
	if x != nil {
		return x.ClientInvoke
	}
	return nil
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	OtlpEndpoint  string                 `protobuf:"bytes,2,opt,name=otlp_endpoint,json=otlpEndpoint,proto3" json:"otlp_endpoint,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *Telemetry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Telemetry) GetOtlpEndpoint() string {
	if x != nil {
		return x.OtlpEndpoint
	}
	return ""
}

func (x *Telemetry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type Messaging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Smtp  *Messaging_SMTP        `protobuf:"bytes,1,opt,name=smtp,proto3" json:"smtp,omitempty"`
	// When true and SMTP host is empty, OTP codes are written to the application log (development only).
	DevLogOtp bool `protobuf:"varint,2,opt,name=dev_log_otp,json=devLogOtp,proto3" json:"dev_log_otp,omitempty"`
	Sms       *SMS `protobuf:"bytes,3,opt,name=sms,proto3" json:"sms,omitempty"`
	// When true and SMS provider is empty, OTP codes are written to the application log (development only).
	DevLogSms     bool `protobuf:"varint,4,opt,name=dev_log_sms,json=devLogSms,proto3" json:"dev_log_sms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messaging) Reset() {
	*x = Messaging{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messaging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messaging) ProtoMessage() {}

func (x *Messaging) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messaging.ProtoReflect.Descriptor instead.
func (*Messaging) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *Messaging) GetSmtp() *Messaging_SMTP {
	if x != nil {
		return x.Smtp
	}
	return nil
}

func (x *Messaging) GetDevLogOtp() bool {
	if x != nil {
		return x.DevLogOtp
	}
	return false
}

func (x *Messaging) GetSms() *SMS {
	if x != nil {
		return x.Sms
	}
	return nil
}

func (x *Messaging) GetDevLogSms() bool {
	if x != nil {
		return x.DevLogSms
	}
	return false
}

type SMS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // twilio
	Twilio        *Twilio                `protobuf:"bytes,2,opt,name=twilio,proto3" json:"twilio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMS) Reset() {
	*x = SMS{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMS) ProtoMessage() {}

func (x *SMS) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMS.ProtoReflect.Descriptor instead.
func (*SMS) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *SMS) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SMS) GetTwilio() *Twilio {
	if x != nil {
		return x.Twilio
	}
	return nil
}

type Twilio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountSid    string                 `protobuf:"bytes,1,opt,name=account_sid,json=accountSid,proto3" json:"account_sid,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Twilio) Reset() {
	*x = Twilio{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Twilio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Twilio) ProtoMessage() {}

func (x *Twilio) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Twilio.ProtoReflect.Descriptor instead.
func (*Twilio) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{13}
}

func (x *Twilio) GetAccountSid() string {
	if x != nil {
		return x.AccountSid
	}
	return ""
}

func (x *Twilio) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *Twilio) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type IdGen struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefaultStrategy string                 `protobuf:"bytes,1,opt,name=default_strategy,json=defaultStrategy,proto3" json:"default_strategy,omitempty"` // uuid | ulid | snowflake | sequence | random
	Random          *IdGen_Random          `protobuf:"bytes,2,opt,name=random,proto3" json:"random,omitempty"`
	Snowflake       *IdGen_Snowflake       `protobuf:"bytes,3,opt,name=snowflake,proto3" json:"snowflake,omitempty"`
	Sequence        *IdGen_Sequence        `protobuf:"bytes,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Resources       *IdGen_Resources       `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdGen) Reset() {
	*x = IdGen{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGen) ProtoMessage() {}

func (x *IdGen) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGen.ProtoReflect.Descriptor instead.
func (*IdGen) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14}
}

func (x *IdGen) GetDefaultStrategy() string {
	if x != nil {
		return x.DefaultStrategy
	}
	return ""
}

func (x *IdGen) GetRandom() *IdGen_Random {
	if x != nil {
		return x.Random
	}
	return nil
}

func (x *IdGen) GetSnowflake() *IdGen_Snowflake {
	if x != nil {
		return x.Snowflake
	}
	return nil
}

func (x *IdGen) GetSequence() *IdGen_Sequence {
	if x != nil {
		return x.Sequence
	}
	return nil
}

func (x *IdGen) GetResources() *IdGen_Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

// Payments 是 v3 支付子域配置（设计 §1.2）。渠道 secret 一律走
// TORCHWOOD_ 环境变量，不写入 config.yaml；未配置时服务可启动，
// 相关操作 fail-closed。
type Payments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stripe        *Payments_Stripe       `protobuf:"bytes,1,opt,name=stripe,proto3" json:"stripe,omitempty"`
	Wechat        *Payments_WeChat       `protobuf:"bytes,2,opt,name=wechat,proto3" json:"wechat,omitempty"`
	Alipay        *Payments_Alipay       `protobuf:"bytes,3,opt,name=alipay,proto3" json:"alipay,omitempty"`
	IosIap        *Payments_IosIap       `protobuf:"bytes,4,opt,name=ios_iap,json=iosIap,proto3" json:"ios_iap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payments) Reset() {
	*x = Payments{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payments) ProtoMessage() {}

func (x *Payments) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payments.ProtoReflect.Descriptor instead.
func (*Payments) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15}
}

func (x *Payments) GetStripe() *Payments_Stripe {
	if x != nil {
		return x.Stripe
	}
	return nil
}

func (x *Payments) GetWechat() *Payments_WeChat {
	if x != nil {
		return x.Wechat
	}
	return nil
}

func (x *Payments) GetAlipay() *Payments_Alipay {
	if x != nil {
		return x.Alipay
	}
	return nil
}

func (x *Payments) GetIosIap() *Payments_IosIap {
	if x != nil {
		return x.IosIap
	}
	return nil
}

type Http_Cors struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowOrigins     []string               `protobuf:"bytes,1,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods     []string               `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders     []string               `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders    []string               `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAge           int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Http_Cors) Reset() {
	*x = Http_Cors{}
	mi := &file_config_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http_Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http_Cors) ProtoMessage() {}

func (x *Http_Cors) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http_Cors.ProtoReflect.Descriptor instead.
func (*Http_Cors) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Http_Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Http_Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Http_Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Http_Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Http_Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Http_Cors) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

type Security_Jwt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	AccessTtl     string                 `protobuf:"bytes,2,opt,name=access_ttl,json=accessTtl,proto3" json:"access_ttl,omitempty"`
	RefreshTtl    string                 `protobuf:"bytes,3,opt,name=refresh_ttl,json=refreshTtl,proto3" json:"refresh_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_Jwt) Reset() {
	*x = Security_Jwt{}
	mi := &file_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Jwt) ProtoMessage() {}

func (x *Security_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_Jwt.ProtoReflect.Descriptor instead.
func (*Security_Jwt) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Security_Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_Jwt) GetAccessTtl() string {
	if x != nil {
		return x.AccessTtl
	}
	return ""
}

func (x *Security_Jwt) GetRefreshTtl() string {
	if x != nil {
		return x.RefreshTtl
	}
	return ""
}

type Security_ApiKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_ApiKey) Reset() {
	*x = Security_ApiKey{}
	mi := &file_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_ApiKey) ProtoMessage() {}

func (x *Security_ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_ApiKey.ProtoReflect.Descriptor instead.
func (*Security_ApiKey) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Security_ApiKey) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

type Security_Sessions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单用户最大并发会话数（end-user sessions）；未配置/0 = 默认 50；-1 = 不限。
	MaxPerUser    int32 `protobuf:"varint,1,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_Sessions) Reset() {
	*x = Security_Sessions{}
	mi := &file_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Sessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Sessions) ProtoMessage() {}

func (x *Security_Sessions) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_Sessions.ProtoReflect.Descriptor instead.
func (*Security_Sessions) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 2}
}

func (x *Security_Sessions) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

type Security_RateLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 通用 API 限流总开关；默认 true（未显式配置为 false 即开启）。
	Enabled *bool                         `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Ip      *Security_RateLimit_Dimension `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	User    *Security_RateLimit_Dimension `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	ApiKey  *Security_RateLimit_Dimension `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// 函数执行身份维度（P0）：按 project:function 计数，默认对齐 api-key
	// 档 6000/min；必须在 user 维度回落之前特判（每次执行独立 ActorID，
	// 落 user 维度 = 实质不限流；全部容器经 bridge NAT 同 IP，落 IP 维度
	// = 互相击穿）。见 internal/api/interceptor/ratelimit.go。
	FunctionsExecution *Security_RateLimit_Dimension `protobuf:"bytes,5,opt,name=functions_execution,json=functionsExecution,proto3" json:"functions_execution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Security_RateLimit) Reset() {
	*x = Security_RateLimit{}
	mi := &file_config_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_RateLimit) ProtoMessage() {}

func (x *Security_RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_RateLimit.ProtoReflect.Descriptor instead.
func (*Security_RateLimit) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 3}
}

func (x *Security_RateLimit) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *Security_RateLimit) GetIp() *Security_RateLimit_Dimension {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Security_RateLimit) GetUser() *Security_RateLimit_Dimension {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Security_RateLimit) GetApiKey() *Security_RateLimit_Dimension {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *Security_RateLimit) GetFunctionsExecution() *Security_RateLimit_Dimension {
	if x != nil {
		return x.FunctionsExecution
	}
	return nil
}

type Security_LoginThrottle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 按账号（email 小写规范化）维度的失败计数上限与窗口。
	Email *Security_RateLimit_Dimension `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 按来源 IP 维度的失败计数上限与窗口（经 trusted-proxy 校验后的 IP）。
	Ip *Security_RateLimit_Dimension `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	// SignUp 按来源 IP 的注册频控上限与窗口。
	SignupIp *Security_RateLimit_Dimension `protobuf:"bytes,3,opt,name=signup_ip,json=signupIp,proto3" json:"signup_ip,omitempty"`
	// X-API-Key 认证失败按来源 IP 的频控（T-02；默认 10 次/60s）。
	ApiKeyAuth    *Security_RateLimit_Dimension `protobuf:"bytes,4,opt,name=api_key_auth,json=apiKeyAuth,proto3" json:"api_key_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_LoginThrottle) Reset() {
	*x = Security_LoginThrottle{}
	mi := &file_config_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_LoginThrottle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_LoginThrottle) ProtoMessage() {}

func (x *Security_LoginThrottle) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_LoginThrottle.ProtoReflect.Descriptor instead.
func (*Security_LoginThrottle) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 4}
}

func (x *Security_LoginThrottle) GetEmail() *Security_RateLimit_Dimension {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *Security_LoginThrottle) GetIp() *Security_RateLimit_Dimension {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Security_LoginThrottle) GetSignupIp() *Security_RateLimit_Dimension {
	if x != nil {
		return x.SignupIp
	}
	return nil
}

func (x *Security_LoginThrottle) GetApiKeyAuth() *Security_RateLimit_Dimension {
	if x != nil {
		return x.ApiKeyAuth
	}
	return nil
}

type Security_RateLimit_Dimension struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每窗口允许的最大请求数；未配置/<=0 使用拦截器内置默认值。
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 窗口时长字符串（如 "60s"）；未配置/非法格式使用拦截器内置默认值。
	Window        string `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security_RateLimit_Dimension) Reset() {
	*x = Security_RateLimit_Dimension{}
	mi := &file_config_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_RateLimit_Dimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_RateLimit_Dimension) ProtoMessage() {}

func (x *Security_RateLimit_Dimension) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_RateLimit_Dimension.ProtoReflect.Descriptor instead.
func (*Security_RateLimit_Dimension) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 3, 0}
}

func (x *Security_RateLimit_Dimension) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Security_RateLimit_Dimension) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type Database_Pool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxIdleConns    int32                  `protobuf:"varint,1,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,3,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime string                 `protobuf:"bytes,4,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Database_Pool) Reset() {
	*x = Database_Pool{}
	mi := &file_config_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Pool) ProtoMessage() {}

func (x *Database_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Pool.ProtoReflect.Descriptor instead.
func (*Database_Pool) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Database_Pool) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Database_Pool) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Database_Pool) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Database_Pool) GetConnMaxIdleTime() string {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return ""
}

type Storage_S3 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Bucket          string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	AccessKeyId     string                 `protobuf:"bytes,4,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,5,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	UseSsl          bool                   `protobuf:"varint,6,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Storage_S3) Reset() {
	*x = Storage_S3{}
	mi := &file_config_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage_S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage_S3) ProtoMessage() {}

func (x *Storage_S3) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage_S3.ProtoReflect.Descriptor instead.
func (*Storage_S3) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Storage_S3) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Storage_S3) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Storage_S3) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *Storage_S3) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *Storage_S3) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *Storage_S3) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type Storage_Local struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage_Local) Reset() {
	*x = Storage_Local{}
	mi := &file_config_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage_Local) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage_Local) ProtoMessage() {}

func (x *Storage_Local) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage_Local.ProtoReflect.Descriptor instead.
func (*Storage_Local) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Storage_Local) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Functions_Docker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions_Docker) Reset() {
	*x = Functions_Docker{}
	mi := &file_config_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_Docker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_Docker) ProtoMessage() {}

func (x *Functions_Docker) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_Docker.ProtoReflect.Descriptor instead.
func (*Functions_Docker) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Functions_Docker) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Functions_Docker) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Functions_Docker) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

// Execution 是执行身份（P0）相关配置：函数容器经 bridge NAT 回访
// Server API 只能走外部端点（server 不在 tw-func-<project> 网络上），
// 平台经 TW_API_BASE_URL env 注入可达地址；空 = 不注入该变量（函数
// 需自行解析，自托管部署文档要求显式配置）。
type Functions_Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiBaseUrl    string                 `protobuf:"bytes,1,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions_Execution) Reset() {
	*x = Functions_Execution{}
	mi := &file_config_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_Execution) ProtoMessage() {}

func (x *Functions_Execution) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_Execution.ProtoReflect.Descriptor instead.
func (*Functions_Execution) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Functions_Execution) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

// Dispatcher 是执行器 v2 的分发通路配置（P0.5，owner 拍板方案③：独立
// functions-dispatcher 进程专职持有 docker.sock、join 项目网络、承接
// Build/Execute/RemoveImage 全部 daemon 操作；server/worker 零 daemon
// 依赖）。executor="docker"（v1 回退）时本节不生效。
type Functions_Dispatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dispatcher 的内网 HTTP 基址（server/worker 侧消费），如
	// http://functions-dispatcher:9070。executor="dispatcher" 时必填。
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// 静态共享密钥（内网专用可选认证；空 = 不校验，仅限可信内网）。
	SharedToken string `protobuf:"bytes,2,opt,name=shared_token,json=sharedToken,proto3" json:"shared_token,omitempty"`
	// ——以下仅 functions-dispatcher 进程消费（池策略全局参数）——
	// 每 daemon 常驻实例总量上限（设计 Q11 拍板：默认 8；防单项目耗尽宿主内存）。
	MaxResidentInstances int32 `protobuf:"varint,3,opt,name=max_resident_instances,json=maxResidentInstances,proto3" json:"max_resident_instances,omitempty"`
	// 单函数有界排队深度上限（超限立即 ResourceExhausted；默认 32）。
	QueueDepth int32 `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	// 队首超时：等待空闲实例的最长时间（如 "10s"；默认 10s，超时
	// ResourceExhausted——同步调用方不得无界等在 30s ctx 上）。
	QueueHeadTimeout string `protobuf:"bytes,5,opt,name=queue_head_timeout,json=queueHeadTimeout,proto3" json:"queue_head_timeout,omitempty"`
	// 实例启动健康探针等待上限（如 "60s"；默认 60s，超时回收并报错）。
	BootTimeout string `protobuf:"bytes,6,opt,name=boot_timeout,json=bootTimeout,proto3" json:"boot_timeout,omitempty"`
	// dispatcher HTTP 监听地址（仅内网；默认 ":9070"）。
	Addr string `protobuf:"bytes,7,opt,name=addr,proto3" json:"addr,omitempty"`
	// 函数网络内需可达的 server 容器名（如 compose 的 container_name）。
	// 非空时，dispatcher 在 join 项目网络（含 internal 变体）的同时把该
	// 容器一并 attach——函数经容器名 DNS 回访平台 API
	// （functions.execution.api_base_url = http://<该名字>:<端口>）。
	// 不可信函数在 internal 网络（无 NAT 出口），这是其回访平台的唯一通路；
	// 容器名 DNS 在 user-defined 网络（含 internal）上由内置 DNS 解析。
	// attach 失败不阻断执行（函数可能无需回访），但会记警告——部署时应
	// 在首次执行前修正。空 = 不 attach（api_base_url 须另行保证可达）。
	CallbackContainer string `protobuf:"bytes,8,opt,name=callback_container,json=callbackContainer,proto3" json:"callback_container,omitempty"`
	// 实例累计超时熔断阈值（functions v3 §1.4：超时不杀实例后，实例累计
	// 超时达到该阈值即杀实例重建，防僵尸负载慢性塞满事件循环；默认 5）。
	TimeoutBudget uint32 `protobuf:"varint,9,opt,name=timeout_budget,json=timeoutBudget,proto3" json:"timeout_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Functions_Dispatcher) Reset() {
	*x = Functions_Dispatcher{}
	mi := &file_config_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_Dispatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_Dispatcher) ProtoMessage() {}

func (x *Functions_Dispatcher) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_Dispatcher.ProtoReflect.Descriptor instead.
func (*Functions_Dispatcher) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 2}
}

func (x *Functions_Dispatcher) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Functions_Dispatcher) GetSharedToken() string {
	if x != nil {
		return x.SharedToken
	}
	return ""
}

func (x *Functions_Dispatcher) GetMaxResidentInstances() int32 {
	if x != nil {
		return x.MaxResidentInstances
	}
	return 0
}

func (x *Functions_Dispatcher) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *Functions_Dispatcher) GetQueueHeadTimeout() string {
	if x != nil {
		return x.QueueHeadTimeout
	}
	return ""
}

func (x *Functions_Dispatcher) GetBootTimeout() string {
	if x != nil {
		return x.BootTimeout
	}
	return ""
}

func (x *Functions_Dispatcher) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Functions_Dispatcher) GetCallbackContainer() string {
	if x != nil {
		return x.CallbackContainer
	}
	return ""
}

func (x *Functions_Dispatcher) GetTimeoutBudget() uint32 {
	if x != nil {
		return x.TimeoutBudget
	}
	return 0
}

// Trigger 是触发器模块平台级配置（P1 触发器模块）。
type Functions_Trigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP 触发器 per-IP 固定窗口限频（次/分钟；默认 3000）。独立更高默认：
	// 微信等回调出口 IP 段集中，沿用全局 300/min 会在发奖风暴下 429 →
	// 重试耗尽 → 事件丢失（设计 §3 三轮复核）。
	HttpIpPerMinute int32 `protobuf:"varint,1,opt,name=http_ip_per_minute,json=httpIpPerMinute,proto3" json:"http_ip_per_minute,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Functions_Trigger) Reset() {
	*x = Functions_Trigger{}
	mi := &file_config_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_Trigger) ProtoMessage() {}

func (x *Functions_Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_Trigger.ProtoReflect.Descriptor instead.
func (*Functions_Trigger) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 3}
}

func (x *Functions_Trigger) GetHttpIpPerMinute() int32 {
	if x != nil {
		return x.HttpIpPerMinute
	}
	return 0
}

// ClientInvoke 是客户端调用面平台级配置（P2 客户端调用面；per-function 的
// 限频配额/窗口在 functions 表策略列上，不在本节）。
type Functions_ClientInvoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每用户并发闸门上限（默认 2，防单用户挤占执行槽）。进程内 keyed
	// 信号量——多实例部署下为近似全局（每实例各 2）。
	PerUserConcurrency int32 `protobuf:"varint,1,opt,name=per_user_concurrency,json=perUserConcurrency,proto3" json:"per_user_concurrency,omitempty"`
	// 并发闸门排队队首超时（如 "5s"；默认 5s，超时 ResourceExhausted——
	// 同步调用方不得无界等待）。
	QueueHeadTimeout string `protobuf:"bytes,2,opt,name=queue_head_timeout,json=queueHeadTimeout,proto3" json:"queue_head_timeout,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Functions_ClientInvoke) Reset() {
	*x = Functions_ClientInvoke{}
	mi := &file_config_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Functions_ClientInvoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Functions_ClientInvoke) ProtoMessage() {}

func (x *Functions_ClientInvoke) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Functions_ClientInvoke.ProtoReflect.Descriptor instead.
func (*Functions_ClientInvoke) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 4}
}

func (x *Functions_ClientInvoke) GetPerUserConcurrency() int32 {
	if x != nil {
		return x.PerUserConcurrency
	}
	return 0
}

func (x *Functions_ClientInvoke) GetQueueHeadTimeout() string {
	if x != nil {
		return x.QueueHeadTimeout
	}
	return ""
}

type Messaging_SMTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	UseTls        bool                   `protobuf:"varint,6,opt,name=use_tls,json=useTls,proto3" json:"use_tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Messaging_SMTP) Reset() {
	*x = Messaging_SMTP{}
	mi := &file_config_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Messaging_SMTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Messaging_SMTP) ProtoMessage() {}

func (x *Messaging_SMTP) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Messaging_SMTP.ProtoReflect.Descriptor instead.
func (*Messaging_SMTP) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11, 0}
}

func (x *Messaging_SMTP) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Messaging_SMTP) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Messaging_SMTP) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Messaging_SMTP) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Messaging_SMTP) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Messaging_SMTP) GetUseTls() bool {
	if x != nil {
		return x.UseTls
	}
	return false
}

type IdGen_Random struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Length         int32                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Charset        string                 `protobuf:"bytes,2,opt,name=charset,proto3" json:"charset,omitempty"` // numeric | alphanumeric
	RedisKeyPrefix string                 `protobuf:"bytes,3,opt,name=redis_key_prefix,json=redisKeyPrefix,proto3" json:"redis_key_prefix,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdGen_Random) Reset() {
	*x = IdGen_Random{}
	mi := &file_config_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGen_Random) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGen_Random) ProtoMessage() {}

func (x *IdGen_Random) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGen_Random.ProtoReflect.Descriptor instead.
func (*IdGen_Random) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14, 0}
}

func (x *IdGen_Random) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *IdGen_Random) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *IdGen_Random) GetRedisKeyPrefix() string {
	if x != nil {
		return x.RedisKeyPrefix
	}
	return ""
}

func (x *IdGen_Random) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

type IdGen_Snowflake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdGen_Snowflake) Reset() {
	*x = IdGen_Snowflake{}
	mi := &file_config_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGen_Snowflake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGen_Snowflake) ProtoMessage() {}

func (x *IdGen_Snowflake) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGen_Snowflake.ProtoReflect.Descriptor instead.
func (*IdGen_Snowflake) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14, 1}
}

func (x *IdGen_Snowflake) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type IdGen_Sequence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RedisKeyPrefix string                 `protobuf:"bytes,1,opt,name=redis_key_prefix,json=redisKeyPrefix,proto3" json:"redis_key_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdGen_Sequence) Reset() {
	*x = IdGen_Sequence{}
	mi := &file_config_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGen_Sequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGen_Sequence) ProtoMessage() {}

func (x *IdGen_Sequence) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGen_Sequence.ProtoReflect.Descriptor instead.
func (*IdGen_Sequence) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14, 2}
}

func (x *IdGen_Sequence) GetRedisKeyPrefix() string {
	if x != nil {
		return x.RedisKeyPrefix
	}
	return ""
}

type IdGen_Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         string                 `protobuf:"bytes,1,opt,name=users,proto3" json:"users,omitempty"`
	Sessions      string                 `protobuf:"bytes,2,opt,name=sessions,proto3" json:"sessions,omitempty"`
	Documents     string                 `protobuf:"bytes,3,opt,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdGen_Resources) Reset() {
	*x = IdGen_Resources{}
	mi := &file_config_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGen_Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGen_Resources) ProtoMessage() {}

func (x *IdGen_Resources) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGen_Resources.ProtoReflect.Descriptor instead.
func (*IdGen_Resources) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{14, 3}
}

func (x *IdGen_Resources) GetUsers() string {
	if x != nil {
		return x.Users
	}
	return ""
}

func (x *IdGen_Resources) GetSessions() string {
	if x != nil {
		return x.Sessions
	}
	return ""
}

func (x *IdGen_Resources) GetDocuments() string {
	if x != nil {
		return x.Documents
	}
	return ""
}

type Payments_Stripe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret key (sk_...). env: TORCHWOOD_PAYMENTS_STRIPE_SECRET_KEY
	SecretKey string `protobuf:"bytes,1,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// Webhook signing secret (whsec_...). env: TORCHWOOD_PAYMENTS_STRIPE_WEBHOOK_SECRET
	WebhookSecret string `protobuf:"bytes,2,opt,name=webhook_secret,json=webhookSecret,proto3" json:"webhook_secret,omitempty"`
	// REST API base URL; empty = https://api.stripe.com (tests may override).
	ApiBaseUrl    string `protobuf:"bytes,3,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payments_Stripe) Reset() {
	*x = Payments_Stripe{}
	mi := &file_config_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payments_Stripe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payments_Stripe) ProtoMessage() {}

func (x *Payments_Stripe) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payments_Stripe.ProtoReflect.Descriptor instead.
func (*Payments_Stripe) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15, 0}
}

func (x *Payments_Stripe) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *Payments_Stripe) GetWebhookSecret() string {
	if x != nil {
		return x.WebhookSecret
	}
	return ""
}

func (x *Payments_Stripe) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type Payments_WeChat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	MchId string                 `protobuf:"bytes,1,opt,name=mch_id,json=mchId,proto3" json:"mch_id,omitempty"`
	AppId string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// APIv3 密钥（32 字节，回调 AES-256-GCM 解密）。env: TORCHWOOD_PAYMENTS_WECHAT_API_V3_KEY
	ApiV3Key string `protobuf:"bytes,3,opt,name=api_v3_key,json=apiV3Key,proto3" json:"api_v3_key,omitempty"`
	// 商户 API 证书序列号。env: TORCHWOOD_PAYMENTS_WECHAT_MERCHANT_SERIAL_NO
	MerchantSerialNo string `protobuf:"bytes,4,opt,name=merchant_serial_no,json=merchantSerialNo,proto3" json:"merchant_serial_no,omitempty"`
	// 商户 API 私钥 PEM。env: TORCHWOOD_PAYMENTS_WECHAT_MERCHANT_PRIVATE_KEY
	MerchantPrivateKey string `protobuf:"bytes,5,opt,name=merchant_private_key,json=merchantPrivateKey,proto3" json:"merchant_private_key,omitempty"`
	// 微信支付平台证书 PEM（验签）。env: TORCHWOOD_PAYMENTS_WECHAT_PLATFORM_CERT
	PlatformCert string `protobuf:"bytes,6,opt,name=platform_cert,json=platformCert,proto3" json:"platform_cert,omitempty"`
	// 可选：覆盖回调 URL；空则用 server.http.public_url + /v1/payments/callbacks/wechat。
	NotifyUrl string `protobuf:"bytes,7,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	// REST API base URL; empty = https://api.mch.weixin.qq.com（tests may override）。
	ApiBaseUrl    string `protobuf:"bytes,8,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payments_WeChat) Reset() {
	*x = Payments_WeChat{}
	mi := &file_config_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payments_WeChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payments_WeChat) ProtoMessage() {}

func (x *Payments_WeChat) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payments_WeChat.ProtoReflect.Descriptor instead.
func (*Payments_WeChat) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15, 1}
}

func (x *Payments_WeChat) GetMchId() string {
	if x != nil {
		return x.MchId
	}
	return ""
}

func (x *Payments_WeChat) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Payments_WeChat) GetApiV3Key() string {
	if x != nil {
		return x.ApiV3Key
	}
	return ""
}

func (x *Payments_WeChat) GetMerchantSerialNo() string {
	if x != nil {
		return x.MerchantSerialNo
	}
	return ""
}

func (x *Payments_WeChat) GetMerchantPrivateKey() string {
	if x != nil {
		return x.MerchantPrivateKey
	}
	return ""
}

func (x *Payments_WeChat) GetPlatformCert() string {
	if x != nil {
		return x.PlatformCert
	}
	return ""
}

func (x *Payments_WeChat) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *Payments_WeChat) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

type Payments_Alipay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	AppId string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// 应用私钥 PEM。env: TORCHWOOD_PAYMENTS_ALIPAY_APP_PRIVATE_KEY
	AppPrivateKey string `protobuf:"bytes,2,opt,name=app_private_key,json=appPrivateKey,proto3" json:"app_private_key,omitempty"`
	// 支付宝公钥 PEM。env: TORCHWOOD_PAYMENTS_ALIPAY_ALIPAY_PUBLIC_KEY
	AlipayPublicKey string `protobuf:"bytes,3,opt,name=alipay_public_key,json=alipayPublicKey,proto3" json:"alipay_public_key,omitempty"`
	// 可选：覆盖回调 URL；空则用 server.http.public_url + /v1/payments/callbacks/alipay。
	NotifyUrl string `protobuf:"bytes,4,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	// 开放平台网关; empty = https://openapi.alipay.com/gateway.do。
	GatewayUrl    string `protobuf:"bytes,5,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payments_Alipay) Reset() {
	*x = Payments_Alipay{}
	mi := &file_config_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payments_Alipay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payments_Alipay) ProtoMessage() {}

func (x *Payments_Alipay) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payments_Alipay.ProtoReflect.Descriptor instead.
func (*Payments_Alipay) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15, 2}
}

func (x *Payments_Alipay) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Payments_Alipay) GetAppPrivateKey() string {
	if x != nil {
		return x.AppPrivateKey
	}
	return ""
}

func (x *Payments_Alipay) GetAlipayPublicKey() string {
	if x != nil {
		return x.AlipayPublicKey
	}
	return ""
}

func (x *Payments_Alipay) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *Payments_Alipay) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

type Payments_IosIap struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BundleId string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	// verifyReceipt shared secret。env: TORCHWOOD_PAYMENTS_IOS_IAP_SHARED_SECRET
	SharedSecret string `protobuf:"bytes,2,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	// App Store Connect API（StoreKit 2 / ASN 备用）issuer。
	IssuerId string `protobuf:"bytes,3,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	KeyId    string `protobuf:"bytes,4,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// App Store Connect API .p8 PEM。env: TORCHWOOD_PAYMENTS_IOS_IAP_PRIVATE_KEY
	PrivateKey string `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Apple Root CA PEM（可多张）；空则使用内置 Apple Root CA - G3。
	// env: TORCHWOOD_PAYMENTS_IOS_IAP_APPLE_ROOT_CERT
	AppleRootCert string `protobuf:"bytes,6,opt,name=apple_root_cert,json=appleRootCert,proto3" json:"apple_root_cert,omitempty"`
	// verifyReceipt 生产地址；空 = https://buy.itunes.apple.com/verifyReceipt。
	VerifyReceiptUrl string `protobuf:"bytes,7,opt,name=verify_receipt_url,json=verifyReceiptUrl,proto3" json:"verify_receipt_url,omitempty"`
	// verifyReceipt 沙盒地址；空 = https://sandbox.itunes.apple.com/verifyReceipt。
	SandboxVerifyUrl string `protobuf:"bytes,8,opt,name=sandbox_verify_url,json=sandboxVerifyUrl,proto3" json:"sandbox_verify_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Payments_IosIap) Reset() {
	*x = Payments_IosIap{}
	mi := &file_config_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payments_IosIap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payments_IosIap) ProtoMessage() {}

func (x *Payments_IosIap) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payments_IosIap.ProtoReflect.Descriptor instead.
func (*Payments_IosIap) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{15, 3}
}

func (x *Payments_IosIap) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *Payments_IosIap) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *Payments_IosIap) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *Payments_IosIap) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Payments_IosIap) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Payments_IosIap) GetAppleRootCert() string {
	if x != nil {
		return x.AppleRootCert
	}
	return ""
}

func (x *Payments_IosIap) GetVerifyReceiptUrl() string {
	if x != nil {
		return x.VerifyReceiptUrl
	}
	return ""
}

func (x *Payments_IosIap) GetSandboxVerifyUrl() string {
	if x != nil {
		return x.SandboxVerifyUrl
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x14torchwood.api.config\"\x92\x04\n" +
	"\tAppConfig\x124\n" +
	"\x06server\x18\x01 \x01(\v2\x1c.torchwood.api.config.ServerR\x06server\x12:\n" +
	"\bsecurity\x18\x02 \x01(\v2\x1e.torchwood.api.config.SecurityR\bsecurity\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.torchwood.api.config.DataR\x04data\x127\n" +
	"\astorage\x18\x04 \x01(\v2\x1d.torchwood.api.config.StorageR\astorage\x12=\n" +
	"\tfunctions\x18\x05 \x01(\v2\x1f.torchwood.api.config.FunctionsR\tfunctions\x12=\n" +
	"\ttelemetry\x18\x06 \x01(\v2\x1f.torchwood.api.config.TelemetryR\ttelemetry\x12=\n" +
	"\tmessaging\x18\a \x01(\v2\x1f.torchwood.api.config.MessagingR\tmessaging\x121\n" +
	"\x05idgen\x18\b \x01(\v2\x1b.torchwood.api.config.IdGenR\x05idgen\x12:\n" +
	"\bpayments\x18\t \x01(\v2\x1e.torchwood.api.config.PaymentsR\bpayments\"\x9e\x01\n" +
	"\x06Server\x12.\n" +
	"\x04grpc\x18\x01 \x01(\v2\x1a.torchwood.api.config.GRPCR\x04grpc\x12.\n" +
	"\x04http\x18\x02 \x01(\v2\x1a.torchwood.api.config.HttpR\x04http\x124\n" +
	"\ametrics\x18\x03 \x01(\v2\x1a.torchwood.api.config.HttpR\ametrics\"4\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"\xed\x02\n" +
	"\x04Http\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x123\n" +
	"\x04cors\x18\x03 \x01(\v2\x1f.torchwood.api.config.Http.CorsR\x04cors\x12\x1d\n" +
	"\n" +
	"public_url\x18\x04 \x01(\tR\tpublicUrl\x1a\xe2\x01\n" +
	"\x04Cors\x12#\n" +
	"\rallow_origins\x18\x01 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x02 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x03 \x03(\tR\fallowHeaders\x12%\n" +
	"\x0eexpose_headers\x18\x04 \x03(\tR\rexposeHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\"\xfc\n" +
	"\n" +
	"\bSecurity\x124\n" +
	"\x03jwt\x18\x01 \x01(\v2\".torchwood.api.config.Security.JwtR\x03jwt\x12>\n" +
	"\aapi_key\x18\x02 \x01(\v2%.torchwood.api.config.Security.ApiKeyR\x06apiKey\x12'\n" +
	"\x0ftrusted_proxies\x18\x03 \x03(\tR\x0etrustedProxies\x12\x1f\n" +
	"\vsetup_token\x18\x04 \x01(\tR\n" +
	"setupToken\x12C\n" +
	"\bsessions\x18\x05 \x01(\v2'.torchwood.api.config.Security.SessionsR\bsessions\x12G\n" +
	"\n" +
	"rate_limit\x18\x06 \x01(\v2(.torchwood.api.config.Security.RateLimitR\trateLimit\x12%\n" +
	"\x0eencryption_key\x18\a \x01(\tR\rencryptionKey\x12S\n" +
	"\x0elogin_throttle\x18\b \x01(\v2,.torchwood.api.config.Security.LoginThrottleR\rloginThrottle\x1a]\n" +
	"\x03Jwt\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1d\n" +
	"\n" +
	"access_ttl\x18\x02 \x01(\tR\taccessTtl\x12\x1f\n" +
	"\vrefresh_ttl\x18\x03 \x01(\tR\n" +
	"refreshTtl\x1a \n" +
	"\x06ApiKey\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x1a,\n" +
	"\bSessions\x12 \n" +
	"\fmax_per_user\x18\x01 \x01(\x05R\n" +
	"maxPerUser\x1a\xaf\x03\n" +
	"\tRateLimit\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x12B\n" +
	"\x02ip\x18\x02 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x02ip\x12F\n" +
	"\x04user\x18\x03 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x04user\x12K\n" +
	"\aapi_key\x18\x04 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x06apiKey\x12c\n" +
	"\x13functions_execution\x18\x05 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x12functionsExecution\x1a9\n" +
	"\tDimension\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06window\x18\x02 \x01(\tR\x06windowB\n" +
	"\n" +
	"\b_enabled\x1a\xc4\x02\n" +
	"\rLoginThrottle\x12H\n" +
	"\x05email\x18\x01 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x05email\x12B\n" +
	"\x02ip\x18\x02 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\x02ip\x12O\n" +
	"\tsignup_ip\x18\x03 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\bsignupIp\x12T\n" +
	"\fapi_key_auth\x18\x04 \x01(\v22.torchwood.api.config.Security.RateLimit.DimensionR\n" +
	"apiKeyAuth\"\xd1\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05debug\x18\x02 \x01(\bR\x05debug\x127\n" +
	"\x04pool\x18\x03 \x01(\v2#.torchwood.api.config.Database.PoolR\x04pool\x120\n" +
	"\x14slow_query_threshold\x18\x04 \x01(\tR\x12slowQueryThreshold\x1a\xab\x01\n" +
	"\x04Pool\x12$\n" +
	"\x0emax_idle_conns\x18\x01 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05R\fmaxOpenConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x03 \x01(\tR\x0fconnMaxLifetime\x12+\n" +
	"\x12conn_max_idle_time\x18\x04 \x01(\tR\x0fconnMaxIdleTime\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"u\n" +
	"\x04Data\x12:\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1e.torchwood.api.config.DatabaseR\bdatabase\x121\n" +
	"\x05redis\x18\x02 \x01(\v2\x1b.torchwood.api.config.RedisR\x05redis\"\xeb\x02\n" +
	"\aStorage\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x120\n" +
	"\x02s3\x18\x02 \x01(\v2 .torchwood.api.config.Storage.S3R\x02s3\x129\n" +
	"\x05local\x18\x03 \x01(\v2#.torchwood.api.config.Storage.LocalR\x05local\x1a\xb9\x01\n" +
	"\x02S3\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\x12\"\n" +
	"\raccess_key_id\x18\x04 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x05 \x01(\tR\x0fsecretAccessKey\x12\x17\n" +
	"\ause_ssl\x18\x06 \x01(\bR\x06useSsl\x1a\x1b\n" +
	"\x05Local\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x93\b\n" +
	"\tFunctions\x12\x1a\n" +
	"\bexecutor\x18\x01 \x01(\tR\bexecutor\x12>\n" +
	"\x06docker\x18\x02 \x01(\v2&.torchwood.api.config.Functions.DockerR\x06docker\x12G\n" +
	"\texecution\x18\x03 \x01(\v2).torchwood.api.config.Functions.ExecutionR\texecution\x12J\n" +
	"\n" +
	"dispatcher\x18\x04 \x01(\v2*.torchwood.api.config.Functions.DispatcherR\n" +
	"dispatcher\x12A\n" +
	"\atrigger\x18\x05 \x01(\v2'.torchwood.api.config.Functions.TriggerR\atrigger\x12Q\n" +
	"\rclient_invoke\x18\x06 \x01(\v2,.torchwood.api.config.Functions.ClientInvokeR\fclientInvoke\x1aR\n" +
	"\x06Docker\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12\x1a\n" +
	"\bregistry\x18\x03 \x01(\tR\bregistry\x1a-\n" +
	"\tExecution\x12 \n" +
	"\fapi_base_url\x18\x01 \x01(\tR\n" +
	"apiBaseUrl\x1a\xd3\x02\n" +
	"\n" +
	"Dispatcher\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fshared_token\x18\x02 \x01(\tR\vsharedToken\x124\n" +
	"\x16max_resident_instances\x18\x03 \x01(\x05R\x14maxResidentInstances\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x05R\n" +
	"queueDepth\x12,\n" +
	"\x12queue_head_timeout\x18\x05 \x01(\tR\x10queueHeadTimeout\x12!\n" +
	"\fboot_timeout\x18\x06 \x01(\tR\vbootTimeout\x12\x12\n" +
	"\x04addr\x18\a \x01(\tR\x04addr\x12-\n" +
	"\x12callback_container\x18\b \x01(\tR\x11callbackContainer\x12%\n" +
	"\x0etimeout_budget\x18\t \x01(\rR\rtimeoutBudget\x1a6\n" +
	"\aTrigger\x12+\n" +
	"\x12http_ip_per_minute\x18\x01 \x01(\x05R\x0fhttpIpPerMinute\x1an\n" +
	"\fClientInvoke\x120\n" +
	"\x14per_user_concurrency\x18\x01 \x01(\x05R\x12perUserConcurrency\x12,\n" +
	"\x12queue_head_timeout\x18\x02 \x01(\tR\x10queueHeadTimeout\"m\n" +
	"\tTelemetry\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12#\n" +
	"\rotlp_endpoint\x18\x02 \x01(\tR\fotlpEndpoint\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"\xc8\x02\n" +
	"\tMessaging\x128\n" +
	"\x04smtp\x18\x01 \x01(\v2$.torchwood.api.config.Messaging.SMTPR\x04smtp\x12\x1e\n" +
	"\vdev_log_otp\x18\x02 \x01(\bR\tdevLogOtp\x12+\n" +
	"\x03sms\x18\x03 \x01(\v2\x19.torchwood.api.config.SMSR\x03sms\x12\x1e\n" +
	"\vdev_log_sms\x18\x04 \x01(\bR\tdevLogSms\x1a\x93\x01\n" +
	"\x04SMTP\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x17\n" +
	"\ause_tls\x18\x06 \x01(\bR\x06useTls\"W\n" +
	"\x03SMS\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x124\n" +
	"\x06twilio\x18\x02 \x01(\v2\x1c.torchwood.api.config.TwilioR\x06twilio\"\\\n" +
	"\x06Twilio\x12\x1f\n" +
	"\vaccount_sid\x18\x01 \x01(\tR\n" +
	"accountSid\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"\xfb\x04\n" +
	"\x05IdGen\x12)\n" +
	"\x10default_strategy\x18\x01 \x01(\tR\x0fdefaultStrategy\x12:\n" +
	"\x06random\x18\x02 \x01(\v2\".torchwood.api.config.IdGen.RandomR\x06random\x12C\n" +
	"\tsnowflake\x18\x03 \x01(\v2%.torchwood.api.config.IdGen.SnowflakeR\tsnowflake\x12@\n" +
	"\bsequence\x18\x04 \x01(\v2$.torchwood.api.config.IdGen.SequenceR\bsequence\x12C\n" +
	"\tresources\x18\x05 \x01(\v2%.torchwood.api.config.IdGen.ResourcesR\tresources\x1a\x85\x01\n" +
	"\x06Random\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\x12\x18\n" +
	"\acharset\x18\x02 \x01(\tR\acharset\x12(\n" +
	"\x10redis_key_prefix\x18\x03 \x01(\tR\x0eredisKeyPrefix\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x1a$\n" +
	"\tSnowflake\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x1a4\n" +
	"\bSequence\x12(\n" +
	"\x10redis_key_prefix\x18\x01 \x01(\tR\x0eredisKeyPrefix\x1a[\n" +
	"\tResources\x12\x14\n" +
	"\x05users\x18\x01 \x01(\tR\x05users\x12\x1a\n" +
	"\bsessions\x18\x02 \x01(\tR\bsessions\x12\x1c\n" +
	"\tdocuments\x18\x03 \x01(\tR\tdocuments\"\xf2\b\n" +
	"\bPayments\x12=\n" +
	"\x06stripe\x18\x01 \x01(\v2%.torchwood.api.config.Payments.StripeR\x06stripe\x12=\n" +
	"\x06wechat\x18\x02 \x01(\v2%.torchwood.api.config.Payments.WeChatR\x06wechat\x12=\n" +
	"\x06alipay\x18\x03 \x01(\v2%.torchwood.api.config.Payments.AlipayR\x06alipay\x12>\n" +
	"\aios_iap\x18\x04 \x01(\v2%.torchwood.api.config.Payments.IosIapR\x06iosIap\x1ap\n" +
	"\x06Stripe\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x01 \x01(\tR\tsecretKey\x12%\n" +
	"\x0ewebhook_secret\x18\x02 \x01(\tR\rwebhookSecret\x12 \n" +
	"\fapi_base_url\x18\x03 \x01(\tR\n" +
	"apiBaseUrl\x1a\x9a\x02\n" +
	"\x06WeChat\x12\x15\n" +
	"\x06mch_id\x18\x01 \x01(\tR\x05mchId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1c\n" +
	"\n" +
	"api_v3_key\x18\x03 \x01(\tR\bapiV3Key\x12,\n" +
	"\x12merchant_serial_no\x18\x04 \x01(\tR\x10merchantSerialNo\x120\n" +
	"\x14merchant_private_key\x18\x05 \x01(\tR\x12merchantPrivateKey\x12#\n" +
	"\rplatform_cert\x18\x06 \x01(\tR\fplatformCert\x12\x1d\n" +
	"\n" +
	"notify_url\x18\a \x01(\tR\tnotifyUrl\x12 \n" +
	"\fapi_base_url\x18\b \x01(\tR\n" +
	"apiBaseUrl\x1a\xb3\x01\n" +
	"\x06Alipay\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12&\n" +
	"\x0fapp_private_key\x18\x02 \x01(\tR\rappPrivateKey\x12*\n" +
	"\x11alipay_public_key\x18\x03 \x01(\tR\x0falipayPublicKey\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x04 \x01(\tR\tnotifyUrl\x12\x1f\n" +
	"\vgateway_url\x18\x05 \x01(\tR\n" +
	"gatewayUrl\x1a\xa3\x02\n" +
	"\x06IosIap\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12#\n" +
	"\rshared_secret\x18\x02 \x01(\tR\fsharedSecret\x12\x1b\n" +
	"\tissuer_id\x18\x03 \x01(\tR\bissuerId\x12\x15\n" +
	"\x06key_id\x18\x04 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vprivate_key\x18\x05 \x01(\tR\n" +
	"privateKey\x12&\n" +
	"\x0fapple_root_cert\x18\x06 \x01(\tR\rappleRootCert\x12,\n" +
	"\x12verify_receipt_url\x18\a \x01(\tR\x10verifyReceiptUrl\x12,\n" +
	"\x12sandbox_verify_url\x18\b \x01(\tR\x10sandboxVerifyUrlB9Z7github.com/torchwoodcloud/torchwood/internal/pkg/configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_config_proto_goTypes = []any{
	(*AppConfig)(nil),                    // 0: torchwood.api.config.AppConfig
	(*Server)(nil),                       // 1: torchwood.api.config.Server
	(*GRPC)(nil),                         // 2: torchwood.api.config.GRPC
	(*Http)(nil),                         // 3: torchwood.api.config.Http
	(*Security)(nil),                     // 4: torchwood.api.config.Security
	(*Database)(nil),                     // 5: torchwood.api.config.Database
	(*Redis)(nil),                        // 6: torchwood.api.config.Redis
	(*Data)(nil),                         // 7: torchwood.api.config.Data
	(*Storage)(nil),                      // 8: torchwood.api.config.Storage
	(*Functions)(nil),                    // 9: torchwood.api.config.Functions
	(*Telemetry)(nil),                    // 10: torchwood.api.config.Telemetry
	(*Messaging)(nil),                    // 11: torchwood.api.config.Messaging
	(*SMS)(nil),                          // 12: torchwood.api.config.SMS
	(*Twilio)(nil),                       // 13: torchwood.api.config.Twilio
	(*IdGen)(nil),                        // 14: torchwood.api.config.IdGen
	(*Payments)(nil),                     // 15: torchwood.api.config.Payments
	(*Http_Cors)(nil),                    // 16: torchwood.api.config.Http.Cors
	(*Security_Jwt)(nil),                 // 17: torchwood.api.config.Security.Jwt
	(*Security_ApiKey)(nil),              // 18: torchwood.api.config.Security.ApiKey
	(*Security_Sessions)(nil),            // 19: torchwood.api.config.Security.Sessions
	(*Security_RateLimit)(nil),           // 20: torchwood.api.config.Security.RateLimit
	(*Security_LoginThrottle)(nil),       // 21: torchwood.api.config.Security.LoginThrottle
	(*Security_RateLimit_Dimension)(nil), // 22: torchwood.api.config.Security.RateLimit.Dimension
	(*Database_Pool)(nil),                // 23: torchwood.api.config.Database.Pool
	(*Storage_S3)(nil),                   // 24: torchwood.api.config.Storage.S3
	(*Storage_Local)(nil),                // 25: torchwood.api.config.Storage.Local
	(*Functions_Docker)(nil),             // 26: torchwood.api.config.Functions.Docker
	(*Functions_Execution)(nil),          // 27: torchwood.api.config.Functions.Execution
	(*Functions_Dispatcher)(nil),         // 28: torchwood.api.config.Functions.Dispatcher
	(*Functions_Trigger)(nil),            // 29: torchwood.api.config.Functions.Trigger
	(*Functions_ClientInvoke)(nil),       // 30: torchwood.api.config.Functions.ClientInvoke
	(*Messaging_SMTP)(nil),               // 31: torchwood.api.config.Messaging.SMTP
	(*IdGen_Random)(nil),                 // 32: torchwood.api.config.IdGen.Random
	(*IdGen_Snowflake)(nil),              // 33: torchwood.api.config.IdGen.Snowflake
	(*IdGen_Sequence)(nil),               // 34: torchwood.api.config.IdGen.Sequence
	(*IdGen_Resources)(nil),              // 35: torchwood.api.config.IdGen.Resources
	(*Payments_Stripe)(nil),              // 36: torchwood.api.config.Payments.Stripe
	(*Payments_WeChat)(nil),              // 37: torchwood.api.config.Payments.WeChat
	(*Payments_Alipay)(nil),              // 38: torchwood.api.config.Payments.Alipay
	(*Payments_IosIap)(nil),              // 39: torchwood.api.config.Payments.IosIap
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: torchwood.api.config.AppConfig.server:type_name -> torchwood.api.config.Server
	4,  // 1: torchwood.api.config.AppConfig.security:type_name -> torchwood.api.config.Security
	7,  // 2: torchwood.api.config.AppConfig.data:type_name -> torchwood.api.config.Data
	8,  // 3: torchwood.api.config.AppConfig.storage:type_name -> torchwood.api.config.Storage
	9,  // 4: torchwood.api.config.AppConfig.functions:type_name -> torchwood.api.config.Functions
	10, // 5: torchwood.api.config.AppConfig.telemetry:type_name -> torchwood.api.config.Telemetry
	11, // 6: torchwood.api.config.AppConfig.messaging:type_name -> torchwood.api.config.Messaging
	14, // 7: torchwood.api.config.AppConfig.idgen:type_name -> torchwood.api.config.IdGen
	15, // 8: torchwood.api.config.AppConfig.payments:type_name -> torchwood.api.config.Payments
	2,  // 9: torchwood.api.config.Server.grpc:type_name -> torchwood.api.config.GRPC
	3,  // 10: torchwood.api.config.Server.http:type_name -> torchwood.api.config.Http
	3,  // 11: torchwood.api.config.Server.metrics:type_name -> torchwood.api.config.Http
	16, // 12: torchwood.api.config.Http.cors:type_name -> torchwood.api.config.Http.Cors
	17, // 13: torchwood.api.config.Security.jwt:type_name -> torchwood.api.config.Security.Jwt
	18, // 14: torchwood.api.config.Security.api_key:type_name -> torchwood.api.config.Security.ApiKey
	19, // 15: torchwood.api.config.Security.sessions:type_name -> torchwood.api.config.Security.Sessions
	20, // 16: torchwood.api.config.Security.rate_limit:type_name -> torchwood.api.config.Security.RateLimit
	21, // 17: torchwood.api.config.Security.login_throttle:type_name -> torchwood.api.config.Security.LoginThrottle
	23, // 18: torchwood.api.config.Database.pool:type_name -> torchwood.api.config.Database.Pool
	5,  // 19: torchwood.api.config.Data.database:type_name -> torchwood.api.config.Database
	6,  // 20: torchwood.api.config.Data.redis:type_name -> torchwood.api.config.Redis
	24, // 21: torchwood.api.config.Storage.s3:type_name -> torchwood.api.config.Storage.S3
	25, // 22: torchwood.api.config.Storage.local:type_name -> torchwood.api.config.Storage.Local
	26, // 23: torchwood.api.config.Functions.docker:type_name -> torchwood.api.config.Functions.Docker
	27, // 24: torchwood.api.config.Functions.execution:type_name -> torchwood.api.config.Functions.Execution
	28, // 25: torchwood.api.config.Functions.dispatcher:type_name -> torchwood.api.config.Functions.Dispatcher
	29, // 26: torchwood.api.config.Functions.trigger:type_name -> torchwood.api.config.Functions.Trigger
	30, // 27: torchwood.api.config.Functions.client_invoke:type_name -> torchwood.api.config.Functions.ClientInvoke
	31, // 28: torchwood.api.config.Messaging.smtp:type_name -> torchwood.api.config.Messaging.SMTP
	12, // 29: torchwood.api.config.Messaging.sms:type_name -> torchwood.api.config.SMS
	13, // 30: torchwood.api.config.SMS.twilio:type_name -> torchwood.api.config.Twilio
	32, // 31: torchwood.api.config.IdGen.random:type_name -> torchwood.api.config.IdGen.Random
	33, // 32: torchwood.api.config.IdGen.snowflake:type_name -> torchwood.api.config.IdGen.Snowflake
	34, // 33: torchwood.api.config.IdGen.sequence:type_name -> torchwood.api.config.IdGen.Sequence
	35, // 34: torchwood.api.config.IdGen.resources:type_name -> torchwood.api.config.IdGen.Resources
	36, // 35: torchwood.api.config.Payments.stripe:type_name -> torchwood.api.config.Payments.Stripe
	37, // 36: torchwood.api.config.Payments.wechat:type_name -> torchwood.api.config.Payments.WeChat
	38, // 37: torchwood.api.config.Payments.alipay:type_name -> torchwood.api.config.Payments.Alipay
	39, // 38: torchwood.api.config.Payments.ios_iap:type_name -> torchwood.api.config.Payments.IosIap
	22, // 39: torchwood.api.config.Security.RateLimit.ip:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 40: torchwood.api.config.Security.RateLimit.user:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 41: torchwood.api.config.Security.RateLimit.api_key:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 42: torchwood.api.config.Security.RateLimit.functions_execution:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 43: torchwood.api.config.Security.LoginThrottle.email:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 44: torchwood.api.config.Security.LoginThrottle.ip:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 45: torchwood.api.config.Security.LoginThrottle.signup_ip:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	22, // 46: torchwood.api.config.Security.LoginThrottle.api_key_auth:type_name -> torchwood.api.config.Security.RateLimit.Dimension
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
