// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fleetly/server/v1/builds.proto

package serverv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildFromUploadRequest 是上传构建的流帧（oneof）：首帧 metadata，后续帧
// chunk（tar 分片）。任何其他形态（首帧无 metadata、metadata 重复、帧既无
// metadata 又无 chunk、超单帧上限）一律 E_BUILD_UPLOAD_INVALID 拒绝。
type BuildFromUploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BuildFromUploadRequest_Metadata
	//	*BuildFromUploadRequest_Chunk
	Payload       isBuildFromUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFromUploadRequest) Reset() {
	*x = BuildFromUploadRequest{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFromUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFromUploadRequest) ProtoMessage() {}

func (x *BuildFromUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFromUploadRequest.ProtoReflect.Descriptor instead.
func (*BuildFromUploadRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{0}
}

func (x *BuildFromUploadRequest) GetPayload() isBuildFromUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BuildFromUploadRequest) GetMetadata() *BuildFromUploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*BuildFromUploadRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *BuildFromUploadRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*BuildFromUploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isBuildFromUploadRequest_Payload interface {
	isBuildFromUploadRequest_Payload()
}

type BuildFromUploadRequest_Metadata struct {
	// 首帧且仅首帧携带。
	Metadata *BuildFromUploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type BuildFromUploadRequest_Chunk struct {
	// 上下文 tar 分片（单帧 ≤ 1MiB；总字节 ≤ 平台上限——超限
	// E_BUILD_UPLOAD_TOO_LARGE）。
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*BuildFromUploadRequest_Metadata) isBuildFromUploadRequest_Payload() {}

func (*BuildFromUploadRequest_Chunk) isBuildFromUploadRequest_Payload() {}

// BuildFromUploadMetadata 是上传构建的请求头（传输面元数据）。
//
// 信任级红线（IMPL-T2-2）：与 git 构建**同信任级**——本消息不含 target/
// build-args/secrets/platform 等任何额外构建参数（无特赦亦无歧视）；解包
// 后的 Dockerfile 走与 git 构建逐字相同的 dockerfile.v0 前端。
type BuildFromUploadMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 镜像仓库组件名（平台 registry 路径 <host>/apps/<name>；服务端转小写，
	// 首末位须为字母数字，可含 . _ -，≤100——tag 以 <name>-<buildid> 派生）。
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Dockerfile 入口（相对上下文根的仓内路径；缺省 Dockerfile）。服务端
	// 校验：clean 相对路径、不越出上下文根、解析后为常规文件。
	Dockerfile    string `protobuf:"bytes,2,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFromUploadMetadata) Reset() {
	*x = BuildFromUploadMetadata{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFromUploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFromUploadMetadata) ProtoMessage() {}

func (x *BuildFromUploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFromUploadMetadata.ProtoReflect.Descriptor instead.
func (*BuildFromUploadMetadata) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{1}
}

func (x *BuildFromUploadMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildFromUploadMetadata) GetDockerfile() string {
	if x != nil {
		return x.Dockerfile
	}
	return ""
}

// BuildFromUploadResponse 返回终态构建行（succeeded；失败经错误信封点名
// error_code 与 build id）。image_ref/image_digest 是 digest 钉定引用——
// registry 模式 `<host>/apps/<name>@sha256:<manifest digest>`；本地模式
// `fleetly-local/<name>:<tag>` + 本机不可变 ID。
type BuildFromUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *BuildView             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFromUploadResponse) Reset() {
	*x = BuildFromUploadResponse{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFromUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFromUploadResponse) ProtoMessage() {}

func (x *BuildFromUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFromUploadResponse.ProtoReflect.Descriptor instead.
func (*BuildFromUploadResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{2}
}

func (x *BuildFromUploadResponse) GetBuild() *BuildView {
	if x != nil {
		return x.Build
	}
	return nil
}

type TriggerBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// compose 文件内容字节（JSON/YAML 原文；应用名取自 compose name——请求
	// 无 app 字段，单源无错位面（A1 注记；若后续加 app 字段须与 Deploy 同款
	// 一致性校验）；服务端解析受控子集——compose 违约不动底座、不入队）。
	Compose []byte `protobuf:"bytes,1,opt,name=compose,proto3" json:"compose,omitempty"`
	// 只构建该 compose 服务；空 = 全部 build 模式服务。
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// 构建上下文解析基准目录（context 相对路径的宿主基准；空 = 服务端临时
	// 目录）。v0.1 单机同宿主语义，见 service 注释（H14：admin scope，且
	// context 解析后不得越出该基准目录）。
	BaseDir string `protobuf:"bytes,3,opt,name=base_dir,json=baseDir,proto3" json:"base_dir,omitempty"`
	// 目标项目（v0.3 W2-S3 归属管道）：仅在该 app 尚不存在、构建自动建行时
	// 消费——解析与缺省语义同 DeployRequest.project（D-W0-9；机具令牌必须
	// 显式）。app 行已在时沿用行上归属，本字段忽略。
	Project       string `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildRequest) Reset() {
	*x = TriggerBuildRequest{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildRequest) ProtoMessage() {}

func (x *TriggerBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerBuildRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerBuildRequest) GetCompose() []byte {
	if x != nil {
		return x.Compose
	}
	return nil
}

func (x *TriggerBuildRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TriggerBuildRequest) GetBaseDir() string {
	if x != nil {
		return x.BaseDir
	}
	return ""
}

func (x *TriggerBuildRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type TriggerBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 应用名（compose name；应用不存在时自动创建——与 deploy 同语义）。
	App string `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 入队的构建行（status 恒 "queued"）。
	Builds []*BuildView `protobuf:"bytes,2,rep,name=builds,proto3" json:"builds,omitempty"`
	// compose 校验期非阻断标注（与 Deploy 同口径透传）。
	Warnings []*ComposeWarning `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	// 直通服务（仅 image 无 build——不建行不构建，附镜像引用）。
	Passthrough   []*PassthroughService `protobuf:"bytes,4,rep,name=passthrough,proto3" json:"passthrough,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildResponse) Reset() {
	*x = TriggerBuildResponse{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildResponse) ProtoMessage() {}

func (x *TriggerBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerBuildResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerBuildResponse) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *TriggerBuildResponse) GetBuilds() []*BuildView {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *TriggerBuildResponse) GetWarnings() []*ComposeWarning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *TriggerBuildResponse) GetPassthrough() []*PassthroughService {
	if x != nil {
		return x.Passthrough
	}
	return nil
}

// PassthroughService 是镜像模式服务的直通报告（无构建行）。
type PassthroughService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassthroughService) Reset() {
	*x = PassthroughService{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassthroughService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassthroughService) ProtoMessage() {}

func (x *PassthroughService) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassthroughService.ProtoReflect.Descriptor instead.
func (*PassthroughService) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{5}
}

func (x *PassthroughService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PassthroughService) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type GetBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{6}
}

func (x *GetBuildRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *BuildView             `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildResponse) Reset() {
	*x = GetBuildResponse{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildResponse) ProtoMessage() {}

func (x *GetBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildResponse.ProtoReflect.Descriptor instead.
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{7}
}

func (x *GetBuildResponse) GetBuild() *BuildView {
	if x != nil {
		return x.Build
	}
	return nil
}

type ListBuildsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   string                 `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	// 返回上限（缺省 20，天花板 100）。
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{8}
}

func (x *ListBuildsRequest) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *ListBuildsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBuildsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Builds        []*BuildView           `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{9}
}

func (x *ListBuildsResponse) GetBuilds() []*BuildView {
	if x != nil {
		return x.Builds
	}
	return nil
}

// BuildView 是构建行的只读投影（词表与 state 层一致：queued/building/
// succeeded/failed；driver ∈ railpack/dockerfile/passthrough）。
type BuildView struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	App     string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Service string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Driver  string                 `protobuf:"bytes,4,opt,name=driver,proto3" json:"driver,omitempty"`
	Status  string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// 成功终态必非空（image_ref ↔ image_digest，D9 digest 引用）。
	ImageRef    string `protobuf:"bytes,6,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	ImageDigest string `protobuf:"bytes,7,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// 产物归档路径（railpack plan JSON / 构建日志）。
	PlanPath string `protobuf:"bytes,8,opt,name=plan_path,json=planPath,proto3" json:"plan_path,omitempty"`
	LogPath  string `protobuf:"bytes,9,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	// 失败终态的注册表错误码。
	ErrorCode     string                 `protobuf:"bytes,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildView) Reset() {
	*x = BuildView{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildView) ProtoMessage() {}

func (x *BuildView) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildView.ProtoReflect.Descriptor instead.
func (*BuildView) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{10}
}

func (x *BuildView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BuildView) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *BuildView) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *BuildView) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *BuildView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BuildView) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *BuildView) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *BuildView) GetPlanPath() string {
	if x != nil {
		return x.PlanPath
	}
	return ""
}

func (x *BuildView) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *BuildView) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BuildView) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BuildView) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

// ComposeWarning 是 compose 校验期非阻断标注的跨面投影（deploy/build 共
// 用；code = 注册表 W_ 码，无注册码提示以 kind 承载稳定标识）。
type ComposeWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeWarning) Reset() {
	*x = ComposeWarning{}
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeWarning) ProtoMessage() {}

func (x *ComposeWarning) ProtoReflect() protoreflect.Message {
	mi := &file_fleetly_server_v1_builds_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeWarning.ProtoReflect.Descriptor instead.
func (*ComposeWarning) Descriptor() ([]byte, []int) {
	return file_fleetly_server_v1_builds_proto_rawDescGZIP(), []int{11}
}

func (x *ComposeWarning) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ComposeWarning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ComposeWarning) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ComposeWarning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fleetly_server_v1_builds_proto protoreflect.FileDescriptor

const file_fleetly_server_v1_builds_proto_rawDesc = "" +
	"\n" +
	"\x1efleetly/server/v1/builds.proto\x12\x11fleetly.server.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x85\x01\n" +
	"\x16BuildFromUploadRequest\x12H\n" +
	"\bmetadata\x18\x01 \x01(\v2*.fleetly.server.v1.BuildFromUploadMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"b\n" +
	"\x17BuildFromUploadMetadata\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x12(\n" +
	"\n" +
	"dockerfile\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\n" +
	"dockerfile\"M\n" +
	"\x17BuildFromUploadResponse\x122\n" +
	"\x05build\x18\x01 \x01(\v2\x1c.fleetly.server.v1.BuildViewR\x05build\"\x90\x01\n" +
	"\x13TriggerBuildRequest\x12!\n" +
	"\acompose\x18\x01 \x01(\fB\a\xbaH\x04z\x02\x10\x01R\acompose\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x19\n" +
	"\bbase_dir\x18\x03 \x01(\tR\abaseDir\x12!\n" +
	"\aproject\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18AR\aproject\"\xe6\x01\n" +
	"\x14TriggerBuildResponse\x12\x10\n" +
	"\x03app\x18\x01 \x01(\tR\x03app\x124\n" +
	"\x06builds\x18\x02 \x03(\v2\x1c.fleetly.server.v1.BuildViewR\x06builds\x12=\n" +
	"\bwarnings\x18\x03 \x03(\v2!.fleetly.server.v1.ComposeWarningR\bwarnings\x12G\n" +
	"\vpassthrough\x18\x04 \x03(\v2%.fleetly.server.v1.PassthroughServiceR\vpassthrough\"D\n" +
	"\x12PassthroughService\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"*\n" +
	"\x0fGetBuildRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"F\n" +
	"\x10GetBuildResponse\x122\n" +
	"\x05build\x18\x01 \x01(\v2\x1c.fleetly.server.v1.BuildViewR\x05build\"O\n" +
	"\x11ListBuildsRequest\x12\x19\n" +
	"\x03app\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03app\x12\x1f\n" +
	"\x05limit\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\x05limit\"J\n" +
	"\x12ListBuildsResponse\x124\n" +
	"\x06builds\x18\x01 \x03(\v2\x1c.fleetly.server.v1.BuildViewR\x06builds\"\x86\x03\n" +
	"\tBuildView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x16\n" +
	"\x06driver\x18\x04 \x01(\tR\x06driver\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\timage_ref\x18\x06 \x01(\tR\bimageRef\x12!\n" +
	"\fimage_digest\x18\a \x01(\tR\vimageDigest\x12\x1b\n" +
	"\tplan_path\x18\b \x01(\tR\bplanPath\x12\x19\n" +
	"\blog_path\x18\t \x01(\tR\alogPath\x12\x1d\n" +
	"\n" +
	"error_code\x18\n" +
	" \x01(\tR\terrorCode\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"l\n" +
	"\x0eComposeWarning\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xdd\x03\n" +
	"\rBuildsService\x12v\n" +
	"\fTriggerBuild\x12&.fleetly.server.v1.TriggerBuildRequest\x1a'.fleetly.server.v1.TriggerBuildResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/builds\x12l\n" +
	"\x0fBuildFromUpload\x12).fleetly.server.v1.BuildFromUploadRequest\x1a*.fleetly.server.v1.BuildFromUploadResponse\"\x00(\x01\x12l\n" +
	"\bGetBuild\x12\".fleetly.server.v1.GetBuildRequest\x1a#.fleetly.server.v1.GetBuildResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/builds/{id}\x12x\n" +
	"\n" +
	"ListBuilds\x12$.fleetly.server.v1.ListBuildsRequest\x1a%.fleetly.server.v1.ListBuildsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/apps/{app}/buildsB\x98\x01\x92ARRP\n" +
	"\adefault\x12E\n" +
	"\x1dAn unexpected error response.\x12$\n" +
	"\"\x1a .fleetly.shared.v1.ErrorResponseZAgithub.com/fleetlyrun/fleetly/genproto/fleetly/server/v1;serverv1b\x06proto3"

var (
	file_fleetly_server_v1_builds_proto_rawDescOnce sync.Once
	file_fleetly_server_v1_builds_proto_rawDescData []byte
)

func file_fleetly_server_v1_builds_proto_rawDescGZIP() []byte {
	file_fleetly_server_v1_builds_proto_rawDescOnce.Do(func() {
		file_fleetly_server_v1_builds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_builds_proto_rawDesc), len(file_fleetly_server_v1_builds_proto_rawDesc)))
	})
	return file_fleetly_server_v1_builds_proto_rawDescData
}

var file_fleetly_server_v1_builds_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fleetly_server_v1_builds_proto_goTypes = []any{
	(*BuildFromUploadRequest)(nil),  // 0: fleetly.server.v1.BuildFromUploadRequest
	(*BuildFromUploadMetadata)(nil), // 1: fleetly.server.v1.BuildFromUploadMetadata
	(*BuildFromUploadResponse)(nil), // 2: fleetly.server.v1.BuildFromUploadResponse
	(*TriggerBuildRequest)(nil),     // 3: fleetly.server.v1.TriggerBuildRequest
	(*TriggerBuildResponse)(nil),    // 4: fleetly.server.v1.TriggerBuildResponse
	(*PassthroughService)(nil),      // 5: fleetly.server.v1.PassthroughService
	(*GetBuildRequest)(nil),         // 6: fleetly.server.v1.GetBuildRequest
	(*GetBuildResponse)(nil),        // 7: fleetly.server.v1.GetBuildResponse
	(*ListBuildsRequest)(nil),       // 8: fleetly.server.v1.ListBuildsRequest
	(*ListBuildsResponse)(nil),      // 9: fleetly.server.v1.ListBuildsResponse
	(*BuildView)(nil),               // 10: fleetly.server.v1.BuildView
	(*ComposeWarning)(nil),          // 11: fleetly.server.v1.ComposeWarning
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_fleetly_server_v1_builds_proto_depIdxs = []int32{
	1,  // 0: fleetly.server.v1.BuildFromUploadRequest.metadata:type_name -> fleetly.server.v1.BuildFromUploadMetadata
	10, // 1: fleetly.server.v1.BuildFromUploadResponse.build:type_name -> fleetly.server.v1.BuildView
	10, // 2: fleetly.server.v1.TriggerBuildResponse.builds:type_name -> fleetly.server.v1.BuildView
	11, // 3: fleetly.server.v1.TriggerBuildResponse.warnings:type_name -> fleetly.server.v1.ComposeWarning
	5,  // 4: fleetly.server.v1.TriggerBuildResponse.passthrough:type_name -> fleetly.server.v1.PassthroughService
	10, // 5: fleetly.server.v1.GetBuildResponse.build:type_name -> fleetly.server.v1.BuildView
	10, // 6: fleetly.server.v1.ListBuildsResponse.builds:type_name -> fleetly.server.v1.BuildView
	12, // 7: fleetly.server.v1.BuildView.started_at:type_name -> google.protobuf.Timestamp
	12, // 8: fleetly.server.v1.BuildView.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 9: fleetly.server.v1.BuildsService.TriggerBuild:input_type -> fleetly.server.v1.TriggerBuildRequest
	0,  // 10: fleetly.server.v1.BuildsService.BuildFromUpload:input_type -> fleetly.server.v1.BuildFromUploadRequest
	6,  // 11: fleetly.server.v1.BuildsService.GetBuild:input_type -> fleetly.server.v1.GetBuildRequest
	8,  // 12: fleetly.server.v1.BuildsService.ListBuilds:input_type -> fleetly.server.v1.ListBuildsRequest
	4,  // 13: fleetly.server.v1.BuildsService.TriggerBuild:output_type -> fleetly.server.v1.TriggerBuildResponse
	2,  // 14: fleetly.server.v1.BuildsService.BuildFromUpload:output_type -> fleetly.server.v1.BuildFromUploadResponse
	7,  // 15: fleetly.server.v1.BuildsService.GetBuild:output_type -> fleetly.server.v1.GetBuildResponse
	9,  // 16: fleetly.server.v1.BuildsService.ListBuilds:output_type -> fleetly.server.v1.ListBuildsResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_fleetly_server_v1_builds_proto_init() }
func file_fleetly_server_v1_builds_proto_init() {
	if File_fleetly_server_v1_builds_proto != nil {
		return
	}
	file_fleetly_server_v1_builds_proto_msgTypes[0].OneofWrappers = []any{
		(*BuildFromUploadRequest_Metadata)(nil),
		(*BuildFromUploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleetly_server_v1_builds_proto_rawDesc), len(file_fleetly_server_v1_builds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleetly_server_v1_builds_proto_goTypes,
		DependencyIndexes: file_fleetly_server_v1_builds_proto_depIdxs,
		MessageInfos:      file_fleetly_server_v1_builds_proto_msgTypes,
	}.Build()
	File_fleetly_server_v1_builds_proto = out.File
	file_fleetly_server_v1_builds_proto_goTypes = nil
	file_fleetly_server_v1_builds_proto_depIdxs = nil
}
