// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: console/v1/leaderboards.proto

package consolev1

import (
	context "context"
	v1 "github.com/torchwoodcloud/torchwood/genproto/shared/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeaderboardsService_CreateLeaderboardBoard_FullMethodName      = "/torchwood.console.v1.LeaderboardsService/CreateLeaderboardBoard"
	LeaderboardsService_ListLeaderboardBoards_FullMethodName       = "/torchwood.console.v1.LeaderboardsService/ListLeaderboardBoards"
	LeaderboardsService_GetLeaderboardBoard_FullMethodName         = "/torchwood.console.v1.LeaderboardsService/GetLeaderboardBoard"
	LeaderboardsService_UpdateLeaderboardBoard_FullMethodName      = "/torchwood.console.v1.LeaderboardsService/UpdateLeaderboardBoard"
	LeaderboardsService_DeleteLeaderboardBoard_FullMethodName      = "/torchwood.console.v1.LeaderboardsService/DeleteLeaderboardBoard"
	LeaderboardsService_ListLeaderboardBoardPeriods_FullMethodName = "/torchwood.console.v1.LeaderboardsService/ListLeaderboardBoardPeriods"
	LeaderboardsService_ListLeaderboardTop_FullMethodName          = "/torchwood.console.v1.LeaderboardsService/ListLeaderboardTop"
	LeaderboardsService_GetLeaderboardEntry_FullMethodName         = "/torchwood.console.v1.LeaderboardsService/GetLeaderboardEntry"
	LeaderboardsService_DeleteLeaderboardEntry_FullMethodName      = "/torchwood.console.v1.LeaderboardsService/DeleteLeaderboardEntry"
	LeaderboardsService_GetLeaderboardSettlement_FullMethodName    = "/torchwood.console.v1.LeaderboardsService/GetLeaderboardSettlement"
	LeaderboardsService_ListLeaderboardSettlements_FullMethodName  = "/torchwood.console.v1.LeaderboardsService/ListLeaderboardSettlements"
	LeaderboardsService_VoidLeaderboardSettlement_FullMethodName   = "/torchwood.console.v1.LeaderboardsService/VoidLeaderboardSettlement"
	LeaderboardsService_RerunLeaderboardSettlement_FullMethodName  = "/torchwood.console.v1.LeaderboardsService/RerunLeaderboardSettlement"
)

// LeaderboardsServiceClient is the client API for LeaderboardsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LeaderboardsService 是排行榜 console 面：board 配置 CRUD、期 top、按
// subject 查条目、删条目（作弊处理——只有未封榜期可删，封榜即终局）。
type LeaderboardsServiceClient interface {
	CreateLeaderboardBoard(ctx context.Context, in *CreateLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error)
	ListLeaderboardBoards(ctx context.Context, in *ListLeaderboardBoardsRequest, opts ...grpc.CallOption) (*ListLeaderboardBoardsResponse, error)
	GetLeaderboardBoard(ctx context.Context, in *GetLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error)
	UpdateLeaderboardBoard(ctx context.Context, in *UpdateLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error)
	DeleteLeaderboardBoard(ctx context.Context, in *DeleteLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.Empty, error)
	ListLeaderboardBoardPeriods(ctx context.Context, in *ListLeaderboardBoardPeriodsRequest, opts ...grpc.CallOption) (*ListLeaderboardBoardPeriodsResponse, error)
	ListLeaderboardTop(ctx context.Context, in *ListLeaderboardTopRequest, opts ...grpc.CallOption) (*v1.ListLeaderboardTopResponse, error)
	GetLeaderboardEntry(ctx context.Context, in *GetLeaderboardEntryRequest, opts ...grpc.CallOption) (*v1.LeaderboardScoreSnapshot, error)
	DeleteLeaderboardEntry(ctx context.Context, in *DeleteLeaderboardEntryRequest, opts ...grpc.CallOption) (*v1.Empty, error)
	// —— Phase 2：结榜发奖（settled 拒绝 void/rerun；作弊处理窗口 = 宽限期）——
	GetLeaderboardSettlement(ctx context.Context, in *GetLeaderboardSettlementRequest, opts ...grpc.CallOption) (*GetLeaderboardSettlementResponse, error)
	ListLeaderboardSettlements(ctx context.Context, in *ListLeaderboardSettlementsRequest, opts ...grpc.CallOption) (*ListLeaderboardSettlementsResponse, error)
	VoidLeaderboardSettlement(ctx context.Context, in *VoidLeaderboardSettlementRequest, opts ...grpc.CallOption) (*LeaderboardSettlementAck, error)
	RerunLeaderboardSettlement(ctx context.Context, in *RerunLeaderboardSettlementRequest, opts ...grpc.CallOption) (*LeaderboardSettlementAck, error)
}

type leaderboardsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardsServiceClient(cc grpc.ClientConnInterface) LeaderboardsServiceClient {
	return &leaderboardsServiceClient{cc}
}

func (c *leaderboardsServiceClient) CreateLeaderboardBoard(ctx context.Context, in *CreateLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.LeaderboardBoard)
	err := c.cc.Invoke(ctx, LeaderboardsService_CreateLeaderboardBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ListLeaderboardBoards(ctx context.Context, in *ListLeaderboardBoardsRequest, opts ...grpc.CallOption) (*ListLeaderboardBoardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaderboardBoardsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_ListLeaderboardBoards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetLeaderboardBoard(ctx context.Context, in *GetLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.LeaderboardBoard)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetLeaderboardBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) UpdateLeaderboardBoard(ctx context.Context, in *UpdateLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.LeaderboardBoard, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.LeaderboardBoard)
	err := c.cc.Invoke(ctx, LeaderboardsService_UpdateLeaderboardBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) DeleteLeaderboardBoard(ctx context.Context, in *DeleteLeaderboardBoardRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_DeleteLeaderboardBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ListLeaderboardBoardPeriods(ctx context.Context, in *ListLeaderboardBoardPeriodsRequest, opts ...grpc.CallOption) (*ListLeaderboardBoardPeriodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaderboardBoardPeriodsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_ListLeaderboardBoardPeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ListLeaderboardTop(ctx context.Context, in *ListLeaderboardTopRequest, opts ...grpc.CallOption) (*v1.ListLeaderboardTopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListLeaderboardTopResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_ListLeaderboardTop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetLeaderboardEntry(ctx context.Context, in *GetLeaderboardEntryRequest, opts ...grpc.CallOption) (*v1.LeaderboardScoreSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.LeaderboardScoreSnapshot)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetLeaderboardEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) DeleteLeaderboardEntry(ctx context.Context, in *DeleteLeaderboardEntryRequest, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_DeleteLeaderboardEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetLeaderboardSettlement(ctx context.Context, in *GetLeaderboardSettlementRequest, opts ...grpc.CallOption) (*GetLeaderboardSettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardSettlementResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetLeaderboardSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ListLeaderboardSettlements(ctx context.Context, in *ListLeaderboardSettlementsRequest, opts ...grpc.CallOption) (*ListLeaderboardSettlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaderboardSettlementsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_ListLeaderboardSettlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) VoidLeaderboardSettlement(ctx context.Context, in *VoidLeaderboardSettlementRequest, opts ...grpc.CallOption) (*LeaderboardSettlementAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardSettlementAck)
	err := c.cc.Invoke(ctx, LeaderboardsService_VoidLeaderboardSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) RerunLeaderboardSettlement(ctx context.Context, in *RerunLeaderboardSettlementRequest, opts ...grpc.CallOption) (*LeaderboardSettlementAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardSettlementAck)
	err := c.cc.Invoke(ctx, LeaderboardsService_RerunLeaderboardSettlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardsServiceServer is the server API for LeaderboardsService service.
// All implementations must embed UnimplementedLeaderboardsServiceServer
// for forward compatibility.
//
// LeaderboardsService 是排行榜 console 面：board 配置 CRUD、期 top、按
// subject 查条目、删条目（作弊处理——只有未封榜期可删，封榜即终局）。
type LeaderboardsServiceServer interface {
	CreateLeaderboardBoard(context.Context, *CreateLeaderboardBoardRequest) (*v1.LeaderboardBoard, error)
	ListLeaderboardBoards(context.Context, *ListLeaderboardBoardsRequest) (*ListLeaderboardBoardsResponse, error)
	GetLeaderboardBoard(context.Context, *GetLeaderboardBoardRequest) (*v1.LeaderboardBoard, error)
	UpdateLeaderboardBoard(context.Context, *UpdateLeaderboardBoardRequest) (*v1.LeaderboardBoard, error)
	DeleteLeaderboardBoard(context.Context, *DeleteLeaderboardBoardRequest) (*v1.Empty, error)
	ListLeaderboardBoardPeriods(context.Context, *ListLeaderboardBoardPeriodsRequest) (*ListLeaderboardBoardPeriodsResponse, error)
	ListLeaderboardTop(context.Context, *ListLeaderboardTopRequest) (*v1.ListLeaderboardTopResponse, error)
	GetLeaderboardEntry(context.Context, *GetLeaderboardEntryRequest) (*v1.LeaderboardScoreSnapshot, error)
	DeleteLeaderboardEntry(context.Context, *DeleteLeaderboardEntryRequest) (*v1.Empty, error)
	// —— Phase 2：结榜发奖（settled 拒绝 void/rerun；作弊处理窗口 = 宽限期）——
	GetLeaderboardSettlement(context.Context, *GetLeaderboardSettlementRequest) (*GetLeaderboardSettlementResponse, error)
	ListLeaderboardSettlements(context.Context, *ListLeaderboardSettlementsRequest) (*ListLeaderboardSettlementsResponse, error)
	VoidLeaderboardSettlement(context.Context, *VoidLeaderboardSettlementRequest) (*LeaderboardSettlementAck, error)
	RerunLeaderboardSettlement(context.Context, *RerunLeaderboardSettlementRequest) (*LeaderboardSettlementAck, error)
	mustEmbedUnimplementedLeaderboardsServiceServer()
}

// UnimplementedLeaderboardsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeaderboardsServiceServer struct{}

func (UnimplementedLeaderboardsServiceServer) CreateLeaderboardBoard(context.Context, *CreateLeaderboardBoardRequest) (*v1.LeaderboardBoard, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLeaderboardBoard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ListLeaderboardBoards(context.Context, *ListLeaderboardBoardsRequest) (*ListLeaderboardBoardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeaderboardBoards not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetLeaderboardBoard(context.Context, *GetLeaderboardBoardRequest) (*v1.LeaderboardBoard, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboardBoard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) UpdateLeaderboardBoard(context.Context, *UpdateLeaderboardBoardRequest) (*v1.LeaderboardBoard, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLeaderboardBoard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) DeleteLeaderboardBoard(context.Context, *DeleteLeaderboardBoardRequest) (*v1.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLeaderboardBoard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ListLeaderboardBoardPeriods(context.Context, *ListLeaderboardBoardPeriodsRequest) (*ListLeaderboardBoardPeriodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeaderboardBoardPeriods not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ListLeaderboardTop(context.Context, *ListLeaderboardTopRequest) (*v1.ListLeaderboardTopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeaderboardTop not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetLeaderboardEntry(context.Context, *GetLeaderboardEntryRequest) (*v1.LeaderboardScoreSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboardEntry not implemented")
}
func (UnimplementedLeaderboardsServiceServer) DeleteLeaderboardEntry(context.Context, *DeleteLeaderboardEntryRequest) (*v1.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLeaderboardEntry not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetLeaderboardSettlement(context.Context, *GetLeaderboardSettlementRequest) (*GetLeaderboardSettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboardSettlement not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ListLeaderboardSettlements(context.Context, *ListLeaderboardSettlementsRequest) (*ListLeaderboardSettlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeaderboardSettlements not implemented")
}
func (UnimplementedLeaderboardsServiceServer) VoidLeaderboardSettlement(context.Context, *VoidLeaderboardSettlementRequest) (*LeaderboardSettlementAck, error) {
	return nil, status.Error(codes.Unimplemented, "method VoidLeaderboardSettlement not implemented")
}
func (UnimplementedLeaderboardsServiceServer) RerunLeaderboardSettlement(context.Context, *RerunLeaderboardSettlementRequest) (*LeaderboardSettlementAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RerunLeaderboardSettlement not implemented")
}
func (UnimplementedLeaderboardsServiceServer) mustEmbedUnimplementedLeaderboardsServiceServer() {}
func (UnimplementedLeaderboardsServiceServer) testEmbeddedByValue()                             {}

// UnsafeLeaderboardsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardsServiceServer will
// result in compilation errors.
type UnsafeLeaderboardsServiceServer interface {
	mustEmbedUnimplementedLeaderboardsServiceServer()
}

func RegisterLeaderboardsServiceServer(s grpc.ServiceRegistrar, srv LeaderboardsServiceServer) {
	// If the following call panics, it indicates UnimplementedLeaderboardsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeaderboardsService_ServiceDesc, srv)
}

func _LeaderboardsService_CreateLeaderboardBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeaderboardBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).CreateLeaderboardBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_CreateLeaderboardBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).CreateLeaderboardBoard(ctx, req.(*CreateLeaderboardBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ListLeaderboardBoards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaderboardBoardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ListLeaderboardBoards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ListLeaderboardBoards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ListLeaderboardBoards(ctx, req.(*ListLeaderboardBoardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetLeaderboardBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetLeaderboardBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetLeaderboardBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetLeaderboardBoard(ctx, req.(*GetLeaderboardBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_UpdateLeaderboardBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLeaderboardBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).UpdateLeaderboardBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_UpdateLeaderboardBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).UpdateLeaderboardBoard(ctx, req.(*UpdateLeaderboardBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_DeleteLeaderboardBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLeaderboardBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_DeleteLeaderboardBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardBoard(ctx, req.(*DeleteLeaderboardBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ListLeaderboardBoardPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaderboardBoardPeriodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ListLeaderboardBoardPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ListLeaderboardBoardPeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ListLeaderboardBoardPeriods(ctx, req.(*ListLeaderboardBoardPeriodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ListLeaderboardTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaderboardTopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ListLeaderboardTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ListLeaderboardTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ListLeaderboardTop(ctx, req.(*ListLeaderboardTopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetLeaderboardEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetLeaderboardEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetLeaderboardEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetLeaderboardEntry(ctx, req.(*GetLeaderboardEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_DeleteLeaderboardEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLeaderboardEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_DeleteLeaderboardEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardEntry(ctx, req.(*DeleteLeaderboardEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetLeaderboardSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetLeaderboardSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetLeaderboardSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetLeaderboardSettlement(ctx, req.(*GetLeaderboardSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ListLeaderboardSettlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaderboardSettlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ListLeaderboardSettlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ListLeaderboardSettlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ListLeaderboardSettlements(ctx, req.(*ListLeaderboardSettlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_VoidLeaderboardSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidLeaderboardSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).VoidLeaderboardSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_VoidLeaderboardSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).VoidLeaderboardSettlement(ctx, req.(*VoidLeaderboardSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_RerunLeaderboardSettlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerunLeaderboardSettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).RerunLeaderboardSettlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_RerunLeaderboardSettlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).RerunLeaderboardSettlement(ctx, req.(*RerunLeaderboardSettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardsService_ServiceDesc is the grpc.ServiceDesc for LeaderboardsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torchwood.console.v1.LeaderboardsService",
	HandlerType: (*LeaderboardsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLeaderboardBoard",
			Handler:    _LeaderboardsService_CreateLeaderboardBoard_Handler,
		},
		{
			MethodName: "ListLeaderboardBoards",
			Handler:    _LeaderboardsService_ListLeaderboardBoards_Handler,
		},
		{
			MethodName: "GetLeaderboardBoard",
			Handler:    _LeaderboardsService_GetLeaderboardBoard_Handler,
		},
		{
			MethodName: "UpdateLeaderboardBoard",
			Handler:    _LeaderboardsService_UpdateLeaderboardBoard_Handler,
		},
		{
			MethodName: "DeleteLeaderboardBoard",
			Handler:    _LeaderboardsService_DeleteLeaderboardBoard_Handler,
		},
		{
			MethodName: "ListLeaderboardBoardPeriods",
			Handler:    _LeaderboardsService_ListLeaderboardBoardPeriods_Handler,
		},
		{
			MethodName: "ListLeaderboardTop",
			Handler:    _LeaderboardsService_ListLeaderboardTop_Handler,
		},
		{
			MethodName: "GetLeaderboardEntry",
			Handler:    _LeaderboardsService_GetLeaderboardEntry_Handler,
		},
		{
			MethodName: "DeleteLeaderboardEntry",
			Handler:    _LeaderboardsService_DeleteLeaderboardEntry_Handler,
		},
		{
			MethodName: "GetLeaderboardSettlement",
			Handler:    _LeaderboardsService_GetLeaderboardSettlement_Handler,
		},
		{
			MethodName: "ListLeaderboardSettlements",
			Handler:    _LeaderboardsService_ListLeaderboardSettlements_Handler,
		},
		{
			MethodName: "VoidLeaderboardSettlement",
			Handler:    _LeaderboardsService_VoidLeaderboardSettlement_Handler,
		},
		{
			MethodName: "RerunLeaderboardSettlement",
			Handler:    _LeaderboardsService_RerunLeaderboardSettlement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "console/v1/leaderboards.proto",
}
