// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: console/v1/leaderboards.proto

package consolev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	v1 "github.com/torchwoodcloud/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLeaderboardBoardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// asc | desc（缺省 desc）
	Sort string `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	// 声明单列 tiebreak 及方向（asc | desc）；缺省不声明
	TiebreakOrder string `protobuf:"bytes,3,opt,name=tiebreak_order,json=tiebreakOrder,proto3" json:"tiebreak_order,omitempty"`
	// parallel | earliest | latest（缺省 parallel）
	TieBreak string `protobuf:"bytes,4,opt,name=tie_break,json=tieBreak,proto3" json:"tie_break,omitempty"`
	// none | daily | weekly | monthly（缺省 none）
	PeriodKind string `protobuf:"bytes,5,opt,name=period_kind,json=periodKind,proto3" json:"period_kind,omitempty"`
	PeriodTz   string `protobuf:"bytes,6,opt,name=period_tz,json=periodTz,proto3" json:"period_tz,omitempty"`
	// best | latest | sum（缺省 best）
	Policy       string `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	ValueMin     *int64 `protobuf:"varint,8,opt,name=value_min,json=valueMin,proto3,oneof" json:"value_min,omitempty"`
	ValueMax     *int64 `protobuf:"varint,9,opt,name=value_max,json=valueMax,proto3,oneof" json:"value_max,omitempty"`
	ClientSubmit bool   `protobuf:"varint,10,opt,name=client_submit,json=clientSubmit,proto3" json:"client_submit,omitempty"`
	// 每期每主体提交次数上限（缺省 100，1..10000）
	PerSubjectSubmitLimit int32                       `protobuf:"varint,11,opt,name=per_subject_submit_limit,json=perSubjectSubmitLimit,proto3" json:"per_subject_submit_limit,omitempty"`
	RetentionPeriods      int32                       `protobuf:"varint,12,opt,name=retention_periods,json=retentionPeriods,proto3" json:"retention_periods,omitempty"`
	SubjectKind           string                      `protobuf:"bytes,13,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	Rewards               []*v1.LeaderboardRewardRule `protobuf:"bytes,14,rep,name=rewards,proto3" json:"rewards,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateLeaderboardBoardRequest) Reset() {
	*x = CreateLeaderboardBoardRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaderboardBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaderboardBoardRequest) ProtoMessage() {}

func (x *CreateLeaderboardBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaderboardBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateLeaderboardBoardRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaderboardBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetTiebreakOrder() string {
	if x != nil {
		return x.TiebreakOrder
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetTieBreak() string {
	if x != nil {
		return x.TieBreak
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetPeriodKind() string {
	if x != nil {
		return x.PeriodKind
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetPeriodTz() string {
	if x != nil {
		return x.PeriodTz
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetValueMin() int64 {
	if x != nil && x.ValueMin != nil {
		return *x.ValueMin
	}
	return 0
}

func (x *CreateLeaderboardBoardRequest) GetValueMax() int64 {
	if x != nil && x.ValueMax != nil {
		return *x.ValueMax
	}
	return 0
}

func (x *CreateLeaderboardBoardRequest) GetClientSubmit() bool {
	if x != nil {
		return x.ClientSubmit
	}
	return false
}

func (x *CreateLeaderboardBoardRequest) GetPerSubjectSubmitLimit() int32 {
	if x != nil {
		return x.PerSubjectSubmitLimit
	}
	return 0
}

func (x *CreateLeaderboardBoardRequest) GetRetentionPeriods() int32 {
	if x != nil {
		return x.RetentionPeriods
	}
	return 0
}

func (x *CreateLeaderboardBoardRequest) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *CreateLeaderboardBoardRequest) GetRewards() []*v1.LeaderboardRewardRule {
	if x != nil {
		return x.Rewards
	}
	return nil
}

type ListLeaderboardBoardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardBoardsRequest) Reset() {
	*x = ListLeaderboardBoardsRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardBoardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardBoardsRequest) ProtoMessage() {}

func (x *ListLeaderboardBoardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardBoardsRequest.ProtoReflect.Descriptor instead.
func (*ListLeaderboardBoardsRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{1}
}

type ListLeaderboardBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Boards        []*v1.LeaderboardBoard `protobuf:"bytes,1,rep,name=boards,proto3" json:"boards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardBoardsResponse) Reset() {
	*x = ListLeaderboardBoardsResponse{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardBoardsResponse) ProtoMessage() {}

func (x *ListLeaderboardBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListLeaderboardBoardsResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{2}
}

func (x *ListLeaderboardBoardsResponse) GetBoards() []*v1.LeaderboardBoard {
	if x != nil {
		return x.Boards
	}
	return nil
}

type GetLeaderboardBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardBoardRequest) Reset() {
	*x = GetLeaderboardBoardRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardBoardRequest) ProtoMessage() {}

func (x *GetLeaderboardBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardBoardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardBoardRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeaderboardBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

// UpdateLeaderboardBoardRequest 用 proto3 optional 表达"未设置 = 不修改"；
// 显式清空走 clear_* 布尔。period/sort/tiebreak 声明/policy/tie_break 在
// 榜内已有条目时不可改（FailedPrecondition）。
type UpdateLeaderboardBoardRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BoardId               string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Sort                  *string                `protobuf:"bytes,2,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	TiebreakOrder         *string                `protobuf:"bytes,3,opt,name=tiebreak_order,json=tiebreakOrder,proto3,oneof" json:"tiebreak_order,omitempty"`
	ClearTiebreak         bool                   `protobuf:"varint,4,opt,name=clear_tiebreak,json=clearTiebreak,proto3" json:"clear_tiebreak,omitempty"`
	TieBreak              *string                `protobuf:"bytes,5,opt,name=tie_break,json=tieBreak,proto3,oneof" json:"tie_break,omitempty"`
	PeriodKind            *string                `protobuf:"bytes,6,opt,name=period_kind,json=periodKind,proto3,oneof" json:"period_kind,omitempty"`
	PeriodTz              *string                `protobuf:"bytes,7,opt,name=period_tz,json=periodTz,proto3,oneof" json:"period_tz,omitempty"`
	Policy                *string                `protobuf:"bytes,8,opt,name=policy,proto3,oneof" json:"policy,omitempty"`
	ValueMin              *int64                 `protobuf:"varint,9,opt,name=value_min,json=valueMin,proto3,oneof" json:"value_min,omitempty"`
	ValueMax              *int64                 `protobuf:"varint,10,opt,name=value_max,json=valueMax,proto3,oneof" json:"value_max,omitempty"`
	ClearValueBounds      bool                   `protobuf:"varint,11,opt,name=clear_value_bounds,json=clearValueBounds,proto3" json:"clear_value_bounds,omitempty"`
	ClientSubmit          *bool                  `protobuf:"varint,12,opt,name=client_submit,json=clientSubmit,proto3,oneof" json:"client_submit,omitempty"`
	PerSubjectSubmitLimit *int32                 `protobuf:"varint,13,opt,name=per_subject_submit_limit,json=perSubjectSubmitLimit,proto3,oneof" json:"per_subject_submit_limit,omitempty"`
	RetentionPeriods      *int32                 `protobuf:"varint,14,opt,name=retention_periods,json=retentionPeriods,proto3,oneof" json:"retention_periods,omitempty"`
	SubjectKind           *string                `protobuf:"bytes,15,opt,name=subject_kind,json=subjectKind,proto3,oneof" json:"subject_kind,omitempty"`
	// 非空 = 整体替换；clear_rewards = true 显式清空
	Rewards       []*v1.LeaderboardRewardRule `protobuf:"bytes,16,rep,name=rewards,proto3" json:"rewards,omitempty"`
	ClearRewards  bool                        `protobuf:"varint,17,opt,name=clear_rewards,json=clearRewards,proto3" json:"clear_rewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLeaderboardBoardRequest) Reset() {
	*x = UpdateLeaderboardBoardRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLeaderboardBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeaderboardBoardRequest) ProtoMessage() {}

func (x *UpdateLeaderboardBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeaderboardBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeaderboardBoardRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLeaderboardBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetSort() string {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetTiebreakOrder() string {
	if x != nil && x.TiebreakOrder != nil {
		return *x.TiebreakOrder
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetClearTiebreak() bool {
	if x != nil {
		return x.ClearTiebreak
	}
	return false
}

func (x *UpdateLeaderboardBoardRequest) GetTieBreak() string {
	if x != nil && x.TieBreak != nil {
		return *x.TieBreak
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetPeriodKind() string {
	if x != nil && x.PeriodKind != nil {
		return *x.PeriodKind
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetPeriodTz() string {
	if x != nil && x.PeriodTz != nil {
		return *x.PeriodTz
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetPolicy() string {
	if x != nil && x.Policy != nil {
		return *x.Policy
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetValueMin() int64 {
	if x != nil && x.ValueMin != nil {
		return *x.ValueMin
	}
	return 0
}

func (x *UpdateLeaderboardBoardRequest) GetValueMax() int64 {
	if x != nil && x.ValueMax != nil {
		return *x.ValueMax
	}
	return 0
}

func (x *UpdateLeaderboardBoardRequest) GetClearValueBounds() bool {
	if x != nil {
		return x.ClearValueBounds
	}
	return false
}

func (x *UpdateLeaderboardBoardRequest) GetClientSubmit() bool {
	if x != nil && x.ClientSubmit != nil {
		return *x.ClientSubmit
	}
	return false
}

func (x *UpdateLeaderboardBoardRequest) GetPerSubjectSubmitLimit() int32 {
	if x != nil && x.PerSubjectSubmitLimit != nil {
		return *x.PerSubjectSubmitLimit
	}
	return 0
}

func (x *UpdateLeaderboardBoardRequest) GetRetentionPeriods() int32 {
	if x != nil && x.RetentionPeriods != nil {
		return *x.RetentionPeriods
	}
	return 0
}

func (x *UpdateLeaderboardBoardRequest) GetSubjectKind() string {
	if x != nil && x.SubjectKind != nil {
		return *x.SubjectKind
	}
	return ""
}

func (x *UpdateLeaderboardBoardRequest) GetRewards() []*v1.LeaderboardRewardRule {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *UpdateLeaderboardBoardRequest) GetClearRewards() bool {
	if x != nil {
		return x.ClearRewards
	}
	return false
}

type DeleteLeaderboardBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeaderboardBoardRequest) Reset() {
	*x = DeleteLeaderboardBoardRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeaderboardBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeaderboardBoardRequest) ProtoMessage() {}

func (x *DeleteLeaderboardBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeaderboardBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeaderboardBoardRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLeaderboardBoardRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

type ListLeaderboardBoardPeriodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardBoardPeriodsRequest) Reset() {
	*x = ListLeaderboardBoardPeriodsRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardBoardPeriodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardBoardPeriodsRequest) ProtoMessage() {}

func (x *ListLeaderboardBoardPeriodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardBoardPeriodsRequest.ProtoReflect.Descriptor instead.
func (*ListLeaderboardBoardPeriodsRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{6}
}

func (x *ListLeaderboardBoardPeriodsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ListLeaderboardBoardPeriodsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLeaderboardBoardPeriodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []string               `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardBoardPeriodsResponse) Reset() {
	*x = ListLeaderboardBoardPeriodsResponse{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardBoardPeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardBoardPeriodsResponse) ProtoMessage() {}

func (x *ListLeaderboardBoardPeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardBoardPeriodsResponse.ProtoReflect.Descriptor instead.
func (*ListLeaderboardBoardPeriodsResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{7}
}

func (x *ListLeaderboardBoardPeriodsResponse) GetPeriods() []string {
	if x != nil {
		return x.Periods
	}
	return nil
}

type ListLeaderboardTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardTopRequest) Reset() {
	*x = ListLeaderboardTopRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardTopRequest) ProtoMessage() {}

func (x *ListLeaderboardTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardTopRequest.ProtoReflect.Descriptor instead.
func (*ListLeaderboardTopRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeaderboardTopRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ListLeaderboardTopRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *ListLeaderboardTopRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLeaderboardTopRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetLeaderboardEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardEntryRequest) Reset() {
	*x = GetLeaderboardEntryRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardEntryRequest) ProtoMessage() {}

func (x *GetLeaderboardEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardEntryRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardEntryRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{9}
}

func (x *GetLeaderboardEntryRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetLeaderboardEntryRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetLeaderboardEntryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type DeleteLeaderboardEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeaderboardEntryRequest) Reset() {
	*x = DeleteLeaderboardEntryRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeaderboardEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeaderboardEntryRequest) ProtoMessage() {}

func (x *DeleteLeaderboardEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeaderboardEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeaderboardEntryRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLeaderboardEntryRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *DeleteLeaderboardEntryRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DeleteLeaderboardEntryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetLeaderboardSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardSettlementRequest) Reset() {
	*x = GetLeaderboardSettlementRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardSettlementRequest) ProtoMessage() {}

func (x *GetLeaderboardSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardSettlementRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardSettlementRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{11}
}

func (x *GetLeaderboardSettlementRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *GetLeaderboardSettlementRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetLeaderboardSettlementResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Settlement    *v1.LeaderboardSettlement        `protobuf:"bytes,1,opt,name=settlement,proto3" json:"settlement,omitempty"`
	Grants        []*v1.LeaderboardSettlementGrant `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardSettlementResponse) Reset() {
	*x = GetLeaderboardSettlementResponse{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardSettlementResponse) ProtoMessage() {}

func (x *GetLeaderboardSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardSettlementResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardSettlementResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{12}
}

func (x *GetLeaderboardSettlementResponse) GetSettlement() *v1.LeaderboardSettlement {
	if x != nil {
		return x.Settlement
	}
	return nil
}

func (x *GetLeaderboardSettlementResponse) GetGrants() []*v1.LeaderboardSettlementGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ListLeaderboardSettlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardSettlementsRequest) Reset() {
	*x = ListLeaderboardSettlementsRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardSettlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardSettlementsRequest) ProtoMessage() {}

func (x *ListLeaderboardSettlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardSettlementsRequest.ProtoReflect.Descriptor instead.
func (*ListLeaderboardSettlementsRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{13}
}

func (x *ListLeaderboardSettlementsRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *ListLeaderboardSettlementsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLeaderboardSettlementsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Settlements   []*v1.LeaderboardSettlement `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaderboardSettlementsResponse) Reset() {
	*x = ListLeaderboardSettlementsResponse{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaderboardSettlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaderboardSettlementsResponse) ProtoMessage() {}

func (x *ListLeaderboardSettlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaderboardSettlementsResponse.ProtoReflect.Descriptor instead.
func (*ListLeaderboardSettlementsResponse) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{14}
}

func (x *ListLeaderboardSettlementsResponse) GetSettlements() []*v1.LeaderboardSettlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

type VoidLeaderboardSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidLeaderboardSettlementRequest) Reset() {
	*x = VoidLeaderboardSettlementRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidLeaderboardSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidLeaderboardSettlementRequest) ProtoMessage() {}

func (x *VoidLeaderboardSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidLeaderboardSettlementRequest.ProtoReflect.Descriptor instead.
func (*VoidLeaderboardSettlementRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{15}
}

func (x *VoidLeaderboardSettlementRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *VoidLeaderboardSettlementRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type RerunLeaderboardSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardId       string                 `protobuf:"bytes,1,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerunLeaderboardSettlementRequest) Reset() {
	*x = RerunLeaderboardSettlementRequest{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerunLeaderboardSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerunLeaderboardSettlementRequest) ProtoMessage() {}

func (x *RerunLeaderboardSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerunLeaderboardSettlementRequest.ProtoReflect.Descriptor instead.
func (*RerunLeaderboardSettlementRequest) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{16}
}

func (x *RerunLeaderboardSettlementRequest) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *RerunLeaderboardSettlementRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type LeaderboardSettlementAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardSettlementAck) Reset() {
	*x = LeaderboardSettlementAck{}
	mi := &file_console_v1_leaderboards_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardSettlementAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardSettlementAck) ProtoMessage() {}

func (x *LeaderboardSettlementAck) ProtoReflect() protoreflect.Message {
	mi := &file_console_v1_leaderboards_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardSettlementAck.ProtoReflect.Descriptor instead.
func (*LeaderboardSettlementAck) Descriptor() ([]byte, []int) {
	return file_console_v1_leaderboards_proto_rawDescGZIP(), []int{17}
}

var File_console_v1_leaderboards_proto protoreflect.FileDescriptor

const file_console_v1_leaderboards_proto_rawDesc = "" +
	"\n" +
	"\x1dconsole/v1/leaderboards.proto\x12\x14torchwood.console.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\x1a\x16shared/v1/common.proto\x1a\x1bshared/v1/leaderboard.proto\"\xd1\x04\n" +
	"\x1dCreateLeaderboardBoardRequest\x12.\n" +
	"\x02id\x18\x01 \x01(\tB\x1e\xbaH\x1b\xc8\x01\x01r\x16\x18(2\x12^[a-z_][a-z0-9_]*$R\x02id\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12%\n" +
	"\x0etiebreak_order\x18\x03 \x01(\tR\rtiebreakOrder\x12\x1b\n" +
	"\ttie_break\x18\x04 \x01(\tR\btieBreak\x12\x1f\n" +
	"\vperiod_kind\x18\x05 \x01(\tR\n" +
	"periodKind\x12\x1b\n" +
	"\tperiod_tz\x18\x06 \x01(\tR\bperiodTz\x12\x16\n" +
	"\x06policy\x18\a \x01(\tR\x06policy\x12 \n" +
	"\tvalue_min\x18\b \x01(\x03H\x00R\bvalueMin\x88\x01\x01\x12 \n" +
	"\tvalue_max\x18\t \x01(\x03H\x01R\bvalueMax\x88\x01\x01\x12#\n" +
	"\rclient_submit\x18\n" +
	" \x01(\bR\fclientSubmit\x127\n" +
	"\x18per_subject_submit_limit\x18\v \x01(\x05R\x15perSubjectSubmitLimit\x12+\n" +
	"\x11retention_periods\x18\f \x01(\x05R\x10retentionPeriods\x12!\n" +
	"\fsubject_kind\x18\r \x01(\tR\vsubjectKind\x12D\n" +
	"\arewards\x18\x0e \x03(\v2*.torchwood.shared.v1.LeaderboardRewardRuleR\arewardsB\f\n" +
	"\n" +
	"_value_minB\f\n" +
	"\n" +
	"_value_max\"\x1e\n" +
	"\x1cListLeaderboardBoardsRequest\"^\n" +
	"\x1dListLeaderboardBoardsResponse\x12=\n" +
	"\x06boards\x18\x01 \x03(\v2%.torchwood.shared.v1.LeaderboardBoardR\x06boards\"?\n" +
	"\x1aGetLeaderboardBoardRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\"\x99\a\n" +
	"\x1dUpdateLeaderboardBoardRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12\x17\n" +
	"\x04sort\x18\x02 \x01(\tH\x00R\x04sort\x88\x01\x01\x12*\n" +
	"\x0etiebreak_order\x18\x03 \x01(\tH\x01R\rtiebreakOrder\x88\x01\x01\x12%\n" +
	"\x0eclear_tiebreak\x18\x04 \x01(\bR\rclearTiebreak\x12 \n" +
	"\ttie_break\x18\x05 \x01(\tH\x02R\btieBreak\x88\x01\x01\x12$\n" +
	"\vperiod_kind\x18\x06 \x01(\tH\x03R\n" +
	"periodKind\x88\x01\x01\x12 \n" +
	"\tperiod_tz\x18\a \x01(\tH\x04R\bperiodTz\x88\x01\x01\x12\x1b\n" +
	"\x06policy\x18\b \x01(\tH\x05R\x06policy\x88\x01\x01\x12 \n" +
	"\tvalue_min\x18\t \x01(\x03H\x06R\bvalueMin\x88\x01\x01\x12 \n" +
	"\tvalue_max\x18\n" +
	" \x01(\x03H\aR\bvalueMax\x88\x01\x01\x12,\n" +
	"\x12clear_value_bounds\x18\v \x01(\bR\x10clearValueBounds\x12(\n" +
	"\rclient_submit\x18\f \x01(\bH\bR\fclientSubmit\x88\x01\x01\x12<\n" +
	"\x18per_subject_submit_limit\x18\r \x01(\x05H\tR\x15perSubjectSubmitLimit\x88\x01\x01\x120\n" +
	"\x11retention_periods\x18\x0e \x01(\x05H\n" +
	"R\x10retentionPeriods\x88\x01\x01\x12&\n" +
	"\fsubject_kind\x18\x0f \x01(\tH\vR\vsubjectKind\x88\x01\x01\x12D\n" +
	"\arewards\x18\x10 \x03(\v2*.torchwood.shared.v1.LeaderboardRewardRuleR\arewards\x12#\n" +
	"\rclear_rewards\x18\x11 \x01(\bR\fclearRewardsB\a\n" +
	"\x05_sortB\x11\n" +
	"\x0f_tiebreak_orderB\f\n" +
	"\n" +
	"_tie_breakB\x0e\n" +
	"\f_period_kindB\f\n" +
	"\n" +
	"_period_tzB\t\n" +
	"\a_policyB\f\n" +
	"\n" +
	"_value_minB\f\n" +
	"\n" +
	"_value_maxB\x10\n" +
	"\x0e_client_submitB\x1b\n" +
	"\x19_per_subject_submit_limitB\x14\n" +
	"\x12_retention_periodsB\x0f\n" +
	"\r_subject_kind\"B\n" +
	"\x1dDeleteLeaderboardBoardRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\"i\n" +
	"\"ListLeaderboardBoardPeriodsRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12 \n" +
	"\x05limit\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc8\x01(\x00R\x05limit\"?\n" +
	"#ListLeaderboardBoardPeriodsResponse\x12\x18\n" +
	"\aperiods\x18\x01 \x03(\tR\aperiods\"\x9d\x01\n" +
	"\x19ListLeaderboardTopRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"~\n" +
	"\x1aGetLeaderboardEntryRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12%\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tsubjectId\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"\x89\x01\n" +
	"\x1dDeleteLeaderboardEntryRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12%\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tsubjectId\x12\x1e\n" +
	"\x06period\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06period\"d\n" +
	"\x1fGetLeaderboardSettlementRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12\x1e\n" +
	"\x06period\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06period\"\xb7\x01\n" +
	" GetLeaderboardSettlementResponse\x12J\n" +
	"\n" +
	"settlement\x18\x01 \x01(\v2*.torchwood.shared.v1.LeaderboardSettlementR\n" +
	"settlement\x12G\n" +
	"\x06grants\x18\x02 \x03(\v2/.torchwood.shared.v1.LeaderboardSettlementGrantR\x06grants\"h\n" +
	"!ListLeaderboardSettlementsRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12 \n" +
	"\x05limit\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xc8\x01(\x00R\x05limit\"r\n" +
	"\"ListLeaderboardSettlementsResponse\x12L\n" +
	"\vsettlements\x18\x01 \x03(\v2*.torchwood.shared.v1.LeaderboardSettlementR\vsettlements\"e\n" +
	" VoidLeaderboardSettlementRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12\x1e\n" +
	"\x06period\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06period\"f\n" +
	"!RerunLeaderboardSettlementRequest\x12!\n" +
	"\bboard_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aboardId\x12\x1e\n" +
	"\x06period\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06period\"\x1a\n" +
	"\x18LeaderboardSettlementAck2\x84\x15\n" +
	"\x13LeaderboardsService\x12\xad\x01\n" +
	"\x16CreateLeaderboardBoard\x123.torchwood.console.v1.CreateLeaderboardBoardRequest\x1a%.torchwood.shared.v1.LeaderboardBoard\"7\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/console/leaderboards/boards\x12\xbd\x01\n" +
	"\x15ListLeaderboardBoards\x122.torchwood.console.v1.ListLeaderboardBoardsRequest\x1a3.torchwood.console.v1.ListLeaderboardBoardsResponse\";\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x02!\x12\x1f/v1/console/leaderboards/boards\x12\xb6\x01\n" +
	"\x13GetLeaderboardBoard\x120.torchwood.console.v1.GetLeaderboardBoardRequest\x1a%.torchwood.shared.v1.LeaderboardBoard\"F\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x02,\x12*/v1/console/leaderboards/boards/{board_id}\x12\xb8\x01\n" +
	"\x16UpdateLeaderboardBoard\x123.torchwood.console.v1.UpdateLeaderboardBoardRequest\x1a%.torchwood.shared.v1.LeaderboardBoard\"B\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02/:\x01*2*/v1/console/leaderboards/boards/{board_id}\x12\xaa\x01\n" +
	"\x16DeleteLeaderboardBoard\x123.torchwood.console.v1.DeleteLeaderboardBoardRequest\x1a\x1a.torchwood.shared.v1.Empty\"?\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02,**/v1/console/leaderboards/boards/{board_id}\x12\xe2\x01\n" +
	"\x1bListLeaderboardBoardPeriods\x128.torchwood.console.v1.ListLeaderboardBoardPeriodsRequest\x1a9.torchwood.console.v1.ListLeaderboardBoardPeriodsResponse\"N\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x024\x122/v1/console/leaderboards/boards/{board_id}/periods\x12\xc2\x01\n" +
	"\x12ListLeaderboardTop\x12/.torchwood.console.v1.ListLeaderboardTopRequest\x1a/.torchwood.shared.v1.ListLeaderboardTopResponse\"J\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x020\x12./v1/console/leaderboards/boards/{board_id}/top\x12\xd3\x01\n" +
	"\x13GetLeaderboardEntry\x120.torchwood.console.v1.GetLeaderboardEntryRequest\x1a-.torchwood.shared.v1.LeaderboardScoreSnapshot\"[\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x02A\x12?/v1/console/leaderboards/boards/{board_id}/entries/{subject_id}\x12\xbf\x01\n" +
	"\x16DeleteLeaderboardEntry\x123.torchwood.console.v1.DeleteLeaderboardEntryRequest\x1a\x1a.torchwood.shared.v1.Empty\"T\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02A*?/v1/console/leaderboards/boards/{board_id}/entries/{subject_id}\x12\xe6\x01\n" +
	"\x18GetLeaderboardSettlement\x125.torchwood.console.v1.GetLeaderboardSettlementRequest\x1a6.torchwood.console.v1.GetLeaderboardSettlementResponse\"[\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x02A\x12?/v1/console/leaderboards/boards/{board_id}/settlements/{period}\x12\xe3\x01\n" +
	"\x1aListLeaderboardSettlements\x127.torchwood.console.v1.ListLeaderboardSettlementsRequest\x1a8.torchwood.console.v1.ListLeaderboardSettlementsResponse\"R\x8a\xb2\x19\x10\b\x04\x12\x05owner\x12\x05admin\x82\xd3\xe4\x93\x028\x126/v1/console/leaderboards/boards/{board_id}/settlements\x12\xde\x01\n" +
	"\x19VoidLeaderboardSettlement\x126.torchwood.console.v1.VoidLeaderboardSettlementRequest\x1a..torchwood.console.v1.LeaderboardSettlementAck\"Y\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02F\"D/v1/console/leaderboards/boards/{board_id}/settlements/{period}:void\x12\xe1\x01\n" +
	"\x1aRerunLeaderboardSettlement\x127.torchwood.console.v1.RerunLeaderboardSettlementRequest\x1a..torchwood.console.v1.LeaderboardSettlementAck\"Z\x8a\xb2\x19\t\b\x04\x12\x05owner\x82\xd3\xe4\x93\x02G\"E/v1/console/leaderboards/boards/{board_id}/settlements/{period}:rerun\x1a\x06\x92\xb2\x19\x02\b\x04B\xe1\x03\x92A\x9a\x03RR\n" +
	"\adefault\x12G\n" +
	"\x1dAn unexpected error response.\x12&\n" +
	"$\x1a\".torchwood.shared.v1.ErrorResponseZ\x91\x02\n" +
	"3\n" +
	"\x06Bearer\x12)\b\x02\x12\x14格式: Bearer <jwt>\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06cookie\x12\x00z\"\n" +
	"\x12x-torchwood-access\x12\f\x1a\n" +
	"permissionZAgithub.com/torchwoodcloud/torchwood/genproto/console/v1;consolev1b\x06proto3"

var (
	file_console_v1_leaderboards_proto_rawDescOnce sync.Once
	file_console_v1_leaderboards_proto_rawDescData []byte
)

func file_console_v1_leaderboards_proto_rawDescGZIP() []byte {
	file_console_v1_leaderboards_proto_rawDescOnce.Do(func() {
		file_console_v1_leaderboards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_console_v1_leaderboards_proto_rawDesc), len(file_console_v1_leaderboards_proto_rawDesc)))
	})
	return file_console_v1_leaderboards_proto_rawDescData
}

var file_console_v1_leaderboards_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_console_v1_leaderboards_proto_goTypes = []any{
	(*CreateLeaderboardBoardRequest)(nil),       // 0: torchwood.console.v1.CreateLeaderboardBoardRequest
	(*ListLeaderboardBoardsRequest)(nil),        // 1: torchwood.console.v1.ListLeaderboardBoardsRequest
	(*ListLeaderboardBoardsResponse)(nil),       // 2: torchwood.console.v1.ListLeaderboardBoardsResponse
	(*GetLeaderboardBoardRequest)(nil),          // 3: torchwood.console.v1.GetLeaderboardBoardRequest
	(*UpdateLeaderboardBoardRequest)(nil),       // 4: torchwood.console.v1.UpdateLeaderboardBoardRequest
	(*DeleteLeaderboardBoardRequest)(nil),       // 5: torchwood.console.v1.DeleteLeaderboardBoardRequest
	(*ListLeaderboardBoardPeriodsRequest)(nil),  // 6: torchwood.console.v1.ListLeaderboardBoardPeriodsRequest
	(*ListLeaderboardBoardPeriodsResponse)(nil), // 7: torchwood.console.v1.ListLeaderboardBoardPeriodsResponse
	(*ListLeaderboardTopRequest)(nil),           // 8: torchwood.console.v1.ListLeaderboardTopRequest
	(*GetLeaderboardEntryRequest)(nil),          // 9: torchwood.console.v1.GetLeaderboardEntryRequest
	(*DeleteLeaderboardEntryRequest)(nil),       // 10: torchwood.console.v1.DeleteLeaderboardEntryRequest
	(*GetLeaderboardSettlementRequest)(nil),     // 11: torchwood.console.v1.GetLeaderboardSettlementRequest
	(*GetLeaderboardSettlementResponse)(nil),    // 12: torchwood.console.v1.GetLeaderboardSettlementResponse
	(*ListLeaderboardSettlementsRequest)(nil),   // 13: torchwood.console.v1.ListLeaderboardSettlementsRequest
	(*ListLeaderboardSettlementsResponse)(nil),  // 14: torchwood.console.v1.ListLeaderboardSettlementsResponse
	(*VoidLeaderboardSettlementRequest)(nil),    // 15: torchwood.console.v1.VoidLeaderboardSettlementRequest
	(*RerunLeaderboardSettlementRequest)(nil),   // 16: torchwood.console.v1.RerunLeaderboardSettlementRequest
	(*LeaderboardSettlementAck)(nil),            // 17: torchwood.console.v1.LeaderboardSettlementAck
	(*v1.LeaderboardRewardRule)(nil),            // 18: torchwood.shared.v1.LeaderboardRewardRule
	(*v1.LeaderboardBoard)(nil),                 // 19: torchwood.shared.v1.LeaderboardBoard
	(*v1.LeaderboardSettlement)(nil),            // 20: torchwood.shared.v1.LeaderboardSettlement
	(*v1.LeaderboardSettlementGrant)(nil),       // 21: torchwood.shared.v1.LeaderboardSettlementGrant
	(*v1.Empty)(nil),                            // 22: torchwood.shared.v1.Empty
	(*v1.ListLeaderboardTopResponse)(nil),       // 23: torchwood.shared.v1.ListLeaderboardTopResponse
	(*v1.LeaderboardScoreSnapshot)(nil),         // 24: torchwood.shared.v1.LeaderboardScoreSnapshot
}
var file_console_v1_leaderboards_proto_depIdxs = []int32{
	18, // 0: torchwood.console.v1.CreateLeaderboardBoardRequest.rewards:type_name -> torchwood.shared.v1.LeaderboardRewardRule
	19, // 1: torchwood.console.v1.ListLeaderboardBoardsResponse.boards:type_name -> torchwood.shared.v1.LeaderboardBoard
	18, // 2: torchwood.console.v1.UpdateLeaderboardBoardRequest.rewards:type_name -> torchwood.shared.v1.LeaderboardRewardRule
	20, // 3: torchwood.console.v1.GetLeaderboardSettlementResponse.settlement:type_name -> torchwood.shared.v1.LeaderboardSettlement
	21, // 4: torchwood.console.v1.GetLeaderboardSettlementResponse.grants:type_name -> torchwood.shared.v1.LeaderboardSettlementGrant
	20, // 5: torchwood.console.v1.ListLeaderboardSettlementsResponse.settlements:type_name -> torchwood.shared.v1.LeaderboardSettlement
	0,  // 6: torchwood.console.v1.LeaderboardsService.CreateLeaderboardBoard:input_type -> torchwood.console.v1.CreateLeaderboardBoardRequest
	1,  // 7: torchwood.console.v1.LeaderboardsService.ListLeaderboardBoards:input_type -> torchwood.console.v1.ListLeaderboardBoardsRequest
	3,  // 8: torchwood.console.v1.LeaderboardsService.GetLeaderboardBoard:input_type -> torchwood.console.v1.GetLeaderboardBoardRequest
	4,  // 9: torchwood.console.v1.LeaderboardsService.UpdateLeaderboardBoard:input_type -> torchwood.console.v1.UpdateLeaderboardBoardRequest
	5,  // 10: torchwood.console.v1.LeaderboardsService.DeleteLeaderboardBoard:input_type -> torchwood.console.v1.DeleteLeaderboardBoardRequest
	6,  // 11: torchwood.console.v1.LeaderboardsService.ListLeaderboardBoardPeriods:input_type -> torchwood.console.v1.ListLeaderboardBoardPeriodsRequest
	8,  // 12: torchwood.console.v1.LeaderboardsService.ListLeaderboardTop:input_type -> torchwood.console.v1.ListLeaderboardTopRequest
	9,  // 13: torchwood.console.v1.LeaderboardsService.GetLeaderboardEntry:input_type -> torchwood.console.v1.GetLeaderboardEntryRequest
	10, // 14: torchwood.console.v1.LeaderboardsService.DeleteLeaderboardEntry:input_type -> torchwood.console.v1.DeleteLeaderboardEntryRequest
	11, // 15: torchwood.console.v1.LeaderboardsService.GetLeaderboardSettlement:input_type -> torchwood.console.v1.GetLeaderboardSettlementRequest
	13, // 16: torchwood.console.v1.LeaderboardsService.ListLeaderboardSettlements:input_type -> torchwood.console.v1.ListLeaderboardSettlementsRequest
	15, // 17: torchwood.console.v1.LeaderboardsService.VoidLeaderboardSettlement:input_type -> torchwood.console.v1.VoidLeaderboardSettlementRequest
	16, // 18: torchwood.console.v1.LeaderboardsService.RerunLeaderboardSettlement:input_type -> torchwood.console.v1.RerunLeaderboardSettlementRequest
	19, // 19: torchwood.console.v1.LeaderboardsService.CreateLeaderboardBoard:output_type -> torchwood.shared.v1.LeaderboardBoard
	2,  // 20: torchwood.console.v1.LeaderboardsService.ListLeaderboardBoards:output_type -> torchwood.console.v1.ListLeaderboardBoardsResponse
	19, // 21: torchwood.console.v1.LeaderboardsService.GetLeaderboardBoard:output_type -> torchwood.shared.v1.LeaderboardBoard
	19, // 22: torchwood.console.v1.LeaderboardsService.UpdateLeaderboardBoard:output_type -> torchwood.shared.v1.LeaderboardBoard
	22, // 23: torchwood.console.v1.LeaderboardsService.DeleteLeaderboardBoard:output_type -> torchwood.shared.v1.Empty
	7,  // 24: torchwood.console.v1.LeaderboardsService.ListLeaderboardBoardPeriods:output_type -> torchwood.console.v1.ListLeaderboardBoardPeriodsResponse
	23, // 25: torchwood.console.v1.LeaderboardsService.ListLeaderboardTop:output_type -> torchwood.shared.v1.ListLeaderboardTopResponse
	24, // 26: torchwood.console.v1.LeaderboardsService.GetLeaderboardEntry:output_type -> torchwood.shared.v1.LeaderboardScoreSnapshot
	22, // 27: torchwood.console.v1.LeaderboardsService.DeleteLeaderboardEntry:output_type -> torchwood.shared.v1.Empty
	12, // 28: torchwood.console.v1.LeaderboardsService.GetLeaderboardSettlement:output_type -> torchwood.console.v1.GetLeaderboardSettlementResponse
	14, // 29: torchwood.console.v1.LeaderboardsService.ListLeaderboardSettlements:output_type -> torchwood.console.v1.ListLeaderboardSettlementsResponse
	17, // 30: torchwood.console.v1.LeaderboardsService.VoidLeaderboardSettlement:output_type -> torchwood.console.v1.LeaderboardSettlementAck
	17, // 31: torchwood.console.v1.LeaderboardsService.RerunLeaderboardSettlement:output_type -> torchwood.console.v1.LeaderboardSettlementAck
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_console_v1_leaderboards_proto_init() }
func file_console_v1_leaderboards_proto_init() {
	if File_console_v1_leaderboards_proto != nil {
		return
	}
	file_console_v1_leaderboards_proto_msgTypes[0].OneofWrappers = []any{}
	file_console_v1_leaderboards_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_console_v1_leaderboards_proto_rawDesc), len(file_console_v1_leaderboards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_console_v1_leaderboards_proto_goTypes,
		DependencyIndexes: file_console_v1_leaderboards_proto_depIdxs,
		MessageInfos:      file_console_v1_leaderboards_proto_msgTypes,
	}.Build()
	File_console_v1_leaderboards_proto = out.File
	file_console_v1_leaderboards_proto_goTypes = nil
	file_console_v1_leaderboards_proto_depIdxs = nil
}
