// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx/boot"
	"github.com/torchwoodcloud/torchwood/cmd/server/internal/runtime"
	"github.com/torchwoodcloud/torchwood/internal/api/clientgrpc"
	"github.com/torchwoodcloud/torchwood/internal/api/consolegrpc"
	realtime2 "github.com/torchwoodcloud/torchwood/internal/api/realtime"
	"github.com/torchwoodcloud/torchwood/internal/api/servergrpc"
	"github.com/torchwoodcloud/torchwood/internal/api/serverhttp"
	"github.com/torchwoodcloud/torchwood/internal/app/analytics"
	"github.com/torchwoodcloud/torchwood/internal/app/assets"
	billing2 "github.com/torchwoodcloud/torchwood/internal/app/billing"
	"github.com/torchwoodcloud/torchwood/internal/app/client"
	"github.com/torchwoodcloud/torchwood/internal/app/console"
	events2 "github.com/torchwoodcloud/torchwood/internal/app/events"
	functions2 "github.com/torchwoodcloud/torchwood/internal/app/functions"
	payments2 "github.com/torchwoodcloud/torchwood/internal/app/payments"
	"github.com/torchwoodcloud/torchwood/internal/app/server"
	storage2 "github.com/torchwoodcloud/torchwood/internal/app/storage"
	"github.com/torchwoodcloud/torchwood/internal/app/subscriptions"
	"github.com/torchwoodcloud/torchwood/internal/infra"
	"github.com/torchwoodcloud/torchwood/internal/infra/auth"
	"github.com/torchwoodcloud/torchwood/internal/infra/auth/principalcache"
	"github.com/torchwoodcloud/torchwood/internal/infra/billing"
	"github.com/torchwoodcloud/torchwood/internal/infra/bun/bunrepo"
	"github.com/torchwoodcloud/torchwood/internal/infra/clients"
	"github.com/torchwoodcloud/torchwood/internal/infra/documentdb"
	"github.com/torchwoodcloud/torchwood/internal/infra/events"
	"github.com/torchwoodcloud/torchwood/internal/infra/functions"
	"github.com/torchwoodcloud/torchwood/internal/infra/health"
	"github.com/torchwoodcloud/torchwood/internal/infra/idgen"
	"github.com/torchwoodcloud/torchwood/internal/infra/messaging"
	"github.com/torchwoodcloud/torchwood/internal/infra/payments"
	"github.com/torchwoodcloud/torchwood/internal/infra/queue"
	"github.com/torchwoodcloud/torchwood/internal/infra/realtime"
	"github.com/torchwoodcloud/torchwood/internal/infra/storage"
	"github.com/torchwoodcloud/torchwood/internal/pkg/bootkit"
)

// Injectors from wire.go:

func wireBootstrap(app lynx.App) (*boot.Bootstrap, func(), error) {
	appConfig, err := NewAppConfig(app)
	if err != nil {
		return nil, nil, err
	}
	logger := bootkit.NewLogger(app)
	dataClients, cleanup, err := clients.NewDataClients(appConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	database := clients.NewDatabase(dataClients)
	repository := bunrepo.NewProjectRepository(database)
	grantsReconcileHook := NewGrantsReconcileHook(database, logger)
	scaleMetricsHook := NewScaleMetricsHook(database, logger)
	schemaReconcileHook := NewSchemaReconcileHook(database, logger)
	onStartHooks := bootkit.NewOnStarts(repository, database, logger, grantsReconcileHook, scaleMetricsHook, schemaReconcileHook)
	onStopHooks := bootkit.NewOnStops()
	apiKeyRepository := bunrepo.NewAPIKeyRepository(database)
	adminRepository := bunrepo.NewAdminRepository(database)
	adminProjectRepository := bunrepo.NewAdminProjectRepository(database)
	redisClient := clients.NewRedis(dataClients)
	redisAdminTokenRevokeStore := auth.NewRedisAdminTokenRevokeStore(redisClient)
	sessionRepository := bunrepo.NewSessionRepository(database)
	userRepository := bunrepo.NewUserRepository(database)
	membershipRepository := bunrepo.NewMembershipRepository(database)
	userRoles := client.NewUserRoles(userRepository, membershipRepository)
	redisOneTimeTokenStore := auth.NewRedisOneTimeTokenStore(redisClient)
	redisExecutionTokenService := functions.NewRedisExecutionTokenService(redisClient)
	cache := principalcache.New(redisClient)
	validator := infra.NewValidatorWithCache(appConfig, apiKeyRepository, repository, adminRepository, adminProjectRepository, redisAdminTokenRevokeStore, sessionRepository, userRepository, userRoles, redisOneTimeTokenStore, redisExecutionTokenService, cache)
	auditRepository := bunrepo.NewAuditRepository(database)
	redisRateLimiter := auth.NewRedisRateLimiter(redisClient)
	objectStore, err := storage.NewMinioObjectStore(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	checkers := health.NewCheckers(database, redisClient, objectStore)
	inviteCodeRepository := bunrepo.NewInviteCodeRepository(database)
	oAuthProviderRepository := bunrepo.NewOAuthProviderRepository(database, appConfig)
	redisRefreshRotationStore := auth.NewRedisRefreshRotationStore(redisClient)
	sessionService := infra.NewSessionServiceWithCache(appConfig, sessionRepository, userRoles, redisRefreshRotationStore, cache)
	redisOTPChallengeStore := auth.NewRedisOTPChallengeStore(redisClient, appConfig)
	redisOAuthStateStore := auth.NewRedisOAuthStateStore(redisClient)
	redisAccountTokenStore := auth.NewRedisAccountTokenStore(redisClient)
	redisLoginThrottle := auth.NewRedisLoginThrottleFromConfig(redisClient, appConfig)
	service, err := idgen.NewService(appConfig, redisClient, repository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mailerService := messaging.NewMailer(appConfig)
	smsService := messaging.NewSMSService(appConfig)
	mfaService := auth.NewTOTPService(appConfig, redisClient)
	mfaChallengeStore := auth.NewRedisMFAChallengeStore(redisClient)
	identityRepository := bunrepo.NewIdentityRepository(database)
	oAuthAuthenticatorFactory := auth.NewOAuthAuthenticatorFactory()
	weChatMiniProgramExchanger := auth.NewWeChatMiniProgramExchanger()
	otpGenerator := auth.NewOTPGenerator()
	sessionCookieVerifier := auth.NewSessionCookieVerifier(appConfig)
	account := client.NewAccount(appConfig, repository, inviteCodeRepository, oAuthProviderRepository, sessionService, redisOTPChallengeStore, redisOAuthStateStore, redisAccountTokenStore, redisLoginThrottle, redisRefreshRotationStore, service, mailerService, smsService, redisRateLimiter, userRoles, mfaService, mfaChallengeStore, redisOneTimeTokenStore, auditRepository, userRepository, identityRepository, sessionRepository, oAuthAuthenticatorFactory, weChatMiniProgramExchanger, otpGenerator, sessionCookieVerifier)
	accountService := clientgrpc.NewAccountService(account)
	eventOutbox := events.NewEventOutbox(database)
	documentDB := documentdb.NewPostgresDocumentDB(database, eventOutbox)
	idempotencyStore := bunrepo.NewIdempotencyStore(database)
	databases := client.NewDatabases(repository, documentDB, idempotencyStore)
	databasesService := clientgrpc.NewDatabasesService(databases)
	groupRepository := bunrepo.NewGroupRepository(database)
	groups := server.NewGroups(repository, userRepository, groupRepository, membershipRepository)
	clientGroups := client.NewGroups(groups, userRepository)
	groupsService := clientgrpc.NewGroupsService(clientGroups)
	orderRepo := bunrepo.NewPaymentOrderRepository(database)
	callbackEventRepo := bunrepo.NewPaymentCallbackEventRepository(database)
	fulfillmentRepo := bunrepo.NewPaymentFulfillmentRepository(database)
	defRepo := bunrepo.NewAssetDefRepository(database)
	holdingRepo := bunrepo.NewAssetHoldingRepository(database)
	ledgerRepo := bunrepo.NewAssetLedgerRepository(database)
	assetsAssets := assets.NewAssets(database, defRepo, holdingRepo, ledgerRepo, eventOutbox, logger, repository)
	planRepo := bunrepo.NewSubscriptionPlanRepository(database)
	subscriptionRepo := bunrepo.NewSubscriptionRepository(database)
	adapter := payments.NewStripeAdapter(appConfig)
	wechatAdapter := payments.NewWeChatAdapter(appConfig)
	alipayAdapter := payments.NewAlipayAdapter(appConfig)
	iosiapAdapter := payments.NewIosIapAdapter(appConfig)
	registry := payments.ProvideRegistry(adapter, wechatAdapter, alipayAdapter, iosiapAdapter)
	providerIndexRepo := bunrepo.NewProviderIndexRepository(database)
	subscriptionsSubscriptions := subscriptions.NewSubscriptions(appConfig, database, planRepo, subscriptionRepo, assetsAssets, orderRepo, registry, adapter, eventOutbox, logger, repository, providerIndexRepo)
	fulfiller := subscriptions.NewOrderFulfiller(assetsAssets, subscriptionsSubscriptions)
	paymentsPayments := payments2.NewPayments(appConfig, database, orderRepo, callbackEventRepo, fulfillmentRepo, fulfiller, registry, eventOutbox, logger, subscriptionsSubscriptions, repository, providerIndexRepo)
	paymentsService := clientgrpc.NewPaymentsService(paymentsPayments)
	assetsService := clientgrpc.NewAssetsService(assetsAssets)
	subscriptionsService := clientgrpc.NewSubscriptionsService(subscriptionsSubscriptions)
	dockerExecutor := functions.NewDockerExecutor(appConfig)
	dispatcherExecutor := functions.NewDispatcherExecutor(appConfig)
	executor, err := functions.ProvideExecutor(appConfig, dockerExecutor, dispatcherExecutor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	functionRepo := bunrepo.NewFunctionRepository(database)
	sharedQueue := queue.NewRedisQueue(redisClient)
	redisCounter := billing.NewRedisCounter(redisClient)
	semaphores := functions2.ProvideSemaphores(redisClient, appConfig)
	triggerRepo := bunrepo.NewFunctionTriggerRepository(database)
	clientQuotaLimiter := functions.NewClientQuotaLimiter(redisClient)
	functionsFunctions := functions2.NewFunctionsWithClientQuota(appConfig, executor, functionRepo, sharedQueue, redisCounter, repository, semaphores, redisExecutionTokenService, triggerRepo, clientQuotaLimiter)
	functionsService := clientgrpc.NewFunctionsService(functionsFunctions)
	analyticsIngestRepository := bunrepo.NewAnalyticsIngestRepository(database)
	ingest := analytics.NewIngest(analyticsIngestRepository, redisCounter, logger)
	analyticsService := clientgrpc.NewAnalyticsService(ingest)
	buildInfo := NewBuildInfo()
	healthService := servergrpc.NewHealthService(checkers, buildInfo)
	schemaManager := NewSchemaManager(database, documentDB)
	settingsWriter := bunrepo.NewProjectSettingsWriter(database)
	purger := storage.NewObjectPurger(objectStore)
	v := NewProjectsOptions(purger, appConfig)
	projects := server.NewProjects(repository, documentDB, database, schemaManager, adminProjectRepository, settingsWriter, v...)
	inviteCodes := server.NewInviteCodes(inviteCodeRepository)
	projectsService := servergrpc.NewProjectsService(projects, inviteCodes)
	uploadSessionStore := storage.NewRedisUploadSessionStore(redisClient)
	bucketRepository := bunrepo.NewBucketRepository(database)
	fileRepository := bunrepo.NewFileRepository(database)
	v2 := NewStorageOptions()
	storageStorage := storage2.NewStorage(appConfig, repository, objectStore, uploadSessionStore, bucketRepository, fileRepository, v2...)
	storageService := servergrpc.NewStorageService(storageStorage)
	users := server.NewUsers(repository, sessionService, database, userRepository, sessionRepository, groupRepository, membershipRepository)
	usersService := servergrpc.NewUsersService(users)
	policySet, err := runtime.ProvideMethodPolicies()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scopeVocabulary := runtime.ProvideScopeVocabulary(policySet)
	apiKeys := server.NewAPIKeys(apiKeyRepository, scopeVocabulary)
	apiKeysService := servergrpc.NewAPIKeysService(apiKeys)
	oAuthProviders := server.NewOAuthProviders(oAuthProviderRepository)
	oAuthProvidersService := servergrpc.NewOAuthProvidersService(oAuthProviders)
	servergrpcGroupsService := servergrpc.NewGroupsService(groups)
	serverDatabases := server.NewDatabases(repository, documentDB, idempotencyStore)
	servergrpcDatabasesService := servergrpc.NewDatabasesService(serverDatabases)
	servergrpcFunctionsService := servergrpc.NewFunctionsService(functionsFunctions)
	servergrpcPaymentsService := servergrpc.NewPaymentsService(paymentsPayments)
	servergrpcAssetsService := servergrpc.NewAssetsService(assetsAssets)
	servergrpcSubscriptionsService := servergrpc.NewSubscriptionsService(subscriptionsSubscriptions)
	usageRepo := bunrepo.NewUsageRepository(database)
	statementRepo := bunrepo.NewBillingStatementRepository(database)
	billingBilling := billing2.NewBilling(redisCounter, usageRepo, statementRepo, repository, fileRepository, logger)
	billingService := servergrpc.NewBillingService(billingBilling)
	consoleAuth := console.NewAuth(appConfig, adminRepository, redisAdminTokenRevokeStore, redisLoginThrottle, redisRefreshRotationStore)
	admins := console.NewAdmins(adminRepository, adminProjectRepository, database)
	setup := console.NewSetup(appConfig, admins, projects, consoleAuth, adminRepository, adminProjectRepository, repository)
	authService := consolegrpc.NewAuthService(consoleAuth, setup)
	adminsService := consolegrpc.NewAdminsService(admins)
	outboxRepository := bunrepo.NewOutboxRepository(database)
	outboxAdmin := events2.NewOutboxAdmin(outboxRepository, repository)
	outboxService := servergrpc.NewOutboxService(outboxAdmin)
	auditLogs := server.NewAuditLogs(auditRepository)
	auditLogsService := servergrpc.NewAuditLogsService(auditLogs)
	servergrpcAnalyticsService := servergrpc.NewAnalyticsService(ingest)
	grpcServer, err := runtime.NewGRPCServer(app, appConfig, validator, auditRepository, redisRateLimiter, checkers, accountService, databasesService, groupsService, paymentsService, assetsService, subscriptionsService, functionsService, analyticsService, healthService, projectsService, storageService, usersService, apiKeysService, oAuthProvidersService, servergrpcGroupsService, servergrpcDatabasesService, servergrpcFunctionsService, servergrpcPaymentsService, servergrpcAssetsService, servergrpcSubscriptionsService, billingService, redisCounter, authService, adminsService, outboxService, auditLogsService, servergrpcAnalyticsService, policySet)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileHandler, err := serverhttp.NewFileHandler(appConfig, validator, storageStorage, auditRepository, logger, policySet)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	oAuthHandler, err := serverhttp.NewOAuthHandler(account, appConfig, auditRepository, redisRateLimiter)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	functionsHandler, err := serverhttp.NewFunctionsHandler(appConfig, validator, functionsFunctions, auditRepository, logger, policySet)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	paymentsHandler, err := serverhttp.NewPaymentsHandler(paymentsPayments, logger, auditRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	triggerIPRateLimiter := functions.NewTriggerIPRateLimiter(redisClient, appConfig)
	triggerIPLimiter := NewTriggerIPLimiter(triggerIPRateLimiter)
	functionTriggersHandler, err := serverhttp.NewFunctionTriggersHandler(functionsFunctions, triggerIPLimiter, appConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	hub := realtime.NewHub(logger)
	handler, err := realtime2.NewHandler(appConfig, validator, documentDB, hub, logger, auditRepository)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcGatewayServer, err := runtime.NewGRPCGatewayServer(app, appConfig, checkers, fileHandler, oAuthHandler, functionsHandler, paymentsHandler, functionTriggersHandler, handler, policySet)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	subscriber := realtime.NewRealtimeSubscriber(redisClient, database, hub, logger)
	realtimeSubscriberService := NewRealtimeSubscriberService(subscriber, logger)
	metricsServer, err := runtime.NewMetricsServer(appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v3 := NewComponents(grpcServer, grpcGatewayServer, realtimeSubscriberService, metricsServer)
	v4 := bootkit.NewComponentBuilders()
	bootstrap := boot.New(onStartHooks, onStopHooks, v3, v4)
	return bootstrap, func() {
		cleanup()
	}, nil
}
