// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v1/functions.proto

package clientv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/torchwoodcloud/torchwood/genproto/shared/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeFunctionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	FunctionId string                 `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// 函数入参：JSON object 字符串（≤32KB，服务端校验形状与字节上限）。
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 可选：指定 deployment（必须 ready）；缺省用最新 ready。
	DeploymentId *string `protobuf:"bytes,3,opt,name=deployment_id,json=deploymentId,proto3,oneof" json:"deployment_id,omitempty"`
	// 可选客户端幂等键：网络超时重试防重复执行。(project, function, user, key)
	// 唯一去重，命中返回既有 execution 原样（进行中返回 running）。
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvokeFunctionRequest) Reset() {
	*x = InvokeFunctionRequest{}
	mi := &file_client_v1_functions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFunctionRequest) ProtoMessage() {}

func (x *InvokeFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_functions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFunctionRequest.ProtoReflect.Descriptor instead.
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_functions_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeFunctionRequest) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *InvokeFunctionRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *InvokeFunctionRequest) GetDeploymentId() string {
	if x != nil && x.DeploymentId != nil {
		return *x.DeploymentId
	}
	return ""
}

func (x *InvokeFunctionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type InvokeFunctionResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// completed | failed | running（幂等命中且执行仍在进行时）。
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 函数响应：stdout 末行 JSON（无合法 JSON 时为空）。
	Response      string `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeFunctionResponse) Reset() {
	*x = InvokeFunctionResponse{}
	mi := &file_client_v1_functions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeFunctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeFunctionResponse) ProtoMessage() {}

func (x *InvokeFunctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_functions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeFunctionResponse.ProtoReflect.Descriptor instead.
func (*InvokeFunctionResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_functions_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeFunctionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *InvokeFunctionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvokeFunctionResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_client_v1_functions_proto protoreflect.FileDescriptor

const file_client_v1_functions_proto_rawDesc = "" +
	"\n" +
	"\x19client/v1/functions.proto\x12\x13torchwood.client.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x15shared/v1/authz.proto\"\xce\x01\n" +
	"\x15InvokeFunctionRequest\x12'\n" +
	"\vfunction_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"functionId\x12\x1d\n" +
	"\x04data\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x18\x80\x80\x02R\x04data\x12(\n" +
	"\rdeployment_id\x18\x03 \x01(\tH\x00R\fdeploymentId\x88\x01\x01\x121\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x0eidempotencyKeyB\x10\n" +
	"\x0e_deployment_id\"o\n" +
	"\x16InvokeFunctionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse2\xb5\x01\n" +
	"\x10FunctionsService\x12\x98\x01\n" +
	"\x0eInvokeFunction\x12*.torchwood.client.v1.InvokeFunctionRequest\x1a+.torchwood.client.v1.InvokeFunctionResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/functions/{function_id}:invoke\x1a\x06\x92\xb2\x19\x02\b\x02B\xf7\x03\x92A\xb2\x03RR\n" +
	"\adefault\x12G\n" +
	"\x1dAn unexpected error response.\x12&\n" +
	"$\x1a\".torchwood.shared.v1.ErrorResponseZ\xab\x02\n" +
	"M\n" +
	"\x06Bearer\x12C\b\x02\x12.格式: Bearer <jwt>（Client API 登录态）\x1a\rAuthorization \x02\n" +
	"\x86\x01\n" +
	"\x06apiKey\x12|\b\x02\x12k项目绑定在密钥行上，不需要 X-Torchwood-Project。该头仅 Console admin 会话切换项目。\x1a\tX-API-Key \x02\n" +
	"Q\n" +
	"\x06cookie\x12G\b\x02\x129TORCHWOOD_session_console=<sid>（Console admin 会话）\x1a\x06Cookie \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00z \n" +
	"\x12x-torchwood-access\x12\n" +
	"\x1a\bend_userZ?github.com/torchwoodcloud/torchwood/genproto/client/v1;clientv1b\x06proto3"

var (
	file_client_v1_functions_proto_rawDescOnce sync.Once
	file_client_v1_functions_proto_rawDescData []byte
)

func file_client_v1_functions_proto_rawDescGZIP() []byte {
	file_client_v1_functions_proto_rawDescOnce.Do(func() {
		file_client_v1_functions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_functions_proto_rawDesc), len(file_client_v1_functions_proto_rawDesc)))
	})
	return file_client_v1_functions_proto_rawDescData
}

var file_client_v1_functions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_v1_functions_proto_goTypes = []any{
	(*InvokeFunctionRequest)(nil),  // 0: torchwood.client.v1.InvokeFunctionRequest
	(*InvokeFunctionResponse)(nil), // 1: torchwood.client.v1.InvokeFunctionResponse
}
var file_client_v1_functions_proto_depIdxs = []int32{
	0, // 0: torchwood.client.v1.FunctionsService.InvokeFunction:input_type -> torchwood.client.v1.InvokeFunctionRequest
	1, // 1: torchwood.client.v1.FunctionsService.InvokeFunction:output_type -> torchwood.client.v1.InvokeFunctionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_v1_functions_proto_init() }
func file_client_v1_functions_proto_init() {
	if File_client_v1_functions_proto != nil {
		return
	}
	file_client_v1_functions_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_functions_proto_rawDesc), len(file_client_v1_functions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_functions_proto_goTypes,
		DependencyIndexes: file_client_v1_functions_proto_depIdxs,
		MessageInfos:      file_client_v1_functions_proto_msgTypes,
	}.Build()
	File_client_v1_functions_proto = out.File
	file_client_v1_functions_proto_goTypes = nil
	file_client_v1_functions_proto_depIdxs = nil
}
